### ISSUE TITLE
Pressing up/down should leave cursor at end of line

### ISSUE THREAD

**Issue by spencerlyon2** [JunoLab/atom-julia-client#108]
Right now pressing up/down to navigate console history leaves the cursor at the start of the line. 

I think it is a good idea to have the cursor go to the end of the line instead (as in the REPL)

**Comment by one-more-minute** [comment]
This makes sense but unfortunately is a bit fiddly to do given the assumptions the prefix work currently makes. Will take a look once it starts to annoy me enough though :)
