### ISSUE TITLE
Feature request: Jump to file:line from console

### ISSUE THREAD

**Issue by malmaud** [JunoLab/atom-julia-client#11]
eg, if I call `@which` from the console, it would be cool to click on the filename and line number that it outputs and have an editor pane jump to the named buffer location.

**Comment by one-more-minute** [comment]
I had this working in Juno/LT for error messages as well as method lists etc. – definitely planning to get it working in Atom as well.

**Comment by one-more-minute** [comment]
your wish is my command

**Comment by malmaud** [comment]
thanks! finally i can now live the life ive imagined for myself.
