### ISSUE TITLE
MethodError: `get` has no method matching get(::Dict{AbstractString,Any}, ::Symbol)

### ISSUE THREAD

**Issue by mwsohn** [JunoLab/atom-julia-client#114]
I am using Julia 0.4.3 and have this error message. So far I have been able to use Atom at all.

MethodError: `get` has no method matching get(::Dict{AbstractString,Any}, ::Symbol)
Closest candidates are:
  get{K,V}(::Dict{K,V}, ::Any, !Matched::Any)
  get(!Matched::ObjectIdDict, ::ANY, !Matched::ANY)
  get{K}(!Matched::WeakKeyDict{K,V}, ::Any, !Matched::Any)
  ...
 in get′ at C:\Users\Min\.julia\v0.4\MacroTools\src\examples/destruct.jl:9
 in anonymous at C:\Users\Min\.julia\v0.4\Atom\src\completions.jl:6
 in handlemsg at C:\Users\Min\.julia\v0.4\Atom\src\comm.jl:56
 [inlined code] from C:\Users\Min\.julia\v0.4\Atom\src\comm.jl:8
 in anonymous at task.jl:63

**Comment by MikeInnes** [comment]
Are you on master of Atom.jl? if so you'll need the master branch of atom-julia-client, too.

**Comment by JeremyCavanagh** [comment]
I have the same problem. My installation route is via homebrew and not directly from the GitHub masters. I update and upgrade via brew on a daily basis. This error started occuring less than a week ago after I used an app to clear disk space which some how removed atom, so, I reinstalled via homebrew ever since then I have this error. I am running Julia 0.4.3 and Atom 1.5.3.

Any ideas?

**Comment by rapus95** [comment]
even when getting atom-julia-client(Atom-side) and Atom(Julia-side) to work together (removing the package in Julia and installing it again) CodeTools begins to make problems every time i enter a new key. When searching for allcompletions in CodeTools I find that the whole process has been changed 14 days ago (https://github.com/JunoLab/CodeTools.jl/commit/6b8984ea19ba7dd6bbfda731a360bf47f4410700) and thus there is no such field anymore. So the final point is whether there is any easy way to align all modules needed for having only a working combination of them installed?

Error described above:
```julia
UndefVarError: allcompletions not defined
 in anonymous at C:\Users\necka\.julia\v0.5\Atom\src\completions.jl:9
 [inlined code] from dict.jl:723
 in handlemsg at C:\Users\necka\.julia\v0.5\Atom\src\comm.jl:57
 [inlined code] from C:\Users\necka\.julia\v0.5\Atom\src\comm.jl:8
 in anonymous at task.jl:63
```

**Comment by MikeInnes** [comment]
I recently pushed updates to the Atom plugins and Julia packages. If you all make sure you're on the latest stable version these issues should be resolved, but otherwise let me know.

**Comment by rapus95** [comment]
It's again working now

**Comment by Varanas** [comment]
Closing, since this seems to be fixed on the newest release.
If not, please reopen this issue, @mwsohn.
