### ISSUE TITLE
Conflict with PyPlot?

### ISSUE THREAD

**Issue by Kindpire** [JunoLab/atom-julia-client#121]
Hi,

I found once I "using PyPlot", whatever I input to the jl file, the atom would report:
Julia Client - Internal Error:
MethodError: `flatten` has no method matching flatten(::Text{Function})
in fullsignature at /path/CodeTools/src/summaries.jl:30
in withmeta at /path/CodeTools/src/completions.jl:49
in withmeta at /path/CodeTools/src/completions.jl:58
in namecompletions_ at /path/CodeTools/src/completions.jl:63
in anonymous at /path/CodeTools/src/utils.jl:16
in completions at /path/CodeTools/src/completions.jl:190
in completions at /path/CodeTools/src/completions.jl:195
in anonymous at /path/Atom/src/completions.jl:19
in handlemsg at /path/Atom/src/comm.jl:56
[inlined code] from /path/Atom/src/comm.jl:8
in anonymous at task.jl:63

or just:
Julia Client – Internal Error
MethodError: `flatten` has no method matching flatten(::Text{Function})

Any idea about how to fix it?
Thanks!

**Comment by Kindpire** [comment]
Oh, I'm using OS X 10.11.3.

Julia 0.4.3
PyPlot 2.1.1

Atom 1.5.3
julia client 0.4.0
language-julia 0.5.0
ink 0.4.0

**Comment by MikeInnes** [comment]
Thanks, I think I know why this is happening – will take a look soon.

**Comment by pfitzseb** [comment]
Probably. I think this is because PyPlot's docstrings aren't in markdown.
If that's correct, accepting `Text`, `Array` and some other types [here](https://github.com/JunoLab/CodeTools.jl/blob/7499d1e4b4ee5db47252b076edac989b9e96d1d0/src/summaries.jl#L7) might do the trick.

**Comment by MikeInnes** [comment]
For now we can just fail out if docs aren't `MD` objects. Later on it'd be good to support `Text` etc.

**Comment by stanislavkazmin** [comment]
So, what it the workaround for now? Could someone say me, ho to change the file mentioned by pfitzseb? Thanks.

**Comment by ElbaKramer** [comment]
For a quick fix, I added the following line after the 7th line in the file `CodeTools/src/summaries.jl`
`flatten(arr::Array{Any,1}) = MD(flat_content!(arr))`

**Comment by stanislavkazmin** [comment]
Ok thank you. Now I get the same error for Text{Function} what do I have to add for this?

**Comment by stanislavkazmin** [comment]
When I add:

` flatten(text::Text{Function}) = MD(flat_content!(text))`

I get the error:

MethodError: `start` has no method matching start(::Text{Function})

**Comment by alstat** [comment]
Having the same error, I decided to remove it and use other plotting alternatives.

**Comment by ElbaKramer** [comment]
I don't know this is correct but I added the following lines and there is no error so far.
Added after the 7th line in the file `CodeTools/src/summaries.jl`:
`flatten(arr::Array{Any,1}) = MD(flat_content!(arr))`
`flatten(txt::Text{Function}) = MD(flat_content!([txt]))`

**Comment by krisztiankosi** [comment]
It looks like working for me, thnx

**Comment by zsoerenm** [comment]
+1

**Comment by ChrisRackauckas** [comment]
Is someone working on getting this fix into master?

**Comment by nw11** [comment]
just tested, thanks!

**Comment by gabrielgellner** [comment]
Is this fix in the currently tagged version? I get this message all the time :(

**Comment by pfitzseb** [comment]
No,  ot yet. 
`Pkg.checkout("CodeTools", branch="julia-0.4")` should do the trick until it is.

**Comment by Mahrgell** [comment]
> Pkg.checkout("CodeTools", branch="julia-0.4") should do the trick until it is.
My Atom answers this with "unrecognized keyword argument "branch""
How to do it right?

**Comment by pfitzseb** [comment]
Should be `Pkg.checkout("CodeTools", "julia-0.4")`, sorry.

**Comment by Mahrgell** [comment]
Hi, thanks a lot for your help.
Sadly I'm still failing at getting it to work :/

New error message is:

```
INFO: Checking out CodeTools julia-0.4...
fatal: Cannot update paths and switch to branch 'julia-0.4' at the same time.
Did you intend to checkout 'origin/julia-0.4' which can not be resolved as commit?
failed process: Process(`git '--work-tree=C:\Users\___\.julia\v0.4\CodeTools' '--git-dir=C:\Users\___\.julia\v0.4\CodeTools\.git' checkout -q -B julia-0.4 -t origin/julia-0.4`, ProcessExited(128)) [128]
```

**Comment by pfitzseb** [comment]
Strange -- maybe try `Pkg.checkout("CodeTools")` first to get the newest version of that repo and then `Pkg.checkout("CodeTools", "julia-0.4")` again?
