### ISSUE TITLE
Start up julia in the project's directory

### ISSUE THREAD

**Issue by tlnagy** [JunoLab/atom-julia-client#124]
Right now, it seems as julia is always started in my home directory instead of the project directory so I have run `cd(/path/to/project/dir)` everytime I open Atom. Is there something misconfigured with my system or is this the expected behavior?

**Comment by Varanas** [comment]
Depends -- do you only have one project dir open or multiple? If there's only one, we should automatically set the working dir, but if there are multiple we default to your HOME dir.

You can also use the `Julia Client: Work in File Folder` command or, alternatively, something like `cd(dirname(@__FILE__))`.

I'm not totally happy with that behaviour, but haven't invested much thought into a better heuristic yet --  do tell if you have any ideas! :)

**Comment by tlnagy** [comment]
Actually, I think this is the latter case: I have multiple directories open. Wouldn't it make sense to default the julia kernel to the selected directory? Starting the kernel in the root directory doesn't seem useful to me.

**Comment by pfitzseb** [comment]
So we'd set Julia's cwd to the directory containing the currently opened file? Hm, probably better than the current behaviour. I guess we could also try evaling every file's contents in it's on dir.

**Comment by MikeInnes** [comment]
Defaulting to the first project folder if there are multiple seems like a good idea. As well as perhaps checking if the project folder is actually a file and jumping up a level.

**Comment by pfitzseb** [comment]
Yep. (I still kinda think a project folder should never be a file...)

**Comment by pfitzseb** [comment]
Alright, this has been implemented on master: We now start Julia in the first open project folder (or, if that is a file, in it's parent dir).
