### ISSUE TITLE
Uncaught Error: spawn where ENOENT

### ISSUE THREAD

**Issue by doyaklee** [JunoLab/atom-julia-client#125]
Hello, I tried to use Julia Console inside Atom, but encountered an error.
I followed the instruction for the installation.
I'm using three machines (two desktops and one laptop). All are Windows 10 machines. 
For two of them, there were no errors, but for one machine, when I tried to enter an expression in the console, I got the following error messages. 
Also, I've checked that Julia works in Atom with Build package, so there's no problem about it.

![cc](https://cloud.githubusercontent.com/assets/14086459/13522067/288b2b56-e1bb-11e5-8351-efe47c6f4efc.png)

Could you point out where the problem comes from? Thanks.

**Comment by Varanas** [comment]
This is probably because of [this](https://github.com/JunoLab/atom-julia-client/blob/2e3b891f031f46d07ad30da1b34adc5bd03ae9e4/lib/connection/process.coffee#L51-L60) check. 
Are you sure the path to the Julia binary is specified correctly?

**Comment by doyaklee** [comment]
I'm 100% sure that the path to the Julia binary is specified correctly. 
In the cmd, I can launch Julia, and in Atom, I can build .jl file using "build" package.

Anyway it didn't work and produced the same error message, so in the Julia Client: Setting, I manually set the Julia Path. Then, when I type something in the console, it didn't produce error message but did nothing as described in #130.

**Comment by pfitzseb** [comment]
In #130, there is an error message -- so do you get one when you spell out the path or not? :)

Also, it's quite strange that Atom can't call `where`. Can you try opening cmd and type something like `where where`? This should a) work and b) return `C:\Windows\System32\where.exe`.

**Comment by doyaklee** [comment]
Sorry for the confusion. I don't know why but C:\Windows\System32 was not included in the path. So, after including it, it seems that now Julia-client finds the default path for Julia. (I've also checked that in the cmd `where` and `where where` work fine.

But, Console is still not working. Following is the error message I get.

`/C:/Users/Benjamin/.atom/packages/julia-client/lib/connection/process.coffee:151 Uncaught (in promise) TypeError: Cannot read property '1' of null  at Object.module.exports.jlprocess.spawnJulia (file:///C:/Users/Benjamin/.atom/packages/julia-client/lib/connection/process.coffee:101:51)
    at file:///C:/Users/Benjamin/.atom/packages/julia-client/lib/connection/process.coffee:82:8
    at process._tickCallback (node.js:368:9)`

**Comment by pfitzseb** [comment]
Can you try calling `powershell $PSVersionTable.PSVersion.Major` in the command line?

**Comment by doyaklee** [comment]
Oh. I didn't know that `powershell` should be in the path.
Since the command you suggested didn't work, I included `C:\Windows\System32\WindowsPowerShell\v1.0` in the path.
After that, now Julia Console finally works in the Atom. Thanks a lot!

**Comment by pfitzseb** [comment]
Great! 
I'm pretty sure that `PATH` includes 
```
%SystemRoot%\system32
%SystemRoot%
%SystemRoot%\System32\Wbem
%SystemRoot%\System32\WindowsPowerShell\v1.0\
```
in a standard Windows installation.

**Comment by doyaklee** [comment]
Yeah. As said above, I have three Windows machines, and in the other two machines, there were no problems. I don't know why in this specific machine, those basic paths are missing. 
Thanks for figuring it out!

**Comment by pfitzseb** [comment]
I guess we could try to make it more robust by just calling the correct `*.exe` instead of relying on it being in `PATH`. That said, I think I'll just add a more informative error message if `where` or `powershell` couldn't be spawned.
