### ISSUE TITLE
Truncated path names on Windows

### ISSUE THREAD

**Issue by EricForgy** [JunoLab/atom-julia-client#128]
![image](https://cloud.githubusercontent.com/assets/8954730/13635937/dea0f9e8-e639-11e5-8f24-2f2d48a80b41.png)

~~~julia
julia> versioninfo()
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
~~~

https://gitter.im/JunoLab/Juno?at=56dfb814a549284116699372

**Comment by EricForgy** [comment]
Some notes:

Here is [line 378 in client.jl](https://github.com/JuliaLang/julia/blob/v0.4.2/base/client.jl#L378) in `_start` from the error message above:

~~~julia
375    function _start()
376        opts = JLOptions()
377        try
378            (quiet,repl,startup,color_set,history_file) = process_options(opts,copy(ARGS))
~~~

It is calling `process_options`.

Here is [line 280](https://github.com/JuliaLang/julia/blob/v0.4.2/base/client.jl#L280) of `process_options`:

~~~julia
215    function process_options(opts::JLOptions, args::Vector{UTF8String})
....
280            include(args[1])
~~~

Here is [line 304](https://github.com/JuliaLang/julia/blob/v0.4.2/base/loading.jl#L304) from `include_from_node1`:

~~~julia
295    function include_from_node1(_path::AbstractString)
296        path, prev = _include_dependency(_path)
...
304                result = Core.include(path)
~~~

Here is [line 261](https://github.com/JuliaLang/julia/blob/v0.4.2/base/boot.jl#L261) in boot.jl:

~~~julia
261    include(fname::ByteString) = ccall(:jl_load_, Any, (Any,), fname)
~~~

---

Looking at the above, it seems that either 

1. ARGS is already bad when `process_options` is called from within `_start` or 
2. `_include_dependency` has a bug in `include_from_node1`

Since my code runs fine from the REPL, I am inclined to exclude 2. leaving the possibility that ARGS is bad.

Where does ARGS come from?

**Comment by EricForgy** [comment]
I'm not familiar with the flow, but if I want to modify `atom-julia-client/script/boot.jl`, how can I see my changes reflected? I tried simply adding some println's and they are not appearing. Then, after adding the println's, I went back and did an apm install again. Still don't see them. 

Is there another step I am missing or is the error above occurring before script/boot.jl is being called?

Do I need to recompile anything? :astonished:

**Comment by pfitzseb** [comment]
Ooookay, my bad. I forgot to actually do something useful when I said I was escaping the path... Sorry about that and thanks for the patience :)

This should be fixed on master with [this](https://github.com/JunoLab/atom-julia-client/commit/b51d83ba9228a9980b964247fd771a8477150e0e) commit.

> I'm not familiar with the flow, but if I want to modify atom-julia-client/script/boot.jl, how can I see my changes reflected? I tried simply adding some println's and they are not appearing. Then, after adding the println's, I went back and did an apm install again. Still don't see them. 

Restarting Atom or reloading it (with `Ctrl-Alt-R`) should do the trick. Problem is you still wouldn't have seen the `println`s since we didn't even get to executing our `boot.jl` properly.

**Comment by EricForgy** [comment]
![image](https://cloud.githubusercontent.com/assets/8954730/13695737/58dc498e-e79c-11e5-92f4-9a170dc9f6b2.png)

Yay! :tada: :tada: :tada: 

Thank you so much @pfitzseb 

Have a great weekend! :beers:
