### ISSUE TITLE
Scrolling of inline results

### ISSUE THREAD

**Issue by nilshg** [JunoLab/atom-julia-client#13]
I've mentioned most of this [in the Juno forum](http://discuss.junolab.org/t/announcing-julia-ide-work-in-atom/297/4), but let me collect my observations here:

- Result popups and autocomplete suggestions that would extend below the lower bound of the screen flicker back and forth at a speed that renders them unreadable; this seems to be an Atom issue brought up [here](https://github.com/atom/atom/issues/8295).
- Large matrices and vectors simply extend beyond the result popup, and it's not possible to scroll through them as in JunoLT:
![d07bbb39eeeb5bccfa9a9bad5c3ae16172481319_1_479x500](https://cloud.githubusercontent.com/assets/7264491/9516133/8cd5fe5e-4c9e-11e5-9241-36428d396b0f.JPG)
- In the console, random newlines are added to print output (the following should appear on three lines, and does so when running the code from the REPL):
![39a72f493bbc4f0a3a5c67dc865cedb9c9455927](https://cloud.githubusercontent.com/assets/7264491/9516166/c1a913f0-4c9e-11e5-9ef7-81e2b4d4ccab.JPG)
- Some error messages get so long that they become unreadable (screengrab is from a screen with 1920 pixels width and fontsize 12, with the default Atom fontsize this message would extend beyond the length of the screen:
![error](https://cloud.githubusercontent.com/assets/7264491/9516215/0d47c694-4c9f-11e5-95b8-002901a9a412.JPG)

**Comment by Varanas** [comment]
Relevant to the first point: [#8540](https://github.com/atom/atom/issues/8540) and [#6857](https://github.com/atom/atom/issues/6857).

Second point: Should be fixed with [this](https://github.com/JunoLab/atom-ink/pull/3), though I'm not sure if it works in your case to. Would you mind trying it and reporting back?

Third one is [this](https://github.com/JunoLab/atom-ink/issues/5).

**Comment by nilshg** [comment]
I'm a little confused; the PR is merged but the `ink.less` file installed on my local machine doesn't contain this change, even though I installed the atom client on here after this PR was merged!?

In any case, I simply added the two lines manually and now all displays are on a single line, with an added scroll bar - I'm not sure this is how it should be?

**Comment by Varanas** [comment]
It should look like this, unless I messed up something with the PR: 
![juno_array](https://cloud.githubusercontent.com/assets/6735977/9616569/28820ece-50ff-11e5-982b-12a797a37705.PNG)

You could try manually installing ink as described [here](https://github.com/JunoLab/atom-julia-client/tree/master/docs).

**Comment by nilshg** [comment]
Okay, I messed up while manually inserted the two lines from your PR, went back to the ink repo and simply copied the entire `ink.less` file from there. Works exactly like in your screen grab now, thanks!

**Comment by one-more-minute** [comment]
@Varanas I tweaked this a bit, check out how scroll bars work now and let me know what you think.

**Comment by Varanas** [comment]
@one-more-minute I like! :) Though I'd kinda like a monotype font for the results, looks a bit awkward otherwise...

**Comment by one-more-minute** [comment]
See JunoLab/atom-ink#7 for the console buffering issue. @nilshg hope you won't mind if I repurpose this for the scrolling issue, since there are other issues tracking the other things.

**Comment by nilshg** [comment]
I feel like I saw an email notification a few days (weeks?) ago of someone saying the flickering outputs issue had been solved in Atom, is this the case? I'm still getting it, so was wondering whether I just imagined this email or am just out of sync with a master of something.

**Comment by one-more-minute** [comment]
I think most of these issues are fixed by now – but let me know if there's anything else I can polish up.
