### ISSUE TITLE
Console Does not respond, no error message given

### ISSUE THREAD

**Issue by fbanez** [JunoLab/atom-julia-client#130]
I am very new at Julia.I am having a problem with Atom/Julia. I think a similar one has been reported in https://github.com/JunoLab/atom-julia-client/issues/126. I installed it this week and it was working until today.
The console does not give anything. It seem to be "thinking" but does not give an error. I am using Mac El Capitan. This is what appears in when I do Cmd-Alt-I. Thank you very much.

/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:957 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details./deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:957 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
events.js:141 Uncaught Error: getaddrinfo ENOTFOUND localhost
events.js:141 Uncaught Error: getaddrinfo ENOTFOUND localhosterrnoException @ dns.js:25onlookup @ dns.js:76

**Comment by pfitzseb** [comment]
I think we're finding the julia binary correctly here, but there's a problem with communication. Can you try something like `ping localhost` in a terminal?

**Comment by fbanez** [comment]
You were right! 
ping localhost did not respond. So I went to look to me etc/hosts file. It seems that the problem was there.
It works now! Thank you very much!!

**Comment by MikeInnes** [comment]
Is this something we can/should guard against, e.g. by connecting to `127.0.0.1` directly?

**Comment by pfitzseb** [comment]
Yeah, I guess we could do that, but I'm not sure if it'd be worth it. The wiki article for localhost says that `127.0.0.1` isn't *always* the IP of the loopback device (it is "for most devices"). 
But tbh, I've never seen a system where `localhost` behaved strangely. or `127.0.0.1` wasn't the loopback device.
