### ISSUE TITLE
Installing and running Julia in Juno

### ISSUE THREAD

**Issue by ssingleton** [JunoLab/atom-julia-client#132]
Please forgive this noob question. I couldn't find where to download the Juno Bundle and attempted the [manual install](https://github.com/JunoLab/atom-julia-client/tree/master/manual). When I open the command palette and type Julia, I do not see that Julia-related commands are now available. And I am not sure how to connect Atom and Julia together.

I am just trying to get to a setting where I am comfortable: doing statistics and econometrics. I am used to being able to open MATLAB or R and just start importing data and multiplying matrices...

This is what I am getting and I am not sure where to go next:

![image](https://cloud.githubusercontent.com/assets/7118968/13859828/a3ca142e-ec85-11e5-8f54-454c82d06a14.png)

Thank you in advance for your help!

**Comment by pfitzseb** [comment]
The path should point to `...\julia-0.4.3\bin\julia.exe` and can be changed by opening the control panel via `Ctrl-Shift-P`, typing `Settings View: Open`, and navigating to `Packages` -> `julia-client` -> `Settings`. 

That said, there will probably be some more errors should you try to open a project folder in your user directory (see #128). As soon as we tag a new version of the relevant packages, you should update and that error will be fixed as well.

**Comment by ssingleton** [comment]
is there a bundle that can run the install for me?

I keep getting one of these two errors:

[image: Inline image 1]
[image: Inline image 2]

**Comment by pfitzseb** [comment]
No, the there were some problems associated with using the bundles, so until someone fixes them there aren't any.
The pictures didn't come through, btw. It should be enough to just append `.exe` to the Julia Path in the settings, so let me know if that doesn't work.

**Comment by ssingleton** [comment]
I did append to .exe. And I still get these responses:

![image](https://cloud.githubusercontent.com/assets/7118968/13899752/b9e7c3c0-edf5-11e5-8820-4940982555b4.png)


![image](https://cloud.githubusercontent.com/assets/7118968/13899754/bdb1be5c-edf5-11e5-9a35-862f23836f13.png)

**Comment by pfitzseb** [comment]
Yeah, the path setting is correct in the second screenshot. What you're seeing there is #128, which will be fixed in the next release.

**Comment by ssingleton** [comment]
Does this mean that I just wait until the next release (of Juno, Atom or Julia) comes out? Is there anything I can do?

**Comment by pfitzseb** [comment]
The new versions are being pushed right this moment, so you should be able to update the relevant plugins (`julia-client`, `ink` and `Atom.jl` in Julia) and should be good to go. 
Thanks for the patience!

**Comment by ssingleton** [comment]
Thank you for the attention!

I'll update the relevant plug ins and respond with my success. Do I need to
reinstall Juno or Atom?

**Comment by pfitzseb** [comment]
No, it should be enough to just go the package settings in Atom and click the update button there. The Julia package (`Atom.jl`) can then be updated after you get Juno to work.

**Comment by ssingleton** [comment]
omg, it works! now I can start programming. Thank you so much!

By the way, I want a pane to show what variables, data and functions I have
created or uploaded. How do I make this appear?

Also, is there a pane that I can query to ask for help, i.e. what does the
command "collect()" do and what arguments does it take? I'd like a
dedicated pane to answer both help queries and display graphs. (i am
effectively trying to get Juno to behave a little like R Studio)

I have already successfully made it do a few other things that are
important to me, so thank you for that!

And thank you again for answering my question and updating the packages to
solve my problem!!

**Comment by MikeInnes** [comment]
> (i am
effectively trying to get Juno to behave a little like R Studio)

This is basically what we're aiming for over time, but things like the workspace aren't implemented just yet. You can get basic help by typing `?collect` into the console.

**Comment by pfitzseb** [comment]
Great! :)
- Your first point isn't really implemented yet, unfortunately, but there has been some work on it.
- You can get docs for a method by pressing `Ctrl-J Ctrl-D` when the cursor is over that method (it looks a bit ugly, but works).
- `Ctrl-J Ctrl-P` will open the plot pane, but not many plotting packages will display in there yet. Gadfly should definitely work though. More to come soonish, I think.

**Comment by ssingleton** [comment]
Cool. I'm just happy to already have this available and that you all are
investing so much time to make this work -- seriously, thank you!!

until then, I still have pen and paper, and my projects are not that
complex yet as I am still trying to learn Julia!

Is there a listhost I can sign up for that will inform me when Juno updates
and what new features become available?

(also, we can close this issue now, too)
