### ISSUE TITLE
Installing and running Julia in Juno

### ISSUE THREAD

**Issue by ssingleton** [JunoLab/atom-julia-client#133]
Please forgive this noob question. I couldn't find where to download the Juno Bundle and attempted the [manual install](https://github.com/JunoLab/atom-julia-client/tree/master/manual). When I open the command palette and type Julia, I do not see that Julia-related commands are now available. And I am not sure how to connect Atom and Julia together.

I am just trying to get to a setting where I am comfortable: doing statistics and econometrics.

Thank you in advance for your help!

**Comment by MikeInnes** [comment]
Hey @ssingleton, did you manage to resolve this?

**Comment by pfitzseb** [comment]
This is #132.

**Comment by MikeInnes** [comment]
Ah it's a dup, thanks.

**Comment by ssingleton** [comment]
I have not! I have asked another friend for help. i am not sure what I am doing wrong. here is what i am seeing:

![image](https://cloud.githubusercontent.com/assets/7118968/13899728/767cd026-edf5-11e5-81bd-c0071f6b1ff5.png)


![image](https://cloud.githubusercontent.com/assets/7118968/13899729/7bd5d8ce-edf5-11e5-99fb-2060725c9277.png)

**Comment by ssingleton** [comment]
I tried it with julia.exe; with quotation marks and without. I honestly don't know what I have done wrong. Thankfully I have been able to use Julia Box during this time.

I wish the manual install directions were more clear
