### ISSUE TITLE
 MbedTLS not properly installed

### ISSUE THREAD

**Issue by gvk489** [JunoLab/atom-julia-client#134]
I am having troubles during the installation. After `Pkg.update()` gives 
> INFO: No packages to install, update or remove

and `Pkg.add("Atom")` puts the right a folder atom in the x84 folders there is a problem with ` using Atom` which tells me that the package MbedTLS is not not propperly installed. 

> ERROR: LoadError: MbedTLS not properly installed. Please run Pkg.build("MbedTLS")
 in error at ./error.jl:21
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/xx/.julia/v0.4/MbedTLS/src/MbedTLS.jl, in expression starting on line 42
ERROR: LoadError: Failed to precompile MbedTLS to /home/xx/.julia/lib/v0.4/MbedTLS.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:384
 in require at ./loading.jl:224
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/xx/.julia/v0.4/HttpServer/src/HttpServer.jl, in expression starting on line 9
ERROR: LoadError: LoadError: Failed to precompile HttpServer to /home/xx/.julia/lib/v0.4/HttpServer.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:384
 in require at ./loading.jl:224
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/xx/.julia/v0.4/Mux/src/server.jl, in expression starting on line 1
while loading /home/xx/.julia/v0.4/Mux/src/Mux.jl, in expression starting on line 22
ERROR: LoadError: LoadError: Failed to precompile Mux to /home/xx/.julia/lib/v0.4/Mux.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:384
 in require at ./loading.jl:224
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/xx/.julia/v0.4/Blink/src/content/content.jl, in expression starting on line 1
while loading /home/xx/.julia/v0.4/Blink/src/Blink.jl, in expression starting on line 8
ERROR: LoadError: Failed to precompile Blink to /home/xx/.julia/lib/v0.4/Blink.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:384
 in require at ./loading.jl:224
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/xx/.julia/v0.4/Atom/src/Atom.jl, in expression starting on line 5
ERROR: Failed to precompile Atom to /home/xx/.julia/lib/v0.4/Atom.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:384
 in require at ./loading.jl:250

I naturally have been running `Pkg.build("MbedTLS")` which resulted in 

> INFO: Building MbedTLS
INFO: Attempting to Create directory /home/xx/.julia/v0.4/MbedTLS/deps/downloads
INFO: Directory /home/xx/.julia/v0.4/MbedTLS/deps/downloads already created
INFO: Downloading file https://cache.julialang.org/https://tls.mbed.org/download/mbedtls-2.1.1-apache.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
===============================[ ERROR: MbedTLS ]===============================
LoadError: failed process: Process(`curl -f -o /home/xx/.julia/v0.4/MbedTLS/deps/downloads/mbedtls-2.1.1-apache.tgz -L https://cache.julialang.org/https://tls.mbed.org/download/mbedtls-2.1.1-apache.tgz`, ProcessExited(77)) [77]
while loading /home/xx/.julia/v0.4/MbedTLS/deps/build.jl, in expression starting on line 69
=================================[ BUILD ERRORS]===============================
WARNING: MbedTLS had build errors.

 - packages with build errors remain installed in /home/xx/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("MbedTLS")`
 - build a single package by running its `deps/build.jl` script

===============================================================================

I have a fresh julia v0.4 after `git pull && make`, and Atom1.5.3 with julia client, language-julia, latex completion, ink and autocomplete-julia. 

I had to install mbedtls with 
`git clone https://github.com/ARMmbed/mbedtls.git mbedtls.git
cd mbedtls.git
SHARED=1 make no_test
sudo make install`

after I run recommended ` `Pkg.build("MbedTLS")`` again same error message. 

Do you know what I am doig wrong?

**Comment by pfitzseb** [comment]
This seems to be a problem with certificates, but not sure. The same error has been reported at https://github.com/JuliaWeb/MbedTLS.jl/issues/34, and the guys over there can probably help you more competently than me.

A quick fix that might or might not work is to change the URLs in `.julia/v0.4/MbedTLS/deps/build.jl` so as to only contain the real URL without the caching stuff, i.e. `https://tls.mbed.org/download/mbedtls-2.1.1-apache.tgz`. 

Should you want to attempt manual installation, you should probably do something along [those](https://github.com/JuliaWeb/MbedTLS.jl/blob/98127b93a85461f08d6c1f0b82e987691469a1d4/deps/build.jl#L34-L48) lines and make sure it's on your path.

**Comment by gvk489** [comment]
After running `Pkg.build("MbedTLS")` some time later again, installation finally succeeded. Probably my bad I guess. Thanks for the quick response though!

**Comment by pfitzseb** [comment]
Nah, it may be that there was something wrong with the cache server or something. Glad it's working for you though!
