### ISSUE TITLE
error calling using Atom

### ISSUE THREAD

**Issue by augustot2** [JunoLab/atom-julia-client#141]
I'm having the following error when calling, using Atom:
DISCLAIMER: I'm using julia Version 0.5.0-dev+1491 on Ubuntu 14.04

julia> using Atom
INFO: Precompiling module Atom...
WARNING: could not import Base.iteratorsize into AbstractTrees
ERROR: LoadError: UndefVarError: SizeUnknown not defined
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:392
 [inlined code] from boot.jl:263
 in anonymous at no file:0
 in eval at ./boot.jl:263
 [inlined code] from ./sysimg.jl:14
 in process_options at ./client.jl:254
 in _start at ./client.jl:377
while loading /home/augusto/.julia/v0.5/AbstractTrees/src/AbstractTrees.jl, in expression starting on line 10
ERROR: LoadError: LoadError: Failed to precompile AbstractTrees to /home/augusto/.julia/lib/v0.5/AbstractTrees.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:471
 in require at ./loading.jl:312
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:392
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:392
 [inlined code] from boot.jl:263
 in anonymous at no file:0
 in eval at ./boot.jl:263
 [inlined code] from ./sysimg.jl:14
 in process_options at ./client.jl:254
 in _start at ./client.jl:377
while loading /home/augusto/.julia/v0.5/JuliaParser/src/token.jl, in expression starting on line 4
while loading /home/augusto/.julia/v0.5/JuliaParser/src/JuliaParser.jl, in expression starting on line 7
ERROR: LoadError: LoadError: LoadError: Failed to precompile JuliaParser to /home/augusto/.julia/lib/v0.5/JuliaParser.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:471
 in require at ./loading.jl:312
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:392
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:392
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:392
 [inlined code] from boot.jl:263
 in anonymous at no file:0
 in eval at ./boot.jl:263
 [inlined code] from ./sysimg.jl:14
 in process_options at ./client.jl:254
 in _start at ./client.jl:377
while loading /home/augusto/.julia/v0.5/CodeTools/src/parse/scope.jl, in expression starting on line 6
while loading /home/augusto/.julia/v0.5/CodeTools/src/parse/parse.jl, in expression starting on line 1
while loading /home/augusto/.julia/v0.5/CodeTools/src/CodeTools.jl, in expression starting on line 10
ERROR: LoadError: LoadError: Failed to precompile CodeTools to /home/augusto/.julia/lib/v0.5/CodeTools.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:471
 in require at ./loading.jl:312
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:392
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:392
 [inlined code] from boot.jl:263
 in anonymous at no file:0
 in eval at ./boot.jl:263
 [inlined code] from ./sysimg.jl:14
 in process_options at ./client.jl:254
 in _start at ./client.jl:377
while loading /home/augusto/.julia/v0.5/Atom/src/eval.jl, in expression starting on line 1
while loading /home/augusto/.julia/v0.5/Atom/src/Atom.jl, in expression starting on line 9
ERROR: Failed to precompile Atom to /home/augusto/.julia/lib/v0.5/Atom.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:471
 in require at ./loading.jl:339
 in eval at ./boot.jl:263

**Comment by pfitzseb** [comment]
I'm pretty sure most of Atom.jl and it's dependencies are horribly broken on 0.5 at the moment, so this is kinda expected.

**Comment by alexranaldi** [comment]
FWIW, I got this same error on 0.4.5.

**Comment by spencerlyon2** [comment]
@alexranaldi do you perhaps have JuliaParser checked out to track the master branch rather than the latest release?

See https://github.com/JunoLab/Atom.jl/issues/30#issuecomment-206384270 for more info

**Comment by alexranaldi** [comment]
@spencerlyon2 Running Pkg.free("JuliaParser") resolved the problem.  I was using a brand new install of 0.4.5, not sure what happened there.  Thanks for the assistance.

**Comment by spencerlyon2** [comment]
Great! No problem.

@augustot2  does this also work for you?

**Comment by augustot2** [comment]
Hi, i was using 0.4.2 and worked, but after this sugestion it worked too for 0.5

**Comment by spencerlyon2** [comment]
Excellent. So freeing JuliaParser allows you to use atom with julia 0.5?

**Comment by augustot2** [comment]
yes, thanks!
