### ISSUE TITLE
Integrate JuliaParser

### ISSUE THREAD

**Issue by Keno** [JunoLab/atom-julia-client#142]
The latest release of JuliaParser contains some new features for better parser diagnostics, which the IDE could take advantage of. 

In terms of how to integrate into Atom, I do know that nuclide does the same with Clang's diagnostics, so there may be inspiration to be taken.
http://nuclide.io/docs/editor/basics/#code-diagnostics

**Comment by MikeInnes** [comment]
The JuliaParser upgrades do look great. I need to update Juno's scoping for the JuliaParser changes anyway, and once that's done it'd be good to look at integrating the diagnostics as a standard part of evaluation.
