### ISSUE TITLE
Can't do "Evaluate All" in console

### ISSUE THREAD

**Issue by tdiao** [JunoLab/atom-julia-client#143]
Hello,

I am referring to the "Evaluate All" when one goes to Packages/Julia. Not sure if I simply missed or misconducted a step in installation or this is an issue.

Following the Juno Manual, I installed Julia, Atom, installed the various packages, and entered the location of the Julia Binary (hopefully it is right; at least when I start Atom, it's no longer telling me "Julia could not be found".) In Atom, I go to Packages/Julia/Open Console. A console window appears. I can use it as a terminal window, i.e. I type in codes and they are evaluated in the console. I can also evaluate in a file in Atom. E.g. if I write, say, 2 + 2, highlight it, and either do Cmd+Enter or go to Packages/Julia/Evaluate, a bubble of 4 appears beside the code in the file. 

However, nothing happens/appears in the console if I have codes in a file and were to do Packages/Julia/Evaluate All. This is what I had seen happen on my classmate's Windows machine and how I expect the Juno-IDE to work. Does this mean I failed to link Atom and Julia together? How may I go about diagnose and fix the issue?

Thank you very much.

**Comment by MikeInnes** [comment]
Evaluate-all will only work in the context of a file / script (not in the console – but maybe that's what you're already doing) and it will run the script silently unless you explicitly ask for output (same as running `julia file.jl`).

So for example, if your script is `2+2` you won't get any output, but if it's `@show 2+2` then you should see the result in the console. Is this what you're seeing, or is something unexpected going on?

**Comment by tdiao** [comment]
Thank you, Mike! I didn't know about the @show function. When I use it, things do show up in the console and that is great. It does not seem to evaluate like Juila normally does though. E.g. if I do
a = [1, 2, 3]
b = [1 2 3]
a .* b

instead of "3 x 3 Array {Int64, 2}: (the 3 by 3 matrix)", it would just show the 3 by 3 matrix. My classmate who's on Windows would have the former show up on console, without using @show. Is this specific to mac?

**Comment by pfitzseb** [comment]
That sounds a bit strange -- Juno (and Julia in general) don't show the output of any lines when evaluating whole files unless you explicitly request that (with `@show a.*b` or `println(a.*b)` or stuff like that). There's a feature request for an option for displaying results in the console rather than inline (#59), but that hasn't been implemented yet.

Also, please quote macros with ` (I did that in your comment), since otherwise you'll ping some user here on GitHub.

**Comment by tdiao** [comment]
I see. Thank you! And thanks for telling me about `!

**Comment by pfitzseb** [comment]
Did you figure this out, @tdiao?

**Comment by tdiao** [comment]
Not quite... @pfitzseb
