### ISSUE TITLE
Julia Client: Toggle Console

### ISSUE THREAD

**Issue by mariosgeo** [JunoLab/atom-julia-client#145]
Hi,

I have the same problem with the one described here.
https://github.com/JuliaLang/julia/issues/15687

What am I doing wrong?

Best

**Comment by MikeInnes** [comment]
This is a docs error, "open console" will do the job. Thanks for reporting, and let me know if there's anything else I can do.

**Comment by mariosgeo** [comment]
Thanks for the reply.

For the moment, I am still on my first steps so I will explore on my own before asking.

Best
