### ISSUE TITLE
Crash while using notification

### ISSUE THREAD

**Issue by tomaklutfu** [JunoLab/atom-julia-client#146]
I evaluate some julia code and notification message box pops up after evaluation finishes. After closing the message box, Atom freezes and then crashes. I am on Linux Ubuntu 16.04 (but it happened on Ubuntu 15.10 too) using Atom 1.6.2.

**Comment by MikeInnes** [comment]
Thanks for reporting – FWIW, you can disable notifications from the settings as a quick fix.

It would probably be worth reporting this to the Atom developers, since they're more likely to be able to fix it properly.

**Comment by tomaklutfu** [comment]
Thanks for quick response. I did disable it. Should I close this or leave it open to track upstream fix?

**Comment by MikeInnes** [comment]
Let's close – unless it's an issue for all ubuntu systems (which we could try to work around) there's not a whole lot we can do, unfortunately.
