### ISSUE TITLE
Can't checkout Atom/Codetools

### ISSUE THREAD

**Issue by nilshg** [JunoLab/atom-julia-client#15]
I'm probably being dense here, but:

````
julia> Pkg.checkout("http://github.com/JunoLab/Atom.jl")
ERROR: http://github.com/JunoLab/Atom.jl is not a git repo

julia> Pkg.checkout("Atom")
ERROR: Atom is dirty, bailing
````

How can I get the latest fixes?

**Comment by Varanas** [comment]
```
Pkg.rm("Atom")
Pkg.clone("http://github.com/JunoLab/Atom.jl")
```
should do the trick.

**Comment by one-more-minute** [comment]
The rule is – `Pkg.checkout` if you already have it, `Pkg.clone` if you don't (and `Pkg.clone("Atom")` will work).

@Varanas is exactly right about how to fix this – you have local changes to Atom.jl so Pkg refuses to overwrite them. You can just nuke the whole folder, or you can make a PR out of your changes and then checkout the master branch ;)

**Comment by nilshg** [comment]
Ah, my local changes were the culprit! Those changes were just those few lines about cutting up large vectors for the inline display, so they're in a PR already. Learned something today!

**Comment by one-more-minute** [comment]
Can you link me to that btw? I seem to have lost it...

**Comment by Varanas** [comment]
It's [that one](https://github.com/nilshg/Atom.jl/pull/1)... Just to the wrong repo, @nilshg.

Not really related, but could we have another gitter chat or reuse the old one for talking about Juno, @one-more-minute? I feel that's somewhat nicer for brainstorming and resolving small problems and stuff than github issues (and those are/should be specific to one repo, not necessarily about the whole project).

**Comment by one-more-minute** [comment]
Ah, nice sleuthing. Yeah, I'll go ahead and set up a gitter for JunoLab.
