### ISSUE TITLE
Uncaught TypeError: ink.Stepper is not a function

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-julia-client#150]
On master for ink and julia-client, error comes up at startup

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.4.3

### Stack Trace

Uncaught TypeError: ink.Stepper is not a function

```
At /Users/solver/Projects/julia-client/lib/runtime/debugger.coffee:39

TypeError: ink.Stepper is not a function
    at Object.module.exports.consumeInk (/Users/solver/Projects/julia-client/lib/runtime/debugger.coffee:39:20)
    at Object.module.exports.consumeInk (/Users/solver/Projects/julia-client/lib/runtime.coffee:20:15)
    at Object.module.exports.JuliaClient.consumeInk (/Users/solver/Projects/julia-client/lib/julia-client.coffee:25:7)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "julia-client": {
    "enableMenu": true,
    "enableToolBar": true,
    "juliaPath": "/Users/solver/Projects/julia/julia",
    "launchOnStartup": true
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.4.2
julia-client, v0.4.3
language-julia, v0.6.0
latex-completions, v0.3.1
minimap, v4.21.0
minimap-autohide, v0.10.1
number-slider, v1.0.1
project-manager, v2.8.0

# Dev
No dev packages
```

**Comment by pfitzseb** [comment]
That's because [this commit](https://github.com/JunoLab/atom-julia-client/commit/3831da552beca4fc85cc88421bb67db6039e8107) is on master when it (arguably) shouldn't be (cc @MikeInnes?). 
You could either get onto the [`stepper`](https://github.com/JunoLab/atom-ink/tree/stepper)-branch on ink or revert to 78ea68bd65a93586ee03a2cdd0ca426785822f5e.

**Comment by MikeInnes** [comment]
Yeah I messed this up a bit after my 14-hour shift last night :) @dlfivefifty as @pfitzseb says you can fix this by rolling back a commit for now, I'll get the stepper branch up and running to fix.

**Comment by MikeInnes** [comment]
Should be fixed now, thanks @dlfivefifty for reporting.
