### ISSUE TITLE
Error in show displays as "Julia Client - Internal Error"

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-julia-client#151]
Running the following in julia-client shows the error as a Julia Client - Internal Error, which makes it hard to debug:

``` julia
immutable Foo end

Base.show(io::IO,f::Foo)=error("My error")

Foo()
```

**Comment by pfitzseb** [comment]
The "hard to debug"-part is fixed for now, but anything in user code should not be an internal error.

**Comment by pfitzseb** [comment]
This should actually be fixed now.
