### ISSUE TITLE
Uncaught TypeError: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by kalihman515** [JunoLab/atom-julia-client#152]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.4.6

### Stack Trace

Uncaught TypeError: Cannot read property 'emit' of undefined

```
At /Users/YJ/.atom/packages/julia-client/lib/connection.coffee:17

TypeError: Cannot read property 'emit' of undefined
    at Object.error (/Users/YJ/.atom/packages/julia-client/lib/connection.coffee:17:27)
    at Object.module.exports.input (/Users/YJ/.atom/packages/julia-client/lib/connection/client.coffee:24:16)
    at /Users/YJ/.atom/packages/julia-client/lib/connection/tcp.coffee:34:14
    at Socket.<anonymous> (/Users/YJ/.atom/packages/julia-client/lib/connection/tcp.coffee:17:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

### Commands

```
 16x -0:24.4.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -0:21.3.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:19.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
 14x -0:16.9.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:14.3.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:12.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:11.4.0 core:move-down (atom-text-editor.editor.is-focused)
 43x -0:11.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:09.1.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:07.6.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:06.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
 55x -0:05.7.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:02.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:01.1.0 julia-client:run-file (atom-text-editor.editor.is-focused)
     -0:01.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:01.1.0 inline-results:clear-all (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "julia-client": {
    "enableMenu": true,
    "enableToolBar": true,
    "errorsToConsole": true,
    "juliaPath": "/Applications/Julia-0.4.5.app/Contents/Resources/julia/bin/julia"
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.4.3
julia-client, v0.4.6
language-julia, v0.6.0
latex-completions, v0.3.1

# Dev
No dev packages
```

Actually, I see this error pretty often in random manner. It just disappears when I reboot Atom. Any clue about this random error pop up? Below is the code that I ran to get this error.

type Person
    firstname::AbstractString
    lastname::AbstractString
    sex::Char
    age::Float64
    children::Array{AbstractString, 1}
end

p1 = Person("Alan", "Bates", 'M', 45.5, ["Jeff", "Stephan"])
#> Person("Alan", "Bates",'M',45.5,String["Jeff","Stephan"])

people = Person[] #> 0-element Array{Person,1}
push!(people, p1)
push!(people, Person("Julia", "Smith", 'F', 27, ["Viral"]))

show(people)

fullname(p::Person) = "$(p.firstname) $(p.lastname)"
fullname(p::Person) = AbstractString(p.firstname, " ", p.lastname)
print(fullname(p1)) #> Alan Bates

type Family
     name::AbstractString
     members::Array{AbstractString, 1}
     big::Bool
     Family(name::AbstractString) = new(name, AbstractString[], false)
     Family(name::AbstractString, members) = new(name, members, length(members) > 4)
end

fam = Family("Bates-Smith", ["Alan", "Julia", "Jeff", "Stephan", "Viral"])
#> Family("Bates-Smith",String["Alan","Julia","Jeff","Stephan","Viral"],true)

**Comment by pfitzseb** [comment]
You seem to have the `Errors To Console` option checked in the `julia-client`, and a recent rewrite of some related code broke that. Until the fix I just pushed is in a tagged version, you can just uncheck that option and everything should work as is.

**Comment by kalihman515** [comment]
Thanks for let me know!
