### ISSUE TITLE
Evaluation Menu Selection No Longer Evaluates Code

### ISSUE THREAD

**Issue by jcdenton87** [JunoLab/atom-julia-client#157]
Updated  Julia-client 0.4.7 today, immediately following update and running Pkg.update() in Julia console the Atom editor popup menu (right clicking in Atom after selecting text in script) no longer executes anything when clicking on Evaluate. Ctrl+Enter evaluates everything and the popup bubble shows the output so I know the functionality is still there... Guessing this is 100% user error but wanted to follow up to see if this happens to anyone else.

**Comment by pfitzseb** [comment]
Nope, this is (was) a real issue. The command got renamed in a recent refactor, but the menu wasn't changed accordingly.

Anyways, fixed by 8e761f81a04b60f357dc54f5e0afaaa65ec23945.
