### ISSUE TITLE
Uber-Juno Julia setup error

### ISSUE THREAD

**Issue by AnthonyJacob** [JunoLab/atom-julia-client#158]
This is what I get when installing uber-juno package.
http://www.jayrambhia.com/blog/android-wireless-connection-2/

> WARNING: Could not check MbedTLS version
> WARNING: Could not check MbedTLS version
> WARNING: Could not check MbedTLS version
> WARNING: Could not check MbedTLS version
> INFO: Building WinRPM
> WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
> WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
> INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 1/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 2/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 3/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 4/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 5/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> WARNING: received error 0 while downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 1/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 2/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 3/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 4/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 5/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> WARNING: received error 0 while downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> INFO: Building Nettle
> INFO: Updating WinRPM package list
> INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 1/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 2/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 3/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270088
> WARNING: Retry 4/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 5/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> WARNING: received error 0 while downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
> INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 1/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 2/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 3/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 4/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> WARNING: Unknown download failure, error code: 2148270105
> WARNING: Retry 5/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> WARNING: received error 0 while downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
> ===============================[ ERROR: Nettle ]================================
> 
> LoadError: None of the selected providers can install dependency nettle.
> Use BinDeps.debug(package_name) to see available providers
> 
> while loading C:\Users\Anthony\.julia\v0.4\Nettle\deps\build.jl, in expression starting on line 39
> 
> ================================================================================
> 
> ================================[ BUILD ERRORS ]================================
> 
> WARNING: Nettle had build errors.
> 
>  - packages with build errors remain installed in C:\Users\Anthony\.julia\v0.4
>  - build the package(s) and all dependencies with `Pkg.build("Nettle")`
>  - build a single package by running its `deps/build.jl` script
> 
> ================================================================================
> INFO: Package database updated
> INFO: METADATA is out-of-date — you may not have the latest version of Atom
> INFO: Use `Pkg.update()` to get the latest versions of your packages
> INFO: Precompiling module Atom...
> ERROR: LoadError: libnettle not properly installed. Please run Pkg.build("Nettle")
>  in error at error.jl:21
> while loading C:\Users\Anthony\.julia\v0.4\Nettle\src\Nettle.jl, in expression starting on line 10
> ERROR: LoadError: Failed to precompile Nettle to C:\Users\Anthony\.julia\lib\v0.4\Nettle.ji
>  in error at error.jl:21
> while loading C:\Users\Anthony\.julia\v0.4\WebSockets\src\WebSockets.jl, in expression starting on line 23
> ERROR: LoadError: LoadError: Failed to precompile WebSockets to C:\Users\Anthony\.julia\lib\v0.4\WebSockets.ji
>  in error at error.jl:21
> while loading C:\Users\Anthony\.julia\v0.4\Mux\src\websockets_integration.jl, in expression starting on line 1
> while loading C:\Users\Anthony\.julia\v0.4\Mux\src\Mux.jl, in expression starting on line 26
> ERROR: LoadError: LoadError: Failed to precompile Mux to C:\Users\Anthony\.julia\lib\v0.4\Mux.ji
>  in error at error.jl:21
> while loading C:\Users\Anthony\.julia\v0.4\Blink\src\content/content.jl, in expression starting on line 1
> while loading C:\Users\Anthony\.julia\v0.4\Blink\src\Blink.jl, in expression starting on line 8
> ERROR: LoadError: Failed to precompile Blink to C:\Users\Anthony\.julia\lib\v0.4\Blink.ji
>  in error at error.jl:21
> while loading C:\Users\Anthony\.julia\v0.4\Atom\src\Atom.jl, in expression starting on line 5
> ERROR: LoadError: Failed to precompile Atom to C:\Users\Anthony\.julia\lib\v0.4\Atom.ji
>  in error at error.jl:21
> while loading C:\Users\Anthony\.atom\packages\julia-client\script\boot.jl, in expression starting on line 35

I am on windows 8

**Comment by pfitzseb** [comment]
See https://github.com/JuliaLang/WinRPM.jl/issues/57 for help.

**Comment by AnthonyJacob** [comment]
I have solved it by restarting PC and running Pkg.update() in julia default console.

**Comment by pfitzseb** [comment]
Great, glad it's working for you!
