### ISSUE TITLE
pkgDir() may point to the wrong version's packages

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/atom-julia-client#159]
[This](https://github.com/JunoLab/atom-julia-client/blob/82994b793c99ec7417017a0fe6f54996d9cc22c5/lib/misc/paths.coffee#L15-L20) always leads to the newest version's packages.

Crossref: http://discuss.junolab.org/t/open-package-in-new-window-doesnt-show-all-packages/581

**Comment by MikeInnes** [comment]
I guess we could check with a client for this if there's one running.
