### ISSUE TITLE
Launching Julia fails silently unless you "Start a REPL"

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-julia-client#16]
If julia fails to launch when you try to execute code for the first time, or when you run the "Start Julia" command, it doesn't give any indication as to what's wrong.

If you run the "Start a REPL" command then you get useful debug output on the javascript console.

**Comment by one-more-minute** [comment]
What's the state of this as of 2016? I imagine the path-checking code covers most of the failure cases – this issue might even be from before we had the console :)

**Comment by pfitzseb** [comment]
I'm pretty sure this is not a valid concern anymore  -- there's been a lot of work done on getting spawning Julia more robust.
