### ISSUE TITLE
doesn't handle docstrings

### ISSUE THREAD

**Issue by lewisl** [JunoLab/atom-julia-client#160]
The convention adopted by Julia for documenting functions is to put text surrounded by triple quotes immediately prior the the function signature line.

Julia-client likes to find errors in the doc strings.

The error popup can never be dismissed.  You must either close the editor tab or go to settings and just disable the package.

**Comment by pfitzseb** [comment]
What exactly is the error (screenshot would be nice, especially to figure out the never-dismissable-parrt) and what were you trying to do?
![docs](https://cloud.githubusercontent.com/assets/6735977/14976587/399288a0-110d-11e6-9566-a1e6dcd57d97.PNG)

If you're trying to eval only one of the lines inside of the docstring or the triple quotes, then yes, you can't, and that's kinda annoying, but only produces the expected error of `Invalid syntax` or similar.
