### ISSUE TITLE
No tab completion in console?

### ISSUE THREAD

**Issue by tlnagy** [JunoLab/atom-julia-client#161]
It would be very useful to have tab completion in the console.

**Comment by pfitzseb** [comment]
This depends on some very new features in the core packages and Atom, but [here](https://github.com/JunoLab/atom-julia-client/commit/62567d6815c648b63a265595f8bcef5ada7bb506)'s a commit that should enable autocompletions in the console as well.

**Comment by ufechner7** [comment]
Any idea, how to install autocomplete-plus 2.30.0 in atom on Ubuntu?

I am using the newest Atom package 1.8.0, but autocomplete-plus is at 2.29.2 and the package manager says: No updates available.

**Comment by pfitzseb** [comment]
I think the easiest way to do that is to clone the git repo for autocomplete-plus and call `apm install` as well as `apm link` on it. Packages that are bundled with Atom are only updated on new releases.
That'll probably not be enough to get this even theoretically working, as you need a recent Atom build -- I don't think you'll get around building Atom master yourself as described [here](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md).

**Comment by ufechner7** [comment]
Hi,
I have now sufficiently new versions of Atom and autocomplete-plus and applied your patch to completions.coffee. Nevertheless autocompletion in the console is not working. Should it work with the TAB key? What might be the problem?

**Comment by pfitzseb** [comment]
That branch never really worked, but I'll look into that as soon as I find the time.

**Comment by ufechner7** [comment]
That would be very nice  :) .

**Comment by pfitzseb** [comment]
Okay, this works now on master :)

**Comment by ufechner7** [comment]
How can I update ink and julia-client to master?

**Comment by pfitzseb** [comment]
See [here](https://github.com/JunoLab/atom-julia-client/tree/master/docs#developer-install).

**Comment by ufechner7** [comment]
The second command failed:
```ufechner@uwe-desktop64:~$ apm install https://github.com/JunoLab/atom-julia-client
Cloning https://github.com/JunoLab/atom-julia-client.git ✓
Installing modules ✗
Cloning https://github.com/JunoLab/atom-julia-client.git ✓
Installing modules ✗
npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/ufechner/.atom/.apm/.apmrc" "--userconfig" "/home/ufechner/.atom/.apmrc" "install" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/autocomplete-plus
npm ERR! 404 
npm ERR! 404 'autocomplete-plus' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'julia-client'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/atom-git-package-clone-11675-6184-1ikl61m/npm-debug.log
ufechner@uwe-desktop64:~$ 
```
Any idea?

**Comment by pfitzseb** [comment]
Yeah, I screwed up there. Please try again.

**Comment by ufechner7** [comment]
Now I get an error when launching Atom:
ERROR: LoadError: UndefVarError: serve not defined
while loading /home/ufechner/.atom/packages/julia-client/script/boot.jl, in expression starting on line 35
Julia has stopped: 1

In the julia console I already did 
Pkg.update()

and using Atom doesn't fail.

Any idea?

**Comment by pfitzseb** [comment]
Ah, yeah... The master version of julia-client only works with `Atom.jl`-master, which in turn only works with julia 0.5.

**Comment by schlichtanders** [comment]
I am using julia 0.5.1 and encountered that the autocomplete in the console completes using ``TAB``, while the autocomplete in the editor itself completes using ``ENTER``.

This is really annoying unfortunately... does anyone know how to change this? What would be the right place to push this forward?
(I guess several newcomers to Julia like myself, and probably everyone would expect the two autocompletes to work the same.)

**Comment by pfitzseb** [comment]
I'm pretty sure that's not the case -- if you installed Juno via uber-juno we change the autocomplete default keybinding to `tab always, enter when explicitly selected` which means you can always use tab for autocomplete but once you select a different completion via cursor up/down, enter works too. If you want to change that setting, go to the `autocomplete-plus` package's settings and look for `Keymap For Confirming A Selection`.

**Comment by schlichtanders** [comment]
that is good to know. In fact I installed it via uber-juno, but ``tab always, enter when explicitly selected`` does work for the editor, but not for the console ...
I will try to find more details, thanks for your reaction!

**Comment by pfitzseb** [comment]
My bad, you right -- just tried again and I seem to not have tested correctly before answering. I'll have a look at fixing this, thanks for noticing.

**Comment by schlichtanders** [comment]
thanks for your effort
considering the ``tab always, enter when explicitly selected`` rule, my system seems to work differently for the EDITOR too:

In my editor ``enter`` works exactly like ``tab``, i.e. if nothing was explicitly selected, it still inserts the first suggested autocompletion.

(again might be configuration issue of course)

**Comment by pfitzseb** [comment]
That would be an issue with [autocomplete-plus](https://github.com/atom/autocomplete-plus), but `tab always, enter when explicitly selected` seems to work perfectly fine for me.

**Comment by schlichtanders** [comment]
good to know, thanks
