### ISSUE TITLE
Recent Build Issues (CentOS 7)

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/atom-julia-client#162]
I am having build issues with the most recent version. This is on CentOS 7. I have issues with Atom's building due to AbstractTrees?  I had a working installation for the last few months until updating packages today.

julia> Pkg.build("Atom")
INFO: Building HttpParser

signal (15): Terminated
unknown function (ip: 0x7fbbde3506f1)
unknown function (ip: 0x7fbbde359484)
unknown function (ip: 0x7fbbde35a1bb)
unknown function (ip: 0x7fbbde35e54d)
jl_matching_methods at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd3000b3c)
unknown function (ip: 0x7fbbd3000cf5)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd3000afb)
unknown function (ip: 0x7fbbd3000cf5)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd30009ab)
unknown function (ip: 0x7fbbd3000cf5)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd300063a)
unknown function (ip: 0x7fbbd300067a)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd2ffe86e)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd2ffc946)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd3023b5b)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd2ffb506)
unknown function (ip: 0x7fbbd2ff9f09)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd2ffb074)
unknown function (ip: 0x7fbbd2ff9f09)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd2ff9933)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd2ff357c)
unknown function (ip: 0x7fbbd2ff5c75)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd2fefbbb)
unknown function (ip: 0x7fbbd2ff020b)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd2fef5ff)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbde361944)
unknown function (ip: 0x7fbbde36240f)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
vcat at abstractarray.jl:874
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
find_in_path at loading.jl:18
jlcall_find_in_path_21209 at  (unknown line)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
recompile_stale at loading.jl:454
_require_from_serialized at loading.jl:83
jlcall__require_from_serialized_21206 at  (unknown line)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd32098fe)
unknown function (ip: 0x7fbbd3207a2e)
unknown function (ip: 0x7fbbd320870c)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbde3d59fd)
unknown function (ip: 0x7fbbde3d699b)
unknown function (ip: 0x7fbbde3d7459)
jl_load at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd3018b80)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd31c652e)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbde3c1903)
unknown function (ip: 0x7fbbde3c0d41)
unknown function (ip: 0x7fbbde3d6727)
unknown function (ip: 0x7fbbde3d67bd)
jl_toplevel_eval_in at /usr/bin/../lib64/julia/libjulia.so (unknown line)
evalfile at loading.jl:320
evalfile at loading.jl:320
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
anonymous at none:14
unknown function (ip: 0x7fbbd3211299)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
anonymous at none:13
open at iostream.jl:114
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbde3c1903)
unknown function (ip: 0x7fbbde3c0d41)
unknown function (ip: 0x7fbbde3d6727)
unknown function (ip: 0x7fbbde3d67bd)
jl_toplevel_eval_in at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x7fbbd31ef6fa)
unknown function (ip: 0x7fbbd31ede53)
unknown function (ip: 0x7fbbd31eeb89)
jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
unknown function (ip: 0x401c29)
unknown function (ip: 0x4017bf)
__libc_start_main at /usr/bin/../lib64/libc.so.6 (unknown line)
unknown function (ip: 0x401805)
unknown function (ip: (nil))
ERROR: AbstractTrees is not an installed package
 in build! at pkg/entry.jl:654
 in build! at pkg/entry.jl:653 (repeats 3 times)
 in build! at pkg/entry.jl:698
 in build at pkg/entry.jl:720
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in build at pkg.jl:64

julia> Pkg.add("AbstractTrees")
WARNING: julia is fixed at 0.4.3 conflicting with requirement for JuliaParser: [0.5.0-,\u221e)
ERROR: AbstractTrees can't be installed because it has no versions that support 0.4.3 of julia. You may need to update METADATA by running `Pkg.update()`
 in error at error.jl:22
 in edit at pkg/entry.jl:26
 in anonymous at task.jl:447
 [inlined code] from task.jl:422
 in add at pkg/entry.jl:46
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating Atom...
INFO: Updating CompilerTools...
INFO: Updating GtkIDE...
INFO: Updating ParallelAccelerator...
INFO: Updating GtkSourceWidget...
INFO: Updating JuliaParser...
INFO: Updating Blink...
INFO: Updating MacroTools...
INFO: Updating MATLAB...
INFO: Updating Publish...
INFO: Updating Requires...
INFO: Computing changes...
WARNING: julia is fixed at 0.4.3 conflicting with requirement for JuliaParser: [0.5.0-,\u221e)
ERROR: AbstractTrees can't be installed because it has no versions that support 0.4.3 of julia. You may need to update METADATA by running `Pkg.update()`
 in error at error.jl:22
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31

**Comment by pfitzseb** [comment]
You seem to be on JuliaParser master (which is 0.5 only) -- if so, try rolling back to the latest released version. 

If that's not the case of doesn't work, the output of `Pkg.status() ` would be interesting.

**Comment by ChrisRackauckas** [comment]
Freeing JuliaParser, MbedTLS, and Blink did the trick.
