### ISSUE TITLE
Julia doesn't boot with "optimisationLevel" variable 

### ISSUE THREAD

**Issue by JonnyCBB** [JunoLab/atom-julia-client#163]
I recently bumped into a problem where whenever I tried to boot Julia within Atom I would get the following error:
```
ERROR: unknown option `-2`
```
And Julia would never finish booting. I tracked the problem to [this line](https://github.com/JunoLab/atom-julia-client/blob/master/lib/connection/client.coffee#L162). Namely
```coffeescript
as.push "-O#{optimisationLevel}"
```
I assume this tries to start Julia with a line something like `julia -O2` (which reproduces the error). Removing `#{optimisationLevel}` solves the problem for me though!

After all that rambling I guess my question is, is this the correct syntax for starting Julia? It doesn't work for me and I haven't seen it before.

**Comment by pfitzseb** [comment]
It is, but only for julia 0.5 onwards. I think we have a 0.4 branch, so you could either use that our stay in the latest tagged version.

**Comment by JonnyCBB** [comment]
Ah ok. Thanks for clearing that up :)

**Comment by MikeInnes** [comment]
We should probably just avoid the flag if the level is 2 anyway.

**Comment by pfitzseb** [comment]
[Good idea.](https://github.com/JunoLab/atom-julia-client/commit/fe5ab4fa036972f950c8ead580e76e504eb8b241) ;)

**Comment by MikeInnes** [comment]
Execution is 90% :)
