### ISSUE TITLE
Progress Meter

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/atom-julia-client#165]
Juno/Atom should have a way of integrating with some progress meter. Currently the package [ProgressMeter.jl](https://github.com/timholy/ProgressMeter.jl) provides a way to have progress meters, but it does not work well with the current console (instead of updating its line, it prints a new line every time). There are a few ways to address this:
- Update the console to allow for progress meter (and other Julia code) to properly re-write onto itself.
- Utilize the progress bar on the bottom left of the screen to show not just when computations are being done, but the progress of the computation (via an interface like progressmeter.jl)
- Create another view in Atom for showing a progress bar (with some interface like progressmeter.jl)
- Let progress meters evolve on their own to be done as plots, and let the current plot handling take care of this.

**Comment by MikeInnes** [comment]
Have you tried `@progress for ...` recently? :)

**Comment by ChrisRackauckas** [comment]
Ooh nice! That works really well. Any way it could have a percentage and a time estimate next to it?

**Comment by pfitzseb** [comment]
Sure, that probably wouldn't be too hard to add. A hover-pop-up might be nicer though, especially since that'll be the way to add more information to the progress metre anyways.

**Comment by ChrisRackauckas** [comment]
Yeah, a hover popup would work well too.
