### ISSUE TITLE
defaultTerminal not working on Linux

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-julia-client#17]
in julia-client.coffee there's a `defaultTerminal` property that seems to appropriately set the terminal based on platform, but when I look at my settings on Linux the terminal setting is set to the windows value.

I set a breakpoint in `defaultTerminal` and reloaded and it looks like `process.platform` is `undefined` while the package is loading? :disappointed:

**Comment by MichaelHatherly** [comment]
Should be fixed by #37. Settings are showing linux terminal as `Default: x-terminal-emulator -e` now.

**Comment by Varanas** [comment]
@ssfrr Is this still an issue?

**Comment by ssfrr** [comment]
Nope, looks solved. thanks.
