### ISSUE TITLE
STDIN

### ISSUE THREAD

**Issue by AnthonyJacob** [JunoLab/atom-julia-client#171]
`readline(STDIN)`

If I type anything in console and hit enter - nothing happens at all. It seems that julia is still waiting for me to end the line but I cannot.

**Comment by MikeInnes** [comment]
You can send something to Julia's STDIN with the `Send to STDIN` command, which will send either a selection or the whole buffer. This is a relatively new feature, so let me know how it goes!

You should also be able to call `input()` which will show an input box in the console.
