### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by AnthonyJacob** [JunoLab/atom-julia-client#174]
I am little confused of all those pages about atom-julia, so I will post it here.
Are there any plans for julia syntax theme packed with the uber juno package?

I have made myself one, but its pretty much just copy paste of another theme with few colors added:
[screenshot](http://i.imgur.com/T69zZIs.png?1)

**Comment by pfitzseb** [comment]
Pretty much all syntax themes out there should just work (provided you have `atom-language-julia` installed, which `uber-juno` does automatically), so I'm not quite sure what you mean with "julia syntax theme".
