### ISSUE TITLE
MethodError `flatten` has no method matchng flatten(::Array{Any,1})

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-julia-client#175]
I keep getting an Internal error, with the error dump attached.  (Also: it's not possible to copy-and-paste from the console.)

![error](https://cloud.githubusercontent.com/assets/1229737/15379237/8026b8c4-1dae-11e6-9f96-66a3a66a54d0.png)

**Comment by pfitzseb** [comment]
Dup of #121, I think.
