### ISSUE TITLE
Cant find plot place and closed the julia tool bar in the left

### ISSUE THREAD

**Issue by Shoreshen** [JunoLab/atom-julia-client#176]
Hi Guys

im new to julia and I closed the tool bar in the left in Atom and am not able to reopen it.

in addition, I cannot find where to open and see the plot in Atom, I tried ctrl+shift+p and find "julia client: open plot pane", it doesnt work.

can anyone help me please.

**Comment by MikeInnes** [comment]
Hi, you can open the tool bar easily enough by executing `Tool Bar: Toggle` from the command palette.

Can you clarify "it doesn't work"? The plot pane will be blank before you've plotted anything. Right now it only works with Gadfly.
