### ISSUE TITLE
Julia console

### ISSUE THREAD

**Issue by AnthonyJacob** [JunoLab/atom-julia-client#177]
C^J+C^O opens terminal, but does not close it when it is open, so I have to do it manually every time.

If I try to run .exe file from there, no window shows up (it runs in background), if I manually kill it from task manager I get this message: 

`;main`
> failed process: Process(`main`, ProcessExited(1)) [1]
>  in run at process.jl:531

**Comment by AnthonyJacob** [comment]
One more thing
If something is printed out into console, it doesn't scroll down automatically - is it intended? 
If I type C^Enter into console it also doesn't scroll down automatically, which is definitely bug.

**Comment by MikeInnes** [comment]
You can easily enough close the console with <kbd>C-W</kbd> so <kbd>C-J C-O C-W</kbd> is a fast way to close it without using the mouse at all.

Perhaps try `start main`? I don't know much at all about the windows console, if we can change how commands are run to be more consistent then that would be fine.

Results/output should always scroll the console down. At the moment typing a newline doesn't do the same, but that's something we'll look at fixing.

**Comment by AnthonyJacob** [comment]
When typing into atom console:
`;cd`
> could not spawn `cd`: no such file or directory (ENOENT)
>  in _jl_spawn at process.jl:262
( It should print out current directory... It works in REPL)

**Comment by pfitzseb** [comment]
This isn't entirely trivial to fix I think. The REPL does something a lot more sophisticated than us [around here](https://github.com/JuliaLang/julia/blob/bdcd42672406416e55e61384b0b01f1febe90cee/base/REPL.jl#L724-L735), so we could use 
```
code = "Base.repl_cmd(`$code`, STDOUT)"
```
[here](https://github.com/JunoLab/Atom.jl/blob/c7ab071b30d90a21f89bf81252bfd1684d1483ff/src/eval.jl#L95) if we have no qualms about using internal methods ;)

Also, I'm not sure if that works alright on non-Windows systems.

**Comment by MikeInnes** [comment]
+1 to just reusing whatever the repl does, that's a good idea.

**Comment by pfitzseb** [comment]
Alrighty, merged.
