### ISSUE TITLE
supertype not defined

### ISSUE THREAD

**Issue by EricForgy** [JunoLab/atom-julia-client#178]
From Atom console with Julia process running:

~~~julia
> 1+1
UndefVarError: supertype not defined
 in distance at C:\Users\Eric Forgy\.julia\v0.4\Media\src\system.jl:8
 in nearest at C:\Users\Eric Forgy\.julia\v0.4\Media\src\system.jl:13
 in anonymous at C:\Users\Eric Forgy\.julia\v0.4\Media\src\system.jl:17
 in _mapreduce at reduce.jl:145
 in mapreduce at reduce.jl:159
 in nearest at C:\Users\Eric Forgy\.julia\v0.4\Media\src\system.jl:16
 in getdisplay at C:\Users\Eric Forgy\.julia\v0.4\Media\src\system.jl:114
 [inlined code] from C:\Users\Eric Forgy\.julia\v0.4\Atom\src\eval.jl:41
 in anonymous at C:\Users\Eric Forgy\.julia\v0.4\Atom\src\eval.jl:108
 in withpath at C:\Users\Eric Forgy\.julia\v0.4\Requires\src\require.jl:37
 in withpath at C:\Users\Eric Forgy\.julia\v0.4\Atom\src\eval.jl:53
 [inlined code] from C:\Users\Eric Forgy\.julia\v0.4\Atom\src\eval.jl:107
 in anonymous at task.jl:58
~~~

![image](https://cloud.githubusercontent.com/assets/8954730/15447368/dedb1d36-1f72-11e6-9f64-a876663fe81e.png)

I've tried Pkg.update() and unistalling/reinstalling ink and atom-julia-client. It's been like this for a while, so I resigned myself to just using Juno as an Editor, but now my packages are big enough they take more than 10 seconds to load, so the Juno workflow would be nice.

~~~julia
julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
~~~

**Comment by EricForgy** [comment]
Just tried `Pkg.checkout("Media")` and it didn't work...

**Comment by EricForgy** [comment]
Just tried `Pkg.checkout("Atom")` and it didn't work either...

**Comment by pfitzseb** [comment]
Not sure it'll help, but I'd try `Pkg.free()`ing Atom, Media and CodeTools unless you need to be on master on those packages (Media.jl master is 0.5 only, I think).

**Comment by EricForgy** [comment]
Oh thank you thank you :pray: That worked :)

**Comment by ChandramouliBanerjee** [comment]
I just installed Atom/Juno on Ubuntu 16.04 and I get the same error message. The fixes suggested here don't work.

**Comment by MikeInnes** [comment]
Try Pkg.update()

**Comment by ChandramouliBanerjee** [comment]
Pkg.Update() doesn't help and Pkg.status() shows I am on Media 0.2.1

**Comment by MikeInnes** [comment]
Did you restart Julia/Juno?

I can't reproduce this with the latest tags of all packages. If that's not the issue, make sure you don't have any master branches in `Pkg.status()`.

**Comment by ChandramouliBanerjee** [comment]
Hey Mike,

Thanks for the quick response. Restarted Julia and Juno and now it works
fine! The program said it had to recompile stale cache for media and atom.

**Comment by MikeInnes** [comment]
Great, glad you got it sorted – enjoy!
