### ISSUE TITLE
Multiple Window/Monitor Support

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/atom-julia-client#180]
For multiple monitor setups, it would be nice to be able to detach the console or other windows and put them on the other screen. Currently, opening up a new window in Atom makes it on a separate console session, causing issues if you try to evaluate code on one screen for a console on another.

**Comment by pfitzseb** [comment]
I've openend an issue over at the ink repo for this, among other improvements to the console.

**Comment by MikeInnes** [comment]
One way to solve this might be to change this part:

> Currently, opening up a new window in Atom makes it on a separate console session

Once we change to the julia-as-a-server model it could be as simple as listing available processes and hooking in another Atom frontend (which doesn't have to be used as a full fronted, it could just be a console on its own). Will need some refactoring on the julia side but it's very doable.

**Comment by pfitzseb** [comment]
> the atom window doesn't have to be used as a full frontend, it could just be a console on its own

Is there some official API to do this? Creating a minimal Atom instance that only loads certain packages could be the way to go here, especially since it'll hopefully be a bit faster then.

**Comment by MikeInnes** [comment]
Nothing official other than opening a new window and then hiding everything but the console. Although it does seem like automating that process – opening a new Atom window, connecting to a running Julia process, and sorting out the layout – could be a reasonable way forward.

**Comment by spencerlyon2** [comment]
What if we work toward embedding the console into a standalone blink window/app?

**Comment by MikeInnes** [comment]
It's a nice idea for sure, and could even have some other uses – serving Julia over the web, replacing the console on Windows. But unfortunately I think the only way to do it is to start from scratch, which is not great.

**Comment by vlepori** [comment]
Any progress on this/ is it still being considered? It's the one feature from RStudio I really miss in Juno.

**Comment by pfitzseb** [comment]
No. We're not actively developing new features for Juno anymore (the dev team has switched to VSCode).

That said, you can still get a nice multi monitor setup by using an external terminal and disabling the plot pane.

**Comment by vlepori** [comment]
Thanks for the reply, had missed that. And that works just fine, cheers!
