### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-julia-client#182]
This is on master of ink & julia-client:

```julia 
/Users/solver/Projects/julia-client/lib/misc/paths.coffee:54
Hide Stack Trace
TypeError: Cannot read property 'match' of undefined
    at ChildProcess.<anonymous> (/Users/solver/Projects/julia-client/lib/misc/paths.coffee:54:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by MikeInnes** [comment]
Can you try the latest commit?

cc @simondanisch

**Comment by SimonDanisch** [comment]
that works :)
But this still doesn't:
![image](https://cloud.githubusercontent.com/assets/1010467/15573698/0e78a304-2349-11e6-9a87-eaa5718c1daf.png)


![image](https://cloud.githubusercontent.com/assets/1010467/15573743/4499e7e0-2349-11e6-8f57-3d9e3d9f9bbe.png)

**Comment by MikeInnes** [comment]
Ah ok but that's a different kind of issue. The errors to console is for when you run a script via Ctrl-Shift-Enter and will eventually be the default for that. Inline eval always gives an inline result.

**Comment by pfitzseb** [comment]
Where does that setting come from anyways? It isn't on master.

I do think showing errors in the console should be the default when evaling a script, so I've made that change [here](https://github.com/JunoLab/Atom.jl/commit/7b4e013a163217a0f43b28e15ba3241d647dc393).

**Comment by MikeInnes** [comment]
To clarify, when I say default I just mean we'll stop supporting the error-notifications thing completely – but that won't happen until we have better support for notifying the user of new output.

**Comment by pfitzseb** [comment]
True, but we had errors piped to the console before, and that broke since then for non-internal errors.

**Comment by pfitzseb** [comment]
So it looks like this now: 
![errorstoconsole](https://cloud.githubusercontent.com/assets/6735977/15575915/8c2085d6-2355-11e6-807c-47c6e3f459a0.PNG)

I accidentally pushed that commit to the 0.5 branch. Should be master now, right?

**Comment by MikeInnes** [comment]
Ah, I see. Yeah we should delete v0.5.

**Comment by pfitzseb** [comment]
Done.

I do have an idea for some mini-notifications and stuff like that, hopefully I get to playing a bit with it soonish.

**Comment by MikeInnes** [comment]
Yeah that'd be cool. I was considering perhaps a toast-esque UI that collects on the bottom left-to-right? (I'm sure you have your own ideas anyway).

**Comment by dlfivefifty** [comment]
This is fixed for me!

**Comment by pfitzseb** [comment]
Great, closing then.
