### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by firevenus** [JunoLab/atom-julia-client#185]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.4.7
### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/siyan/.atom/packages/julia-client/lib/misc/history.coffee:22

TypeError: Cannot read property '0' of null
    at Interface.<anonymous> (/Users/siyan/.atom/packages/julia-client/lib/misc/history.coffee:22:12)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at ReadStream.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at onread (fs.js:1832:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "julia-client": {
    "enableMenu": true,
    "enableToolBar": true,
    "juliaPath": "/Applications/Julia-0.4.5.app/Contents/Resources/julia/bin/julia",
    "launchOnStartup": true
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-fortran, v0.4.0
autocomplete-python, v1.7.3
ink, v0.4.4
julia-client, v0.4.7
language-julia, v0.6.0
latex-completions, v0.3.1
tool-bar, v0.4.0
uber-juno, v0.1.1

# Dev
No dev packages
```

**Comment by MikeInnes** [comment]
Is this something that comes up as soon as you start the package?

If so your best bet is to try deleting `~/.atom/{julia-client,ink}` and re installing them. Let me know how that goes.

**Comment by firevenus** [comment]
I tried to re-install everything, enable the uber and clear it. Still not working. Despite the error, everything seems working fine. 
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.4
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.4.7


### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/siyan/.atom/packages/julia-client/lib/misc/history.coffee:22

TypeError: Cannot read property '0' of null
    at Interface.<anonymous> (/Users/siyan/.atom/packages/julia-client/lib/misc/history.coffee:22:12)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at ReadStream.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at onread (fs.js:1832:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "julia-client": {
    "enableMenu": true,
    "enableToolBar": true,
    "juliaPath": "/Applications/Julia-0.4.5.app/Contents/Resources/julia/bin/julia",
    "launchOnStartup": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.8.1
ink, v0.4.4
julia-client, v0.4.7
language-julia, v0.6.0
latex-completions, v0.3.1
tool-bar, v1.0.0
uber-juno, v0.1.1

# Dev
No dev packages
```

**Comment by firevenus** [comment]
The file:
fs = require 'fs'
readline = require 'readline'

paths = require './paths'

module.exports =
  path: paths.home '.julia_history'

  read: ->
    new Promise (resolve) =>
      lineReader = readline.createInterface
        input: fs.createReadStream @path

      entries = []
      readingMeta = false

      lineReader.on 'line', (line) =>
        if line.startsWith '#'
          if !readingMeta
            entries.push {loaded: true}
            readingMeta = true
          [_, key, val] = line.match /# (.+?): (.*)/
          entries[entries.length-1][key] = val
        else
          readingMeta = false
          entry = entries[entries.length-1]
          if entry.hasOwnProperty 'input'
            entry.input += '\n' + line.slice(1)
          else
            entry.input = line.slice(1)

      lineReader.on 'close', ->
        resolve entries

  write: (entries) ->
    return unless entries?
    out = fs.createWriteStream @path, flags: 'a'
    for entry in entries
      writeKey = (k, v) -> out.write "# #{k}: #{v}\n"
      if not entry.loaded
        if entry.time? then writeKey 'time', entry.time
        writeKey 'mode', entry.mode or 'julia'
        for line in entry.input.split '\n'
          out.write "\t#{line}\n"
    return

**Comment by pfitzseb** [comment]
Can you try deleting/renaming the `.julia_history` file in your homedir and restarting Atom afterwards?

**Comment by firevenus** [comment]
tried, not working....

**Comment by firevenus** [comment]
I have solved the problem by deleting .julia_history in history.coffee file. Thanks guys.
