### ISSUE TITLE
Pkg.add("Atom") is not working

### ISSUE THREAD

**Issue by warpuv** [JunoLab/atom-julia-client#191]
julia> Pkg.add("Atom")

INFO: Initializing package repository /home/yury/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection timed out

ERROR: failed process: Process(`git clone -q -b metadata-v2 git://github.com/JuliaLang/METADATA.jl METADATA`, ProcessExited(128)) [128]
 in anonymous at ./pkg/dir.jl:52

**Comment by pfitzseb** [comment]
Seems like a network problem.

**Comment by warpuv** [comment]
git:// protocol or ports blocked in my company. May it be better to use https?

**Comment by warpuv** [comment]
this solves my problem: `git config --global url."https://".insteadOf git://`
