### ISSUE TITLE
color break with regular expression

### ISSUE THREAD

**Issue by jingpengwu** [JunoLab/atom-julia-client#192]
the IDE is really awesome, I love it in a few minutes when start using it! 

one issue is the compatibility with regular expression. the color coding seems breaks after a regular expression:

![screenshot from 2016-07-05 17 52 14](https://cloud.githubusercontent.com/assets/7651573/16601239/68c5466e-42d9-11e6-9a2a-ab599f9c4d0d.png)

**Comment by pfitzseb** [comment]
Can't reproduce this:
![regexp](https://cloud.githubusercontent.com/assets/6735977/16611534/442ac584-4362-11e6-83a9-1dbc26621286.PNG)

Can you check which version of `language-julia` you're using?

**Comment by jingpengwu** [comment]
the version of `language-julia` is 0.6.0
I am using mac OS.

Just find that updating the IDE fixed this issue.
