### ISSUE TITLE
respect "\r"

### ISSUE THREAD

**Issue by gdkrmr** [JunoLab/atom-julia-client#193]
i like showing progress like this:

```julia
for i in 1:100
    print("\r", i, "/100")
end
```
which currently starts a new line for ever call to `print`, in a terminal all calls to `print` will go into the same line.

**Comment by MikeInnes** [comment]
It's not easy for us to provide console compatibility for ANSI codes etc, but we can provide better ways of doing things like progress meters. Have you tried the `@progress` macro?

**Comment by pfitzseb** [comment]
This particular console feature is pretty unlikely to be implemented I think, so closing this as wontfix.

If you really want this, please open either an issue or a PR over at https://github.com/JunoLab/atom-ink.
