### ISSUE TITLE
atom-ink not listed as dependency

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-julia-client#2]
I tried adding the git URL in the dependencies section of package.json, and running "apm install", but that just put it in the node-modules subdirectory. I ended up just installing it directly into my packages directory manually. Not sure what the right package.json incantation is to get it to install it as a top-level package.

**Comment by one-more-minute** [comment]
Doesn't look like this is possible at the moment – all the linter packages require a manual install of atom-linter as well.

It may be partly intentional, so that packages can be swapped out more easily.

I think the best option here is to just detect if the `ink` service is not provided and show a helpful error message.

**Comment by ssfrr** [comment]
Ah, I see. I guess the super-slick thing for Atom to do would be to prompt the user to select from all the available providers of the given service, but that's probably a bit fancy for where Atom is right now.

**Comment by davidanthoff** [comment]
Might [this](https://www.npmjs.com/package/atom-package-dependencies) help?

**Comment by one-more-minute** [comment]
Very possibly! What we have is working OK for now, I think, but I will look at this in more detail at some point. (Or anyone else is welcome to as well, of course)

**Comment by pfitzseb** [comment]
I'll close this, since we now have a one-click installer with uber-juno *and* a way to automatically install ink if it isn't there since [this commit](https://github.com/JunoLab/atom-julia-client/commit/af987897cbc4e2190edb2cb06a51cfa52893340f).
