### ISSUE TITLE
Very long one-line output overlays code

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-julia-client#20]
If you evaluate

"hellodvxcjlk;jlfds;gjsfl;kgjsfkljfgvkl;cxklxc;iofppfdiopgdffdipdidfopfddiopfifopdsifopiifopdsdsopfdiop"

in a small window it will overlay the code itself, making it uneditable

**Comment by nilshg** [comment]
This doesnt happen for me, can you post a screenshot? 

For me the inline result shows up to the right of the expression (which isn't great, as it'll just be cut off, but then again I don't think there's a great way to handle the display of 105-character strings inline...)

![capture](https://cloud.githubusercontent.com/assets/7264491/9703959/1d7c4414-548c-11e5-8e7a-ed7582b897f7.JPG)

**Comment by Varanas** [comment]
The key words are "small window" ;) I can see this too:
![longline](https://cloud.githubusercontent.com/assets/6735977/9704555/4a296832-54ac-11e5-9861-2500d62cc6ca.PNG)

**Comment by nilshg** [comment]
Hm, I tried making my Atom window small, but as I said the inline result will just be cut off at the end of the window, I can never get the inline result to start displaying to the left of the last character in the string.

Is this maybe because I'm "faking" my small window by just resizing and pulling to the edge of the screen, which of course still has a width of 1920 pixels?

**Comment by Varanas** [comment]
This can be kinda annyoing... ;)
![gtk](https://cloud.githubusercontent.com/assets/6735977/9774510/6c274b44-5749-11e5-96fd-0cba7db5344b.PNG)
I'll take a stab at fixing this tomorrow.

**Comment by one-more-minute** [comment]
Ideally I'd like to avoid this by avoiding long output in the first place, although it'll be a while before we can really get there.

**Comment by Varanas** [comment]
What do you mean by "avoiding ling output"? I thought about just defining a `max-width` with `overflow: hidden` which would be viewable when unfolding the result or something like that. Didn't get to doing that yet though ;)

**Comment by one-more-minute** [comment]
I just mean that for types like Window in your example, the default output should be some kind of tree as opposed to just a printed string. We could also catch long strings when rendering the `Text` object and split them up, for now.

**Comment by Varanas** [comment]
So I finally remembered to commit my "fix". 
This is probably something that can stay even after fixing the output on the Julia side of things (modulo some tweaks to the `max-width`, probably). I'm not quite sure how to hook into the display system for types and stuff like that, tbh.

**Comment by CarloLucibello** [comment]
@Varanas can you please commit your "fix" to master for the time being. This issue is very annoying

**Comment by Varanas** [comment]
Done. Update to [atom-ink](https://github.com/JunoLab/atom-ink) master and you should be good to go.

**Comment by CarloLucibello** [comment]
thanks!

Il giorno ven 25 set 2015 alle ore 11:17 Varanas <notifications@github.com>
ha scritto:

**Comment by dlfivefifty** [comment]
It’s now cutting off the output short, is this intentional?

**Comment by Varanas** [comment]
Yes. Though you should be able to scroll it on mouseover.

**Comment by dlfivefifty** [comment]
yes that works, great!

**Comment by pfitzseb** [comment]
This is *finally* fixed now! 🎉
