### ISSUE TITLE
console should use a fixed-width font for output

### ISSUE THREAD

**Issue by JeffBezanson** [JunoLab/atom-julia-client#202]
Many types use text output formats that assume fixed-width for lining things up nicely. This is not really usable as a julia console without this.

I tried changing fonts and it seemed to only change the font used for input.

**Comment by JeffBezanson** [comment]
Ah, this seems to be fixed in a more recent version.

**Comment by MikeInnes** [comment]
Yup I think we fixed this a while back and I'm seeing fixed-width for both STDOUT and results on master:

<img width="378" alt="screenshot 2016-08-10 22 18 56" src="https://cloud.githubusercontent.com/assets/2234614/17571541/841eee5c-5f48-11e6-8498-c06b82d9a970.png">

There's a flip side to this issue which is that packages should really use types (like `Table`) to express structure and have the frontend do the right thing to display it.
