### ISSUE TITLE
fix output limiting for 0.5

### ISSUE THREAD

**Issue by JeffBezanson** [JunoLab/atom-julia-client#203]
The console should display to an `IOContext` with `limit=true`.

**Comment by MikeInnes** [comment]
Are there docs on this? I haven't been involved in the display system changes so I don't know the context of this issue.

**Comment by MikeInnes** [comment]
Ok I think I see what you mean. This would be useful although again it's preferable to use structured display as much as possible.

**Comment by KristofferC** [comment]
Same with the workspace in my opinion.

**Comment by MikeInnes** [comment]
Fixed by https://github.com/JunoLab/Juno.jl/commit/5adfc09d9f129599aba27eb04e511034f2baba8f
