### ISSUE TITLE
startup time

### ISSUE THREAD

**Issue by JeffBezanson** [JunoLab/atom-julia-client#205]
Starting julia in julia-client takes a very long time for me. I expected this to be julia package load time, and part of it is, but according to `top` for most of the time julia is not active, and instead there are two `atom` processes using 20-50% cpu for about two minutes before the console prompt becomes active.

**Comment by MikeInnes** [comment]
If startup and completions are taking this long then something very strange is going on. What's your version of Atom?

**Comment by JeffBezanson** [comment]
1.9.7, and this is on ubuntu 14.04

**Comment by MikeInnes** [comment]
Linking this comment for posterity: https://github.com/JunoLab/atom-julia-client/issues/208#issuecomment-239447866

**Comment by pfitzseb** [comment]
This should be mostly fixed in the last version.
