### ISSUE TITLE
match limit exceeded

### ISSUE THREAD

**Issue by cihga39871** [JunoLab/atom-julia-client#207]
When a parameter is too long, it will throw an error. With every single typing it throws an error, and it is cumbersome.

Julia Client – Internal Error
PCRE.exec error: match limit exceeded
 in error at error.jl:21

**Comment by MikeInnes** [comment]
What's the output of `Pkg.status()`?

**Comment by cihga39871** [comment]
Thanks.

10 required packages:
 - ArgParse                      0.3.0
 - Atom                          0.4.2
 - DocOpt                        0.1.2
 - GLM                           0.5.3
 - Gadfly                        0.4.2
 - Plots                         0.7.3
 - ProgressMeter                 0.3.2
 - RCall                         0.5.0
 - RDatasets                     0.1.3
 - SortingAlgorithms             0.0.6
64 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.3.21
 - Blink                         0.3.4+             
master

 - Calculus                      0.1.15
 - CodeTools                     0.3.0
 - Codecs                        0.1.5
 - ColorTypes                    0.2.3
 - Colors                        0.6.5
 - Compat                        0.8.3
 - Compose                       0.4.2
 - Contour                       0.1.0
 - DataArrays                    0.3.3
 - DataFrames                    0.7.3
 - DataStructures                0.4.4
 - Dates                         0.4.4
 - Distances                     0.3.1
 - Distributions                 0.9.0
 - Docile                        0.5.23
 - DualNumbers                   0.2.2
 - FactCheck                     0.4.3
 - FixedPointNumbers             0.1.3
 - FixedSizeArrays               0.2.1
 - GZip                          0.2.19
 - Grid                          0.4.0
 - Hexagons                      0.0.4
 - Hiccup                        0.0.2
 - HttpCommon                    0.2.6
 - HttpParser                    0.1.1
 - HttpServer                    0.1.5
 - Iterators                     0.1.9
 - JSON                          0.6.0
 - JuliaParser                   0.6.4
 - KernelDensity                 0.1.2
 - LNR                           0.0.2
 - Lazy                          0.10.1
 - LibExpat                      0.1.2
 - Loess                         0.0.6
 - MacroTools                    0.3.0
 - MbedTLS                       0.2.2
 - Measures                      0.0.2
 - Media                         0.1.2
 - Mustache                      0.0.15
 - Mux                           0.2.0
 - NaNMath                       0.2.1
 - Nettle                        0.2.3
 - Optim                         0.5.0
 - PDMats                        0.4.2
 - PositiveFactorizations        0.0.1
 - RecipesBase                   0.0.5
 - Reexport                      0.0.3
 - Requires                      0.2.2
 - SHA                           0.1.2
 - Showoff                       0.0.7
 - StatsBase                     0.8.2
 - StatsFuns                     0.2.2
 - TextWrap                      0.1.5
 - URIParser                     0.1.4
 - WebSockets                    0.1.2
 - WinRPM                        0.1.15
 - WinReg                        0.1.0
 - WoodburyMatrices              0.1.5
 - Zlib                          0.1.12
 - jul6F08.tmp                   0.0.0-             non-repo (unregistered)
 - julB9D0.tmp                   0.0.0-             non-repo (unregistered)

**Comment by pfitzseb** [comment]
See #112 -- either try `Pkg.checkout("CodeTools")` or wait for a new tagged release.

**Comment by pfitzseb** [comment]
Right, my bad.

**Comment by MikeInnes** [comment]
No worries!

**Comment by pfitzseb** [comment]
I'll close this -- if you still have the issue, feel free to reopen this, @cihga39871.
