### ISSUE TITLE
julia processes remain after quitting atom

### ISSUE THREAD

**Issue by JeffBezanson** [JunoLab/atom-julia-client#208]
It looks like the julia processes started by julia-client are still running after I quit atom.

**Comment by MikeInnes** [comment]
If you're on the latest master of julia-client, we keep some julia processes around to reduce the boot time. It's probably fair to stop doing that if Atom is completely quit, however.

**Comment by MikeInnes** [comment]
Oh, and you can change the current behaviour by (1) running the "reset server" command to kill the current processes, and (2) change the boot mode option to "basic" in julia-client's settings.

**Comment by JeffBezanson** [comment]
Nice. How do I run the reset server command?

**Comment by MikeInnes** [comment]
Just bring up the command palette with `Ctrl-Shift-P`, type "reset server" and press enter. The command palette's also a pretty useful place to look for other functionality, just type "julia" in to see julia stuff.

**Comment by JeffBezanson** [comment]
Aha, this seems to solve my startup time problem as well. So I guess it had something to do with server mode.

**Comment by MikeInnes** [comment]
Now I've had some startup hangs in server mode as well, but unfortunately it seems intermittent. I think I can fix it but we'll just leave it disabled by default for now.

**Comment by pfitzseb** [comment]
Server mode is now disabled, so I'll close this.
