### ISSUE TITLE
"no such file or directory" error on starting

### ISSUE THREAD

**Issue by KristofferC** [JunoLab/atom-julia-client#209]
Updated things to latest master and getting:

```
ERROR: LoadError: getcwd: no such file or directory (ENOENT)
 in uv_error at ./libuv.jl:68 [inlined]
 in uv_error(::Symbol, ::Int32) at ./libuv.jl:67
 in pwd() at ./file.jl:34
 in find_in_path(::String) at ./loading.jl:114
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/kristoffer/.atom/packages/julia-client/script/boot.jl, in expression starting on line 3
```

It seems weird.. the `pwd()` command is throwing the error.

**Comment by MikeInnes** [comment]
Could you try changing boot mode to basic in julia-client's settings and see if it helps?

It may be that we just need to set the working directory explicitly when booting, but it's odd that I'm not getting this on OS X

**Comment by KristofferC** [comment]
I reinstalled a bunch of stuff and now it doesn't seem to error there anymore..

Getting 

```jl
ERROR: LoadError: function connect does not accept keyword arguments
while loading /home/kristoffer/.atom/packages/julia-client/script/boot.jl, in expression starting on line 35
Julia has stopped: 1, null
```

but that just seems to be a mismatch between versions.

**Comment by MikeInnes** [comment]
Yup, that's just Atom.jl being out of date. The latest tag should do the job on 0.4, or master on 0.5.

**Comment by KristofferC** [comment]
I am quite confused. Packages are updated:
```
➜  Atom git:(master) pwd    
/home/kristoffer/.julia/v0.5/Atom
➜  Atom git:(master) git pull
Already up-to-date.

➜  CodeTools git:(master) git pull
Already up-to-date.
```

But still:

![image](https://cloud.githubusercontent.com/assets/1282691/17622823/ed74c994-609c-11e6-96bb-826cae0b83a4.png)

So there is no connect method in Atom that accepts a keyword argument... where is this method even defined?

**Comment by MikeInnes** [comment]
Ok, you need master of julia-client and ink then – see the apm commands [here](https://github.com/JunoLab/atom-julia-client/tree/master/docs).

**Comment by KristofferC** [comment]
Yeah, getting master of `julia-client` fixed it. I had the master version but then I got confused because when you have the master version it reports that as 0.4.3...

![image](https://cloud.githubusercontent.com/assets/1282691/17623213/30d667f4-609f-11e6-9712-61217bd4bb74.png)

while the latest tagged release is 0.4.7 so it seems more up to date to get that one. Oh well..
