### ISSUE TITLE
On julia v0.5: Internal Error - EOF not defined

### ISSUE THREAD

**Issue by kescobo** [JunoLab/atom-julia-client#210]
I was using the precompiled Mac binaries for julia v0.4.5. with no problem. I cloned and built julia v0.5.0-rc1+1, did `Pkg.add("Atom")`. And then opened Atom. I switched the julia path in julia-client settings, and then restarted Atom. It went through the "the first time you run it will take a couple of minutes" thing, and the terminal works (though it spits out a lot of warnings about `AbstractString` being deprecated). 

But any time I type, or even click into a .jl file, errors start popping up in the right side of the window:

```
UndefVarError: EOF not defined
 in scopes(::LNR.LineNumberingReader{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::LNR.Cursor) at /Users/KBLaptop/.julia/v0.5/CodeTools/src/parse/scope.jl:153
 in codemodule(::String, ::Int64) at /Users/KBLaptop/.julia/v0.5/CodeTools/src/parse/parse.jl:6
 in filemodule_(::String) at /Users/KBLaptop/.julia/v0.5/CodeTools/src/module.jl:93
 in macro expansion at ./dict.jl:689 [inlined]
 in (::CodeTools.##1#2{CodeTools.#filemodule_,Dict{Any,Any}})(::String, ::Vararg{String,N}) at /Users/KBLaptop/.julia/v0.5/CodeTools/src/utils.jl:3
 in modulenames(::Dict{String,Any}, ::LNR.Cursor) at /Users/KBLaptop/.julia/v0.5/Atom/src/eval.jl:10
 in (::Atom.##104#105)(::Dict{String,Any}) at /Users/KBLaptop/.julia/v0.5/Atom/src/eval.jl:24
 in handlemsg(::Dict{String,Any}, ::Dict{String,Any}, ::Vararg{Dict{String,Any},N}) at /Users/KBLaptop/.julia/v0.5/Atom/src/comm.jl:82
 in (::Atom.##5#8)() at ./event.jl:46
```

MacOS v10.11.6
Atom v1.9.8
julia-client v0.4.7

I tried uninstalling and reinstalling uber-juno, and the `Atom.jl` package and all dependencies in Julia, still get the same problem. 

I then installed the pre-compiled binaries for mac for v0.4.6, and switched the julia path to `/Applications/Julia-0.4.6.app/Contents/Resources/julia/bin/julia`. This works fine, no errors.

Ditto if I `git checkout v0.4.6`, build from there and use `/usr/bin/julia` as the path.

**Comment by pfitzseb** [comment]
Try `Pkg.checkout("CodeTools")` (and possibly a few others), until the new versions are tagged.

**Comment by kescobo** [comment]
Tried checking out CodeTools, Ink, Atom - I'm getting slightly different errors, but still getting lots of them on typing and on evaluation... Should I just keep going through the list?

**Comment by MikeInnes** [comment]
We just did a bunch of releases so you should be able to use the latest tags. Take a look at `Pkg.status()` and `Pkg.free(X)` the stuff you checked out, and see how that goes.

**Comment by kescobo** [comment]
This problem is solved, now I'm having others... Will investigate further and report back.
