### ISSUE TITLE
0.5 Inline output very slow

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-julia-client#213]
The spinning wheel takes about an extra 20 seconds, even for something as simple as a 5x5 Matrix.  This appears to only happen after an output whose show is slow.

**Comment by pfitzseb** [comment]
Does this only happen after startup? Because if not, I definitely can't reproduce this.

**Comment by dlfivefifty** [comment]
Hmm, I'll see if I can come up with a reproducing example.

**Comment by dlfivefifty** [comment]
This doesn't seem to exist anymore.
