### ISSUE TITLE
error caused by space in directory name?

### ISSUE THREAD

**Issue by xqrongm** [JunoLab/atom-julia-client#215]
OS: Windows 10
Atom version 1.9.9
Atom package "julia-client" 0.5.0
Julia version 0.4.6
Julia package "Atom" 0.4.5

I just updated to "julia-client" 0.5.0 and opened a Julia client in Atom, typed in `1+1` and got this error below. The actual directory is "C:\Users\Xiaoqing Rong". Is the error caused by the space in the path? I've been using "julia-client" for a while and everything was fine before the update to 0.5.0.

ERROR: could not open file C:\Users\Xiaoqing 
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 in process_options at client.jl:280
 in _start at client.jl:378

**Comment by BoundaryValueProblems** [comment]
I have exactly the same problem after upgrading to Atom version 1.9.9 and julia-client 0.5.0. Previous version was working without such an error.

**Comment by jklizarraga** [comment]
Same problem here.

**Comment by pfitzseb** [comment]
Are you trying to open a file that is in a dir with a space in it? I was trying to reproduce this earlier, but couldn't...

**Comment by xqrongm** [comment]
No, the error happened when I opened a Julia console in Atom and typed in `1+1`. It looked like julia-client couldn't start.

**Comment by pfitzseb** [comment]
Okay, found it. Should be fixed soonish ;)

**Comment by pfitzseb** [comment]
Done: https://github.com/JunoLab/atom-julia-client/commit/c862f67879a67a9e020df2256cb555180bef602e
Should be fixed in the next release.
