### ISSUE TITLE
Small changes required for an upcoming Atom release

### ISSUE THREAD

**Issue by maxbrunsfeld** [JunoLab/atom-julia-client#217]
Hi! Atom will soon be upgrading to a new version of Electron, which will cause some APIs to change.

You'll need to change [this usage](https://github.com/JunoLab/atom-julia-client/blob/00dabcda3b739620b20e3ded3bb4b2d1456d91e9/lib/runtime/frontend.coffee#L23) of `BrowserWindow.prototype.loadUrl` to `w.webContents.loadURL`.

There may be other similar small changes required. See [this post](http://electron.atom.io/blog/2015/11/17/electron-api-changes) on the electron blog for more information. And let me know if you need any additional help. Thanks!

**Comment by pfitzseb** [comment]
At least the electron docs seem to say that this isn't strictly necessary: https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winloadurlurl-options

`julia-client` also works with Atom master, so I don't think we need to change this?

**Comment by maxbrunsfeld** [comment]
You're right, apparently `loadURL` still exists on `BrowserWindow.prototype`. But `loadUrl` (lowercase 'r' and 'l') does not, and that's what you're calling, so I think you just need to change `Url` -> `URL`.

**Comment by pfitzseb** [comment]
Oh, right, I'm blind.
Thanks for pointing that out! :)
