### ISSUE TITLE
Integration with IJulia kernel

### ISSUE THREAD

**Issue by habemus-papadum** [JunoLab/atom-julia-client#220]
Hi -- back in the Juno/LT days, I used to have Juno/LT connect to a julia kernel that had been launched by IJulia (the flow involved running a command in Juno/LT that copied a small snippet  to the system clipboard, and then manually evaluating this text in a IJulia cell (or a manually launched repl session, or whatever suited your particular needs -- I happened to like IJulia))  This approach was often very productive (I can try to describe various pros and cons at some point if there is interest).  Looking at the v0.5 CHANGELOG, (and changes in Atom.jl) it looks like connecting to a julia process not started by Juno/Atom might be again possible -- I see references to "server" mode, etc.   Is this workflow possible again in Juno/Atom? (perhaps it was always possible?)  If not, any thoughts on how one might re-implement this behaviour?

thanks!

**Comment by MikeInnes** [comment]
Yes, this is a nice feature, but one that got brushed aside a little with the recent changes. It shouldn't be too difficult to reimplement this though, so given the interest I may take a look at it soon.

**Comment by lilinjn** [comment]
Ok -- thanks!  If there are beginner level steps that can be delegated, let me know.  Cheers

**Comment by lilinjn** [comment]
Hi -- Using the new "Julia Client: Connect to Local Port" now makes the desired workflow possible.  Thanks!  

(Though the UI is not so easy to follow as of now -- for the time being here are my notes:
1) in the IJulia session/console repl that you want Juno to connect to:

````
import Atom
@async Atom.serve(8712) #use whatever port you like
````

2) (optional) use ssh to forward a local port to remote box if necessary; remember this port for the next step

3) In Juno -- "Julia Client: Connect to Local Port", make sure Julia Console is open -- type in the proper port number in the proper location next to the icon that looks like a clipboard.  

Upon success you should see a notification saying the connection to the local port was successful.

**Comment by MikeInnes** [comment]
I'm implementing a much nicer version of this (like the old version) in https://github.com/JunoLab/atom-julia-client/pull/259#pullrequestreview-3351974.

**Comment by lilinjn** [comment]
awesome!
