### ISSUE TITLE
scroll bar causes console screen to flash back and forth

### ISSUE THREAD

**Issue by xqrongm** [JunoLab/atom-julia-client#222]
Windows 10
Atom v1.10.0
julia-client v0.5.1

I'm not sure if the issue is with Atom or julia-client.

There is this cell in my Julia console that has a scroll bar
![image](https://cloud.githubusercontent.com/assets/12205732/18142002/ab12370c-6f89-11e6-8d02-13bff797b4cf.png)

When I click on it, it just starts to flash back and forth between with scroll bar and without scroll bar. Here are the screenshots for its two "flashing stages"

**stage 1**
![image](https://cloud.githubusercontent.com/assets/12205732/18142069/edad144c-6f89-11e6-9323-5acf68a821eb.png)

**stage 2**
![image](https://cloud.githubusercontent.com/assets/12205732/18142071/f05dfd82-6f89-11e6-8130-be511a8bd5f9.png)
.
.

When I try to type something in the last cell, the console screen starts flashing even faster between the two following stages. I can hardly see what I'm typing.

**stage 1**
![image](https://cloud.githubusercontent.com/assets/12205732/18142115/22aabee2-6f8a-11e6-9bdc-1ed44f0badd5.png)

**stage 2**
![image](https://cloud.githubusercontent.com/assets/12205732/18142118/26575aaa-6f8a-11e6-8344-cbdf496cea3b.png)

**Comment by pfitzseb** [comment]
I think the first issue might be fixed now on current master. The autocomplete one not so much, I'm afraid, but then again that would require patching autocomplete-plus (also [see here](https://github.com/atom/autocomplete-plus/issues/680) -- this probably is what you're seeing?).

**Comment by pfitzseb** [comment]
In theory everything in here should be fixed by now -- please reopen the issue if not!
