### ISSUE TITLE
Feature request: Add open workspace to julia menu

### ISSUE THREAD

**Issue by Pbellive** [JunoLab/atom-julia-client#227]
Hi,
      I learned today (via [this thread](https://groups.google.com/forum/#!topic/julia-users/0WPbotMp0G8)) that I can open the juno workspace variable display by typing `julia open workspace` from the atom command line. Is the workspace feature still at an experimental stage or is it ready for wide use?

If it is ready to go, It would be convenient if one could also open the workspace from the julia menu in atom. In addition to convenience I would guess that many users assume the workspace functionality is not yet included in Juno since it's not available from the menu or from a button that is visible by default. I was certainly such a user until a kind julia-users contributor helped me out today. 

Thanks, Patrick

**Comment by pfitzseb** [comment]
Fair enough: https://github.com/JunoLab/atom-julia-client/commit/178b5124a8bf47df0a4b328a4d4d5759fac2445c
No reason to keep those hidden, even if they are still experimental features, I think.
