### ISSUE TITLE
Julia has stopped: 1

### ISSUE THREAD

**Issue by Edvac** [JunoLab/atom-julia-client#228]
Julia has stopped: 1
ERROR: unknown option: --precompiled=yes
 in process_options at client.jl:306
 in _start at client.jl:389

**Comment by pfitzseb** [comment]
[Update julia to at least the latest 0.4 version.](http://discuss.junolab.org/t/solved-julia-not-compiling-under-juno/874)

**Comment by zlqs1985** [comment]
hi, I have the same problem, and even I have just updated the julia-lang to 0.5.0 and all packages, the error remains

**Comment by pfitzseb** [comment]
Feel free to reopen this if you're still experiencing that error.
