### ISSUE TITLE
Intrnal Error: type Text has no field text

### ISSUE THREAD

**Issue by shashi** [JunoLab/atom-julia-client#232]
running

``` julia
using Vega
scatterplot(x=rand(10),y=rand(10))
```

results in

![image](https://cloud.githubusercontent.com/assets/25916/18700254/d8b8f1bc-7ff3-11e6-81d0-9e59b0404fa8.png)

**Comment by pfitzseb** [comment]
Are you on Vega.jl master or something? I can't reproduce this.

**Comment by pfitzseb** [comment]
Please reopen if this still happens.
