### ISSUE TITLE
setting deprecation warning on may crash Atom

### ISSUE THREAD

**Issue by TsurHerman** [JunoLab/atom-julia-client#233]
When deprecation warning is on , the console window may be swamped with depwarn messages
which causes Atom to hang.

On windows
Steps to reproduce:
1) set deprecation warning in julia client
2) set Boot mode to server
3) re-launch Atom
4) in the console window type something like a=5 to get it warmed up
5) type Base. and hit Tab to get a completion .... crash!

**Comment by pfitzseb** [comment]
One cause of this is fixed by https://github.com/JunoLab/CodeTools.jl/commit/04cd5aded8c3b7a2f45e4559b2e889428375f071, the other by at least mitigated by https://github.com/JunoLab/atom-julia-client/commit/945f9391d1fda2d81f5defb5cda0cc5fe47458fb.
