### ISSUE TITLE
I'm not use Console

### ISSUE THREAD

**Issue by unalman** [JunoLab/atom-julia-client#235]
Hello my use Atom in Julia language but not use. Because Atom Console not working. I'm basic write code  example(2+2) but I get this error:

WARNING: Method definition 
require(Symbol) in module Base at loading.jl:345 overwritten in module Juno at C:\Users\unalman.julia\v0.5\Requires\src\require.jl:12.
INFO: Precompiling module Atom.
WARNING: Module Juno with uuid 4571906551681 is missing from the cache.
This may mean module Juno does not support precompilation but is imported by a module that does.
ERROR: LoadError: Declaring **precompile**(false) is not allowed in files that are being precompiled.
 in require(::Symbol) at .\loading.jl:385
 in include_from_node1(::String) at .\loading.jl:488
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\Users\unalman.julia\v0.5\Atom\src\Atom.jl, in expression starting on line 5
ERROR: LoadError: Failed to precompile Atom to C:\Users\unalman.julia\lib\v0.5\Atom.ji.
 in compilecache(::String) at .\loading.jl:593
 in require(::Symbol) at .\loading.jl:422
 in require(::Symbol) at C:\Users\unalman.julia\v0.5\Requires\src\require.jl:12
 in include_from_node1(::String) at .\loading.jl:488
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\unalman.atom\packages\julia-client\script\boot.jl, in expression starting on line 36

**Comment by pfitzseb** [comment]
Try calling `using Atom` in the console and then restart Atom.

Ref: https://github.com/JunoLab/uber-juno/issues/15

**Comment by unalman** [comment]
I'm try Atom in console write using Atom .But I'm get new error:

WARNING: 
Base.String is deprecated, use AbstractString instead.
ERROR: LoadError: LoadError: LoadError: LoadError: UndefVarError: MethodList not defined
while loading C:\Users\unalman\.julia\v0.4\Juno\src\base\methods.jl, in expression starting on line 5
while loading C:\Users\unalman\.julia\v0.4\Juno\src\base/base.jl, in expression starting on line 123
while loading C:\Users\unalman\.julia\v0.4\Juno\src\Juno.jl, in expression starting on line 28
while loading C:\Users\unalman\.atom\packages\julia-client\script\boot.jl, in expression starting on line 36

**Comment by pfitzseb** [comment]
Is this still a problem on the latest version?
