### ISSUE TITLE
Dataframe output format

### ISSUE THREAD

**Issue by huyiqun** [JunoLab/atom-julia-client#237]
I am playing around with data analysis functionalities in julia. I am not sure if I am missing something that can be changed in settings here or the output format in the atom-julia-client is not designed for showing data frames. So basically, I want to have a quick look of what the data look like, but the inline output just says `DataFrames.DataFrame` (same as in console). Even if I click on it, it gives information about each column and indices, etc., it does not display the data table. 

![screen shot 2016-09-21 at 4 46 12 pm](https://cloud.githubusercontent.com/assets/10877536/18728405/10897ec8-801b-11e6-80ea-707fb19bf4d2.png)

![screen shot 2016-09-21 at 5 14 35 pm](https://cloud.githubusercontent.com/assets/10877536/18729221/ec0680d8-801e-11e6-8cc0-24dabb645cef.png)

I have to explicitly type `print(df)`, then the inline output will just be a check mark and the console will print the data structure. 

![screen shot 2016-09-21 at 4 48 51 pm](https://cloud.githubusercontent.com/assets/10877536/18728487/502e5ac6-801b-11e6-90bf-039d24f0de3f.png)

What are my options to easily view the data in this case?

Also, this happens when I run the line `print(df)` using `shift-command`, 
![screen shot 2016-09-21 at 4 53 18 pm](https://cloud.githubusercontent.com/assets/10877536/18728599/ee0bc774-801b-11e6-847f-040d50af910e.png)
but if I type `print(df)` in the console, the output is just fine, as shown in the previous picture.

**Comment by pfitzseb** [comment]
There's just no support for prettyprinting `DataFrame`s yet in Juno. We'll get there eventually though.

**Comment by huyiqun** [comment]
Thanks, @pfitzseb ! Also wondering if it is possible to configure so that the output only shows in the console not inline?

**Comment by pfitzseb** [comment]
No, not yet: https://github.com/JunoLab/atom-julia-client/issues/59

**Comment by davidzentlermunro** [comment]
Any progress on this?

**Comment by sylvaticus** [comment]
As of current Juno version in 2018/7/31 this functionality seems it has been implemented:
![juno_missing_workspace_bug](https://user-images.githubusercontent.com/2077159/43459129-d2953f30-94cc-11e8-9938-cdff84607aee.png)

The only problem is the display of `missing` type in the workspace.

**Comment by pfitzseb** [comment]
That's fixed with https://github.com/JunoLab/atom-julia-client/commit/6b61c8dd72a5996e6baa7d44f0231e1ee7b7d14b.
