### ISSUE TITLE
Move cursor to beginning of next block that can be executed after Ctrl-Enter

### ISSUE THREAD

**Issue by davidanthoff** [JunoLab/atom-julia-client#24]
This is essentially the RStudio behavior, super convenient, because one can run a whole file by just repeatedly hitting Ctrl-Enter.

**Comment by one-more-minute** [comment]
It's sometimes nice to have the cursor stay put too, though, if you're working on an expression.

In Juno/LT we had "Eval + Move" bound to Shift-Enter – the same as IPython, effectively – so I think it'd be nice to have that in Atom as well.

**Comment by davidanthoff** [comment]
Yes, having both would be ideal, and matching IPython would be great.

**Comment by one-more-minute** [comment]
Just implemented this!
