### ISSUE TITLE
unable to run julia programs

### ISSUE THREAD

**Issue by yoddha24** [JunoLab/atom-julia-client#242]
On clicking "start julia", i am getting the following message:

Julia could not be started.
We tried to launch Julia from:
julia
This path can be changed in the settings.
Details:
  /bin/sh: julia: command not found

**Comment by MikeInnes** [comment]
Does the `julia` command work when run from a terminal?

You may be able to fix this by going to the Julia->Settings menu and entering the path to your local Julia binary.

**Comment by yoddha24** [comment]
Thankyou for the comment. I now prefer to work with command line only instead of atom IDE. regards
