### ISSUE TITLE
Juno does not respect semicolon as a mean to suppress output

### ISSUE THREAD

**Issue by TsurHerman** [JunoLab/atom-julia-client#244]
in the julia builtin REPL
A = rand(1024,1024);

yields no output

in Atom in the console or when directly evaluating I would expect the same behavior
A = rand(1024,1024);(cntrl-enter) should yield 'A' or just a symbol to represent that it was evaluated
instead I get a print that takes a long time to render(at-least under windows)

**Comment by pfitzseb** [comment]
I think our plan for this is to just make rendering of results fast (and sized such that they don't take more than the height of the console by default) -- if that works as planned, suppressing output with `;` would be unnecessary.

**Comment by TsurHerman** [comment]
I think you are right , but just in case can you add this feature?
There are cases when I know I don't want to see the output, and the semicolon is deliberate

**Comment by MikeInnes** [comment]
Although we don't have plans for this feature we wouldn't say no to a good PR :)

Happy to give pointers if you're interested in implementing this.

**Comment by TsurHerman** [comment]
Hmm sure , though it is not at all trivial to hack on your code in a language that I am un-familliar
with (coffee-script).

I'll have a look when I have some time. is there anywhere a high level documentation of your project?

**Comment by MikeInnes** [comment]
It may not be as tricky as you think since eval is fairly self contained in the Julia code ([here](https://github.com/JunoLab/Atom.jl/blob/251d14379746a5092524889c9c3fa7786e5ca52c/src/eval.jl#L108)).

We just need a function that takes a code block and returns whether it should be suppressed – if so render `nothing` rather than the result of evaluation.

**Comment by KristofferC** [comment]
Also see https://github.com/JuliaLang/julia/blob/0287a9971ea4d740d2bc5e205423e2ae5bdf4124/base/REPL.jl#L962, https://github.com/JuliaLang/julia/blob/0287a9971ea4d740d2bc5e205423e2ae5bdf4124/base/REPL.jl#L240 for how the REPL does it.

**Comment by pfitzseb** [comment]
Implemented in https://github.com/JunoLab/Atom.jl/pull/65. Thanks for the contribution, @TsurHerman!
