### ISSUE TITLE
Error message cropped

### ISSUE THREAD

**Issue by janekdb** [JunoLab/atom-julia-client#249]
It would be useful to be able to see the full error message,

![julia-ide-cropped-error](https://cloud.githubusercontent.com/assets/1123855/18988156/397deede-86fd-11e6-9208-2176db6694f7.png)

**Comment by janekdb** [comment]
I have now found the hscroll control which is useful. It would be an enhancement to be able to use more of my screen.
![julia-ide-hscroll](https://cloud.githubusercontent.com/assets/1123855/18988282/dc0db5d0-86fd-11e6-9930-3cbc39e0f1ce.png)

This shows there is plenty of horizontal space to occupy and reduce the amount of scrolling required to see the full messsage,

![screen-more-available](https://cloud.githubusercontent.com/assets/1123855/18988324/1285a2b2-86fe-11e6-9154-1a7d87c2c8dd.png)

**Comment by marius311** [comment]
I agree 100% (as was discussed a bunch [here](https://github.com/JunoLab/atom-julia-client/issues/199)). I can definitely understand the want to keep the output small until its expanded, and then I can kind of understand keeping the vertical size of the output small even once its expanded, but I still really don't see any reason for not using the entire horizontal space available. What of use could possibly be getting covered up? 

Just throwing out an idea, what about options "Allow output box to fill screen horizontally / vertically / both" (which could be off by default, i.e. the current behavior?

**Comment by pfitzseb** [comment]
I don't think anyone opposes the idea of making expanded results (or results in general) nicer, it's just that no ones gotten around to actually doing it yet.

**Comment by MikeInnes** [comment]
Yeah, mainly it's just technically a lot easier to have inline results as they are now. We have some patches to atom core which will improve the situation though.

**Comment by pfitzseb** [comment]
One idea would be to turn the inline result into a block result when expanding, but I'm not sure if that'd feel and look good.

**Comment by Karsten7** [comment]
@janekdb You can add 
```
.ink.inline {
  max-width: inherit;
}
```
to your _styles.less_ file (which can be opened using the Menu Bar: File ► Stylesheet...), to remove the default limitation to 400px.

**Comment by JobJob** [comment]
Adding this just above (and with the same indentation as) [this line](https://github.com/JunoLab/atom-julia-client/blob/master/lib/runtime/evaluation.coffee#L35)
```
pixels2edge = editor.editorElement.getBoundingClientRect().right - (r.view.offsetParent.offsetLeft)
r.view.offsetParent.style.width = pixels2edge - 24 + "px" #-24 for the vert scrollbar and a little clearance
```
is a kludgy but acceptable workaround for me.
@MikeInnes what patches are you referring to in your previous post? How does my fix make you feel? : )

Btw Juno makers I have just been trying Juno out again in the last few days and am loving it! Thank you!

**Comment by JobJob** [comment]
For anyone game enough to use my ugly fix, here is an even uglier version that works better, I was finding the `r.view.offsetParent` wasn't always available (some rendering timing issue I guess).

Put this just above (and with the same indentation as) [this line](https://github.com/JunoLab/atom-julia-client/blob/master/lib/runtime/evaluation.coffee#L35)
```
ensureResultResize = ->
  if r.view.offsetParent?
    editorRight = editor.editorElement.getBoundingClientRect().right
    resultLeft = r.view.offsetParent.offsetLeft
    pixelsForResult = editorRight - resultLeft
    r.view.offsetParent.style.width = pixelsForResult - 24 + "px" #-24 for the vert scrollbar and clearance
  else
    setTimeout(ensureResultResize, 5)
ensureResultResize()
```

As before you'll need to make @Karsten7's change to your styles.less file (which can be found in preferences->Open Config Folder button on left hand side)

**Comment by pfitzseb** [comment]
This has been *finally* fixed in the latest Juno release.

**Comment by JobJob** [comment]
🎉
