### ISSUE TITLE
Julia client internal error: non-boolean (Void) used in boolean context

### ISSUE THREAD

**Issue by dpsanders** [JunoLab/atom-julia-client#25]
Looks like it will be great -- terrific work as usual, @one-more-minute!

Just installed on Mac OSX Yosemite.
When I try inline evaluation, I get "Julia Client - Internal Error" as follows.
Evaluation on the Julia console seems to be working, though.

```
TypeError: non-boolean (Void) used in boolean context
 in filter! at ./array.jl:921
 in files at /Users/dsanders/.julia/v0.5/CodeTools/src/module.jl:18
 in jl_files at /Users/dsanders/.julia/v0.5/CodeTools/src/module.jl:28
 in find_include at /Users/dsanders/.julia/v0.5/CodeTools/src/module.jl:79
 in filemodule at /Users/dsanders/.julia/v0.5/CodeTools/src/module.jl:90
 in modulenames at /Users/dsanders/.julia/v0.5/Atom/src/eval.jl:8
 in anonymous at /Users/dsanders/.julia/v0.5/Atom/src/eval.jl:22
 [inlined code] from /Users/dsanders/.julia/v0.5/Atom/src/comm.jl:23
 in anonymous at task.jl:63
```

Julia version:
```
julia> versioninfo()
Julia Version 0.5.0-dev+63
Commit 4a2298d* (2015-09-12 22:48 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.3.0)
  CPU: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by dpsanders** [comment]
Possibly related: I can't get `\alpha` to give the Unicode alpha.

**Comment by one-more-minute** [comment]
Glad to see you looking into this stuff :) Unfortunately this is a strange error that I haven't seen before – I can look into it via the backtrace but if I can't reproduce it might be tricky to fix.

Also, [latex-completions](https://github.com/JunoLab/atom-latex-completions) are moved out into their own package now, so that they can be enjoyed in any other languages you might happen to be using.

**Comment by dpsanders** [comment]
I no longer seem to get that problem. Sometimes inline evaluation doesn't work and there is a message "Julia has stopped: 1, null" on the Console.

But now I do seem to have inline evaluation working, many thanks! (And latex completions too now after your comment, thanks!)  Keep up the great work!

**Comment by mjhubert** [comment]
I fixed this problem by following this instruction
"You currently also need to run Pkg.checkout("JuliaParser") in order to avoid errors from the latest release."
