### ISSUE TITLE
Atom cannot start Julia (0.5), after updating Julia-client package to 0.5.7

### ISSUE THREAD

**Issue by uozden** [JunoLab/atom-julia-client#256]
Hi,
Atom cannot start Julia (0.5), after updating Julia-client package to 0.5.7 - on Windows 10-64bit. Thank you

**Comment by pfitzseb** [comment]
This should be fixed on 0.5.8 -- can you try updating?

**Comment by uozden** [comment]
Dear  @pfitzseb, thank you very much for the prompt response. Having update to 0.5.8, it worked.

**Comment by pfitzseb** [comment]
Great, glad it's working now!
