### ISSUE TITLE
no output for types that use the default `show` method

### ISSUE THREAD

**Issue by JeffBezanson** [JunoLab/atom-julia-client#262]
For example

```
type NewType; x; end
NewType(0)
```

Nothing is displayed, but it should show `NewType(0)`.

**Comment by MikeInnes** [comment]
In both editor and console I get the following output:

<img width="389" alt="screenshot 2016-10-07 22 28 27" src="https://cloud.githubusercontent.com/assets/2234614/19205965/7a041308-8cdd-11e6-93f8-c16ae496916c.png">

**Comment by JeffBezanson** [comment]
Maybe I need to upgrade something?

**Comment by MikeInnes** [comment]
We've never not had output in those cases but it could just be a bad state. I would definitely try a Pkg.update() and check for updates in Atom's settings.

**Comment by JeffBezanson** [comment]
Thanks. Updating everything seems to have fixed it.
