### ISSUE TITLE
julia-client notifications and the left side minimap conflict

### ISSUE THREAD

**Issue by dsweber2** [JunoLab/atom-julia-client#263]
When using the minimap on the left side and running julia inline (as with shift-enter), the output of the notification isn't aligned with the end of the code as normal, making it impossible to read the code underneath it. I'm not entirely sure if the fix should be here or in the minimap, so I've raised the issue in both.

screenshot of the behavior, see line 45 (or rather, don't which is the point):
![conflict](https://cloud.githubusercontent.com/assets/7095649/19217883/887a3862-8d9c-11e6-9c97-db34fc501ffc.png)

**Comment by pfitzseb** [comment]
I'll close this in favour of https://github.com/JunoLab/atom-ink/issues/79, because that's the repo that has the bug.
