### ISSUE TITLE
Issues with Atom integration

### ISSUE THREAD

**Issue by nhejazi** [JunoLab/atom-julia-client#266]
I've been using Juno on and off for a while now (from before the move to Atom), and I've had success in using the Juno IDE alongside Atom; however, after recent upgrades (macOS Sierra, Julia v0.5, and an Atom re-install), simply using `apm install uber-juno` seems to have no effect. Have any others experience similar behavior?

**Comment by pfitzseb** [comment]
That should be `apm install uber-juno` (or you could use the package installation GUI from inside Atom).

**Comment by nhejazi** [comment]
My bad on the type -- now fixed. I am using `apm install`; otherwise, I'd probably get some kind of obvious error message...

**Comment by MikeInnes** [comment]
uber-juno stores a config setting so that it only runs once. If you go into the uber-juno settings you may see a box that you can untick, then restart?

**Comment by nhejazi** [comment]
Ok, good to know. Tried that, and everything seems to be working fine now. I definitely was not clear on how `uber-juno` worked. @MikeInnes - I guess in case of future errors, it's probably best to just install `ink` and `julia-client` regularly via `apm`?

**Comment by MikeInnes** [comment]
You should get notified of updates via Atom so unless you have a clean install, using apm shouldn't be necessary. But yeah updating everything is a good way to go if there are issues.
