### ISSUE TITLE
Julia has stopped 

### ISSUE THREAD

**Issue by zlqs1985** [JunoLab/atom-julia-client#267]
Hi, I encounter a problem when using Atom as Julia IDE. When I click the "`Start Julia`" button within`Julia`menu, the console show me that "Julia has stopped". According some early response, it's due to outdated version. But my Julia version is 0.4.2 and even after I updated to the latest 0.5.0, the problem remains.

**Comment by ChrisRackauckas** [comment]
If you go to the REPL and type in `using Atom`, do you get an error?
