### ISSUE TITLE
inconsistent # of significant numbers

### ISSUE THREAD

**Issue by missperovaz** [JunoLab/atom-julia-client#274]
Hi folks,

I'm using Julia in Atom. 
See the example:
`unique([122 122.5 10 10.3]) 
`
displays the following result:
122 123 10 10.3

so, it is limiting the display both in console and inline evaluation to three significant digits. 
Any advice on that? This leads to a lot of confusion while debugging. 
Any help is appreciated.

thanks,

**Comment by pfitzseb** [comment]
Yeah, this can be pretty misleading.
You can click on numbers though to get them displayed in full precision.

**Comment by pfitzseb** [comment]
Should at least be mitigated by the "solution" in https://github.com/JunoLab/Juno.jl/issues/27,
