### ISSUE TITLE
0.5.10 version is causing the editor window to crash

### ISSUE THREAD

**Issue by malmaud** [JunoLab/atom-julia-client#277]
I see this immediately upon opening a Julia file
![screen shot 2016-11-14 at 11 18 51 am](https://cloud.githubusercontent.com/assets/987837/20274460/ad73af44-aa62-11e6-9ca7-0c80630f0f52.png)

**Comment by pfitzseb** [comment]
Is ink up-to-date?

**Comment by malmaud** [comment]
Yes, 0.6.1

**Comment by pfitzseb** [comment]
Huh, strange. Can you try opening the dev console before loading a julia file and post a screenshot if there's anything interesting there?

**Comment by malmaud** [comment]
I actually get that error immediately upon starting Atom - it's not actually contingent upon opening a Julia file.

**Comment by malmaud** [comment]
So i tried uninstallingl ink and julia-client and reinstalling them, and that worked. So I guess this can be closed?

**Comment by pfitzseb** [comment]
Probably, but still strange that you got into that state.
