### ISSUE TITLE
Cannot connect to external process

### ISSUE THREAD

**Issue by AStupidBear** [JunoLab/atom-julia-client#278]
After updating Julia-client to the latest version, I cannot connect to external processes.
![2016-11-15_190959](https://cloud.githubusercontent.com/assets/16422976/20303605/25610948-ab67-11e6-85a6-ed76e1c1e98a.png)
![2016-11-15_190710](https://cloud.githubusercontent.com/assets/16422976/20303528/bfc00044-ab66-11e6-9ac1-dbc1006c2f17.png)
It keeps running forever.

**Comment by pfitzseb** [comment]
Are your Julia packages up-to-date?

**Comment by AStupidBear** [comment]
No, maybe that' the problem.BTW, does it support ssh forward as before?Yao

**Comment by pfitzseb** [comment]
Please reopen if this still is an issue.
