### ISSUE TITLE
Julia kernel closes during initial startup

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-julia-client#28]
Here is the log when I try to start Julia, by evaluating a line consisting of just "1".  Every time it said "Julia has stopped" I had to re-evaluate the line to start bootup.  Eventually it got there.

Julia
INFO: Recompiling stale cache file /Users/solver/.julia/lib/v0.4/Media.ji for module Media.
INFO: Recompiling stale cache file /Users/solver/.julia/lib/v0.4/Requires.ji for module Requires.
Julia has stopped: 1, null
INFO: Recompiling stale cache file /Users/solver/.julia/lib/v0.4/Hiccup.ji for module Hiccup.
Julia has stopped: 1, null
INFO: Recompiling stale cache file /Users/solver/.julia/lib/v0.4/CodeTools.ji for module CodeTools.
INFO: Recompiling stale cache file /Users/solver/.julia/lib/v0.4/LNR.ji for module LNR.
Julia has stopped: 1, null
INFO: Recompiling stale cache file /Users/solver/.julia/lib/v0.4/JuliaParser.ji for module JuliaParser.

**Comment by dlfivefifty** [comment]
This is 0.4.0-rc1 and Atom 1.0.11 with packages up to date

**Comment by one-more-minute** [comment]
Will be fixed in julia 0.4.2
