### ISSUE TITLE
Error initializing Array of a custom type of length 26

### ISSUE THREAD

**Issue by DatName** [JunoLab/atom-julia-client#282]
This is very weird, but the following lines of code produce "Julia Client -- Internal Error" in Atom:

```
type TestType
end

A = Array(TestType, 26)
```

The error is 

>  UndefRefError: access to undefined reference
>  in setindex!(::Array{Any,1}, ::Array{TestType,1}, ::UnitRange{Int64}) at .\array.jl:436
>  in cat_t(::Int64, ::Type{T}, ::Array{TestType,1}, ::Vararg{Any,N}) at .\abstractarray.jl:1098
>  in cat(::Int64, ::Array{TestType,1}, ::Hiccup.Node{:span}, ::Array{TestType,1}, ::Vararg{Array{TestType,1},N}) at .\abstractarray.jl:1057
>  in trim(::Array{TestType,1}, ::Int64) at C:\Users\Pavel\.julia\v0.5\Juno\src\base\base.jl:84
>  in render(::Juno.Inline, ::Array{TestType,1}) at C:\Users\Pavel\.julia\v0.5\Media\src\system.jl:175
>  in render at C:\Users\Pavel\.julia\v0.5\Atom\src\display\view.jl:51 [inlined]
>  in render(::Juno.Editor, ::Array{TestType,1}) at C:\Users\Pavel\.julia\v0.5\Juno\src\types.jl:13
>  in (::Atom.##53#56)(::Dict{String,Any}) at C:\Users\Pavel\.julia\v0.5\Atom\src\eval.jl:66
>  in handlemsg(::Dict{String,Any}, ::Dict{String,Any}, ::Vararg{Dict{String,Any},N}) at C:\Users\Pavel\.julia\v0.5\Atom\src\comm.jl:163
>  in (::Atom.##14#17)() at .\event.jl:68

The line `A = Array(TestType, 25)` works. Just as `B = Array(Float64, 26)`. 

This error does not occur in REPL.

I run it under Windows.
Atom version is 1.12.15
julia-client version is 0.5.10
ink version 0.6.1
language-julie version is 0.10.0
uber-juno version is 0.1.1

**Comment by pfitzseb** [comment]
This should be fixed by https://github.com/JunoLab/Juno.jl/commit/3d81eb2a179735bf0cc435d6670d7196419e4184. Thanks for reporting!
