### ISSUE TITLE
Display Error: UpperTriangular

### ISSUE THREAD

**Issue by mkriele** [JunoLab/atom-julia-client#285]
In the  original Julia console upper triangular matrices are displayed as matrices, where the lower triangular entries are displayed as single dots.  In Juno the lower triangular entries are displayed as random values.  
```Julia
x = [1.2 2 3; 0 4 6; 0 0 2]
A = x'x
chol(A)
3×3 UpperTriangular{Float64,Array{Float64,2}}:
 1.2   2.0  3.0
 2.4   4.0  6.0
 3.6  30.0  2.0
```
(the displayed values 2.4, 2.6, 30.0 are random and will likely be different when replicating this code).

This is purely a display issue with the Juno UI. If I select the output in Juno and copy it into this message I get the correct display here in this message:
```Julia
3×3 UpperTriangular{Float64,Array{Float64,2}}:
 1.2  2.0  3.0
  ⋅   4.0  6.0
  ⋅    ⋅   2.0
```
This display issue appears both in the Juno console and for inline results in Julia source files.

**Comment by pfitzseb** [comment]
This is fixed on master, we now fall back on the show method if there's no render method.
