### ISSUE TITLE
Feature request: option to disable dimming `end`'s 

### ISSUE THREAD

**Issue by marius311** [JunoLab/atom-julia-client#287]
With atom-julia-client enabled, all the `end`'s in my code get dimmed a bit like this:

![image](https://cloud.githubusercontent.com/assets/1510968/20806472/58c38914-b7fb-11e6-94d1-4d84da5ca491.png)

I'm not sure the purpose of this, but for me it actually makes it visually more confusing to parse a piece of Julia code. Could there be an option to disable it?

**Comment by pfitzseb** [comment]
I'm not sure if an explicit option would be a good idea. You can just add
```
atom-text-editor::shadow {
  .keyword.control.end.julia {
    opacity: 1;
  }
}
```
to your `styles.less` file and `end`s won't be dimmed anymore.

**Comment by marius311** [comment]
Perfect, that works, thanks.

**Comment by pfitzseb** [comment]
This'll change to 
```css
atom-text-editor{
  .keyword.control.end.julia {
    opacity: 1;
  }
}
```
in the next atom version, btw.
