### ISSUE TITLE
julia-client internal error

### ISSUE THREAD

**Issue by waelsboui** [JunoLab/atom-julia-client#289]
Atom : 1.12.6
Julia-client: 0.5.10
Ink: 0.6.1
language-Julia: 0.10.0
Uber-juno: 0.1.1
Julia: 0.4.6

Can anyone help me fix this trouble please ?

![julient-client](https://cloud.githubusercontent.com/assets/22308719/20884571/049582d6-baba-11e6-83c5-27dd77041468.JPG)

**Comment by pfitzseb** [comment]
This should be resolved by `Pkg.update()` -- if not, please reopen this issue.
