### ISSUE TITLE
Output gives "write: broken pip (EPIPE)"

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-julia-client#29]
Evaluating `versioninfo()` gives a long error message (which I can't copy and paste).  Here are some  relevant lines:

```
write: broken pip (EPIPE)
in yieldto at /Applications.../julia/sys.dylib
in wait at /Applications.../julia/sys.dylib
in stream_wait at /Applications.../julia/sys.dylib
in uv_write at stream.jl:952
...
in versioninfo at interactiveutil.jl:153 (repeats 2 times)
in include_string at .../v0.4/CodeTools/src/eval.jl:32
in include_string at .../v0.4/CodeTools/src/eval.jl:36
[inlined code] from  .../v0.4/Atom/src/eval.jl:37
in anonymous at task.jl:63
```

This is in julia-0.4.0-rc1 and Atom 1.0.11 on OS X

**Comment by CarloLucibello** [comment]
I get such error each time I evaluate commands such as println("hi"). It is the same for you?

**Comment by Varanas** [comment]
@CarloLucibello Are you using OS X as well?

**Comment by CarloLucibello** [comment]
No, ArchLinux, with  julia-0.4.0-rc1 and updated atom-julia-client

**Comment by one-more-minute** [comment]
This is related to #28 – when precompilation runs it breaks the STDOUT pipe. You can fix it simply by restarting the client – and in general, if a change to Atom.jl or its deps triggers precompilation, kill Julia and restart before working.

**Comment by Varanas** [comment]
For once an issue that *doesn't* happen on Windows. Astonishing...

**Comment by one-more-minute** [comment]
Wow, really? Guess that's a first for us then

**Comment by nilshg** [comment]
Yep, I've never seen this on any of my systems. Windows ftw :)

**Comment by one-more-minute** [comment]
This is fixed in Julia master
