### ISSUE TITLE
begin/end screws up working module detection

### ISSUE THREAD

**Issue by marius311** [JunoLab/atom-julia-client#290]
The following scenario looks to not be parsed correctly in terms of the working module detection,

```julia
module test

# <- put cursor here, says (correctly) we're in Main/test

f(x) = begin
end

# <- put cursor here, says we're in Main

end
```

Note the `f(x)` is necessary, a bare begin/end works fine. This is Julia 0.5 and atom-julia-client 0.5.10. 

Incidentally, when someone looks at this maybe they can also fix the somewhat similar https://github.com/JunoLab/atom-julia-client/issues/198 which appears to still be around? :)

**Comment by MikeInnes** [comment]
This should be fixed now, unfortunately #198 is still an issue though.

**Comment by pfitzseb** [comment]
Also relevant: https://github.com/JunoLab/CodeTools.jl/issues/21

The gist in my last post over there seems to work pretty well, but unfortunately needs the unreleased Tokenize.jl package.

**Comment by MikeInnes** [comment]
That's good to know at least, it'll be easy to integrate your patch. I'm sure we could bug for a Tokenizer release if it's going to be useful to us.

**Comment by KristofferC** [comment]
Just fyi, Tokenize.jl does not correctly tokenize stuff that involve transpose operators (`'`) and will try to consume characters while trying to finish what it thinks is a `Char` literal.

**Comment by marius311** [comment]
Great, thanks very much. Which repo and/or branch do I need to get to see the fix?

Incidentally, I found another case (which may well also be fixed). Basically replace the `f(x)..` line above with,

```julia
@anymacro begin
end
```

**Comment by pfitzseb** [comment]
`Pkg.checkout("CodeTools")` should do the trick, for some of those cases. By no means very comprehensive yet, sadly.

**Comment by marius311** [comment]
Ok, great, confirm both things I mentioned fixed.
