### ISSUE TITLE
unknown option: --depwarn=yes  in process_options at client.jl:306  in _start at client.jl:389

### ISSUE THREAD

**Issue by bethrice44** [JunoLab/atom-julia-client#291]
I have installed Atom, Juno and have Julia version 0.5.0. When I try to run a command in the Julia console I get the error:

unknown option: --depwarn=yes
 in process_options at client.jl:306
 in _start at client.jl:389

Julia has stopped: 1

I have uninstalled and reinstalled all of the above, but I get the same error.

**Comment by pfitzseb** [comment]
Are you sure that you have pointed Juno at the 0.5 binary?

**Comment by bethrice44** [comment]
Thanks - fixed! I had an old version of Julia installed that it was pointing at, whoops.

**Comment by pfitzseb** [comment]
Great, glad you got Juno running now!
