### ISSUE TITLE
Plot windows not calculating size properly

### ISSUE THREAD

**Issue by staticfloat** [JunoLab/atom-julia-client#297]
After installing 0.5.11 with the new button widgets in the Plots windows, it looks like plot heights are not being calculated properly, they're being created a little too tall for the pane size:

![screen shot 2016-12-15 at 12 53 30 pm](https://cloud.githubusercontent.com/assets/130920/21241668/813a76f8-c2c5-11e6-888c-603d7a4ddaac.png)

**Comment by pfitzseb** [comment]
Yup, that's because of the toolbar.

**Comment by pfitzseb** [comment]
And should be fixed on master.
