### ISSUE TITLE
Julia

### ISSUE THREAD

**Issue by yellow95** [JunoLab/atom-julia-client#298]
How can I fix that problem, is there someone who can help me, please? :)

ERROR: LoadError: could not open file C:\Users\Piotrek\.julia\v0.5\MbedTLS\src\..\deps\deps.jl
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\Users\Piotrek\.julia\v0.5\MbedTLS\src\MbedTLS.jl, in expression starting on line 38
ERROR: LoadError: Failed to precompile MbedTLS to C:\Users\Piotrek\.julia\lib\v0.5\MbedTLS.ji.
 in compilecache(::String) at .\loading.jl:593
 in require(::Symbol) at .\loading.jl:393
 in include_from_node1(::String) at .\loading.jl:488
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\Users\Piotrek\.julia\v0.5\HttpServer\src\HttpServer.jl, in expression starting on line 10
ERROR: LoadError: LoadError: Failed to precompile HttpServer to C:\Users\Piotrek\.julia\lib\v0.5\HttpServer.ji.
 in compilecache(::String) at .\loading.jl:593
 in require(::Symbol) at .\loading.jl:393
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\Users\Piotrek\.julia\v0.5\Mux\src\server.jl, in expression starting on line 1
while loading C:\Users\Piotrek\.julia\v0.5\Mux\src\Mux.jl, in expression starting on line 22
ERROR: LoadError: LoadError: Failed to precompile Mux to C:\Users\Piotrek\.julia\lib\v0.5\Mux.ji.
 in compilecache(::String) at .\loading.jl:593
 in require(::Symbol) at .\loading.jl:393
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\Users\Piotrek\.julia\v0.5\Blink\src\content/content.jl, in expression starting on line 1
while loading C:\Users\Piotrek\.julia\v0.5\Blink\src\Blink.jl, in expression starting on line 9
ERROR: LoadError: Failed to precompile Blink to C:\Users\Piotrek\.julia\lib\v0.5\Blink.ji.
 in compilecache(::String) at .\loading.jl:593
 in require(::Symbol) at .\loading.jl:393
 in include_from_node1(::String) at .\loading.jl:488
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\Users\Piotrek\.julia\v0.5\Atom\src\Atom.jl, in expression starting on line 5
ERROR: LoadError: Failed to precompile Atom to C:\Users\Piotrek\.julia\lib\v0.5\Atom.ji.
 in compilecache(::String) at .\loading.jl:593
 in require(::Symbol) at .\loading.jl:422
 in include_from_node1(::String) at .\loading.jl:488
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\Piotrek\.atom\packages\julia-client\script\boot.jl, in expression starting on line 29

**Comment by pfitzseb** [comment]
Your best bet is to ask for help over at https://github.com/JuliaWeb/MbedTLS.jl. Closing here, since this issue is unrelated to Juno.
