### ISSUE TITLE
Deprecated selector in `julia-client\styles\julia-client.less`

### ISSUE THREAD

**Issue by Karsten7** [JunoLab/atom-julia-client#300]
In `julia-client\styles\julia-client.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .keyword.control.end.julia` => `atom-text-editor.editor .syntax--keyword.syntax--control.syntax--end.syntax--julia`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by pfitzseb** [comment]
This is fixed on master.
