### ISSUE TITLE
Installing the latest "master" properly using git

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JunoLab/atom-julia-client#305]
I want to install the latest "master" version available on the GitHub website properly. 
Currently, the official release version is installed at ~/.atom/packages/julia-client .
So, I moved that folder to somewhere else and ran the command:
```git clone https://github.com/JunoLab/atom-julia-client```
which created the new most current master version as "atom-julia-client". So, I renamed it as "julia-client", and started atom. Then I got the error: Cannot find module 'etch' ...
So, I would appreciate it if someone could tell me how to properly install the master version.
The same applies for the "atom-ink" package.
Best,
BVPs

**Comment by Karsten7** [comment]
[This instructions](http://docs.junolab.org/latest/devdocs/dev_install.html) might be helpful.

**Comment by pfitzseb** [comment]
In particular, you need to call `apm install` in those directories.

**Comment by BoundaryValueProblems** [comment]
Karsten7 and pfitzseb: Thanks a lot. But since I already have the latest public release version in ~/.atom/packages, wouldn't ```apm upgrade atom-julia-client``` and ```apm upgrade atom-ink``` be sufficient instead of ```apm install``` commands? Or I still have to remove those existing folders and do ```apm install``` there?

**Comment by pfitzseb** [comment]
`apm install` actually installs the dependencies, which you need -- otherwise you get that error you reported. Also, I'd recommend installing the `master` branches into `.atom/dev/packages`, which are only loaded when starting with `atom -d`. So you can always get back to stable without having to mess around with git.
