### ISSUE TITLE
keywords inside comments screw up module detection

### ISSUE THREAD

**Issue by marius311** [JunoLab/atom-julia-client#308]
Caught another module detection bug. Keywords inside comments seem to be parsed as if they weren't commented. E.g. 

```julia
module test
# for
end
```

Now put the cursor after the `end` and atom-julia-client still thinks you're inside `Main/test`. 

Replacing `for` with `begin`, `function`, `type`, `immutable`, `if`, `while`, `do` and possibly others I haven't thought of triggers the same problem.

**Comment by marius311** [comment]
And another one. 

```julia
module test
[x for x=1:2]
end 
```

Again putting the cursor after the `end` it thinks you're still in `Main/test`. Funnily enough thanks to the above bug, the following is a workaround:

```julia
module test
[x for x=1:2] #end
end 
```

This is kind of related to https://github.com/JunoLab/atom-julia-client/issues/198

**Comment by MikeInnes** [comment]
This looks like it's finally fixed!
