### ISSUE TITLE
Juno in a browser?

### ISSUE THREAD

**Issue by EricForgy** [JunoLab/atom-julia-client#31]
Newbie alert...

I'm watching the development of Juno2 with interest and fascination. After Viral recently mentioned Atom in the user groups, I started reading about Atom. I'm a big fan of web technologies, so I think Atom/Juno are super cool. My first thought when learning Atom was written in Javascript was, "Cool! It should be able to run in a browser!" That excitement quickly faded when I read that a web-based Atom editor was a non-starter because it wouldn't have access to the file system. However, with the [communication](https://github.com/JunoLab/atom-julia-client/blob/master/docs/communication.md) developed here for use with Julia, access to the file system could be achieved via Julia.

Is it reasonable to have hope that Juno can be run from a browser, which would mean (I guess) stripping out the file system dependencies from Atom and use Julia for that instead?

Is that a Herculean effort or something a mortal like me (and my team) may possibly achieve?

I imagine a day where the browser is more like a desktop with app icons etc. I'd like to be able to double click a Juno icon on a web page (browser full screen to mimic a desktop) and have it pop up in a window all contained completely in the browser and completely in Javascript.

Here is a [demo video](https://www.youtube.com/watch?v=IriE1ZP-uOM) I uploaded last year that illustrates what I'm talking about. The video is long (and a bit dry - sorry), but here are some highlights:

* 0:40 - Simple blank "desktop" in the browser
* 0:52 - A dream of using the browser's Javascript console as a Julia REPL (?)
  * **Could some of the Coffee scripts in atom-julia-client be used to make this happen?**
* 2:28 - A basic window as a building block for web apps that are indistinguishable from desktop app. 
  * **This is where I would love to see Juno.**
* 3:30 - Dynamically adding callback functionality to SVG widgets
  * Note: There is not a single div in the entire demo. Everything is done on top of d3.js and SVG.
* 4:20 - Demonstrating the correct behavior when windows overlap
* 4:30 - Re-sizing windows.
* 4:50 - Adding widgets to widgets. Everything nests properly.
* 5:20 - Textbox callbacks (pure SVG and JS via d3.js)
* 5:30 - Dynamically adding callback functionality to textboxes

Since I made that demo video, I built a charting library on top of d3.js to go with it and I would love to be able to run Juno in a browser together with my charting library. Maybe it is wishful thinking (?) :)

**Comment by one-more-minute** [comment]
I agree that it would be amazing to see Juno in browser, especially if you could log on to something like JuliaBox and just start coding away with no setup. (The desktop-in-browser thing is also interesting – it seems like a lot of people have liked this idea in the past but it's never really taken off – not sure why exactly.)

Unfortunately, I think that kind of thing is pretty much orthogonal to Juno's current direction. Getting Atom (and it's huge ecosystem of plugins, remember) to work in the browser might be *technically* doable, if you faked the node.js APIs to go over TCP for example, but you'd have to battle with the fact that everything assumes low-latency access to both the node APIs and any npm dependencies. I've seen some speculation that github would be interested in this too, but unless they have some amazing trick up their sleeve I think it's pretty unlikely they'll go in this direction.

When I was looking into this it seemed like the only viable route was to build something in Julia which interfaced with a JS frontend, e.g. via Blink.jl. A lot of the GUI tools to do that already exist (e.g. CodeMirror, golden layout etc.), so it would be relatively easy to get the basics going, but turning that into something as polished and comprehensive as Atom is a herculean task in itself. Perhaps one day, but for now Atom is the local maximum.

**Comment by one-more-minute** [comment]
I'm going to close this for now since we depend on Atom's future development to even think about something like this, but thanks for opening the discussion!
