### ISSUE TITLE
No tab completion for field name

### ISSUE THREAD

**Issue by AStupidBear** [JunoLab/atom-julia-client#310]
![2017-02-05_114227](https://cloud.githubusercontent.com/assets/16422976/22623507/37892d96-eb98-11e6-831c-0890a92a52ac.jpg)

I use the latest master version of Atom.jl and Juno.jl. Packages of Atom.exe are also up to date.

**Comment by louisponet** [comment]
It seems that in the latest version this works? At least I seem to be getting field autocomplete suggestions. If so, the ones I'm getting have no label to the left of them, like functions (\lambda), types (T) etc. Would be very nice if there was like something similar for fields like (S) or whatever that it's clear that it's not an autocompletion that was derived from some other variable that it found in the current editor. I don't know if that's feasible but I would like that!

**Comment by pfitzseb** [comment]
This should work in the new REPL, but definitely not in an editor. https://github.com/pfitzseb/atom-julia-lsp-client might enable it though, if you're using that.
