### ISSUE TITLE
Feature Request: Smarter Parsing for .jmd files

### ISSUE THREAD

**Issue by kescobo** [JunoLab/atom-julia-client#311]
Related to [this discussion](https://discourse.julialang.org/t/smart-parsing-jmd-files-weave-jl/1877) on Discourse - It would be nice if the "evaluate all" on `.jmd` files would only evaluate code inside annotated code blocks. This way, when returning to a file to continue an analysis, I could simply open the file, evaluate all, and then pick up where I left off. Currently, it requires highlighting and evaluating each code block separately.

I'd be happy to take a stab at this myself, but would need some guidance as I have not done any developing in Atom.

**Comment by MikeInnes** [comment]
This would be a great feature and a welcome addition. In terms of taking a stab at it your best bet is probably to take a look at doing atom development independently of Juno, at least to begin with. The [atom manual](http://flight-manual.atom.io/) is the best resource for getting started, and you can get the text of the editor and start to process out the cells with commands like:

```js
ed = atom.workspace.getActiveTextEditor()
text = ed.getText()
```
which can be run interactively in the devtools. Once you can do some of that, hooking it up to julia-client for the actual evaluation should be reasonably straightforward.

**Comment by mpastell** [comment]
You can have a look at the https://atom.io/packages/language-weave for regex for parsing the code chunks. It would be great to see this feature, but I also don't have time to work on it right now. 

I would appreciate a mention on Weave related issues, I had missed this thread on discourse as well.

**Comment by mpastell** [comment]
@kescobo I realized that it's actually very simple to get the code from a `jmd` file if you use `language-weave`. Here is a simple function that extracts code from all chunks:

```javascript
    parse_chunks(){
        ed = atom.workspace.getActiveTextEditor();
        text = ed.getText();
        lines = text.split("\n");
        N = ed.getLineCount();
        var code = "";

        for (i=0; i<N; i++)
        {
            scopes = ed.scopeDescriptorForBufferPosition([i,0]).scopes;
            if (scopes.length > 1)
            {
                if (scopes[1] == "source.julia")
                {
                    code += lines[i] + "\n";
                    console.log(lines[i]);
                }
            }
        }
        return(code);
     }
```

**Comment by kescobo** [comment]
@mpastell That's great, thanks! 

If I understand correctly, because `language-julia` already tells the editor that code chunks have julia scope, it might just be a matter I can just check for the scope and evaluate if julia? Seems simple enough :-)

A billion things happening for me right now, but I will hopefully be able to take a stab at this sometime soonish.

**Comment by mpastell** [comment]
Exactly, scoping is defined in the grammar. I think the correct place start in this repo is https://github.com/JunoLab/atom-julia-client/blob/master/lib/runtime/evaluation.coffee#L48

**Comment by kescobo** [comment]
@mpastell Hmm... that *does* look promising.

**Comment by mpastell** [comment]
It seemed so simple that I made a pull request, looking forward to suggestion on how to improve.

**Comment by pfitzseb** [comment]
Implemented in https://github.com/JunoLab/atom-julia-client/pull/354.
