### ISSUE TITLE
MethodError: `bind`

### ISSUE THREAD

**Issue by christianlaurent1992** [JunoLab/atom-julia-client#315]
Hello, I am trying to install Juno, i've followed at least 2 different install instructions, and removed and reinstalled it etc. Julia is installed and works fine in the terminal- its just juno thats not working for me. cmake and curl are installed, i have run Pkg.update().
I am on ubuntu 16.04.2

If i try to run anything at all from the Julia console in atom, i get the following error: please please please help- Juno looks like it will be a great IDE!

MethodError: `bind` has no method matching bind(::Media.Binding{Any}, ::Atom.Console, ::Task)
Closest candidates are:
  bind{T}(!Matched::Lazy.Binding{T}, ::T, ::Task)
  bind{T}(!Matched::Function, !Matched::Lazy.Binding{T}, ::T)
 [inlined code] from /home/rabbit/.julia/v0.4/Lazy/src/dynamic.jl:67
 in anonymous at /home/rabbit/.julia/v0.4/Atom/src/eval.jl:98
 in anonymous at /home/rabbit/.julia/v0.4/Atom/src/eval.jl:97
 [inlined code] from /home/rabbit/.julia/v0.4/Atom/src/comm.jl:18

**Comment by pfitzseb** [comment]
Please update to julia 0.5.
