### ISSUE TITLE
UndefVarError: isdebugging not defined (Julia 0.6.0-pre.alpha.0)

### ISSUE THREAD

**Issue by asbisen** [JunoLab/atom-julia-client#316]
With `Julia 0.6.0` Atom fails in evaluating Julia expression with the error

`UndefVarError: isdebugging not defined`

![screen shot 2017-03-07 at 7 42 31 am](https://cloud.githubusercontent.com/assets/5142211/23664218/d3294c80-0309-11e7-8034-91ec4361d784.png)

**Comment by sbromberger** [comment]
Happening with `Version 0.6.0-pre.alpha.200 (2017-03-20 11:54 UTC)`

**Comment by asampal** [comment]
I'm seeing this too on one of my systems. Was originally using Atom 1.16 beta, and I was getting errors with Juno. I installed Atom 1.15, uninstalled uber-juno and the other packages it installs, re-installed uber-juno, but ended up with this error in the end. 

Using Windows, with Julia 0.6.0-pre.alpha.0 as well.

**Comment by malmaud** [comment]
@MikeInnes, is there an approximate timeline for Julia 0.6 support?

**Comment by asampal** [comment]
@malmaud , it looks like [gallium](https://github.com/Keno/Gallium.jl) is the dependency that needs to be upgraded to 0.6. Looking at recent commits there, I'm not sure that's a priority. Maybe worth checking with @Keno or @JeffBezanson to see if it's something imminent or not.

**Comment by pfitzseb** [comment]
Gallium isnt'a hard dependency -- the Juno debugger obviously won't work unless Gallium works on 0.6, but the rest should. I'll have a look once I get my hands on a 0.6 build (which will probably take a day or so).

**Comment by pfitzseb** [comment]
Nevermind, this should have been fixed by https://github.com/JunoLab/Atom.jl/commit/4b4d73dea7ad3d9dd183e966091fa4509808cf3c.

**Comment by asampal** [comment]
@pfitzseb , you're saying that Juno should be working with Gallium already, according to that fix?

**Comment by pfitzseb** [comment]
Yes, if you do `Pkg.checkout("Atom")`. The released version doesn't/shouldn't work yet, afaict.

**Comment by asampal** [comment]
Thanks, @pfitzseb - works now.

**Comment by pfitzseb** [comment]
Alright, great. Closing this then.
