### ISSUE TITLE
Juno.runtime.debugger.clearall is not a function

### ISSUE THREAD

**Issue by dpo** [JunoLab/atom-julia-client#319]
Selecting "Julia Debug: Clear All Breakpoints" from the command pane results in the above message. This is on OSX 10.11, Atom 1.15.0, julia-client 0.5.12 and everything else I could think of updated.

**Comment by AStupidBear** [comment]
+1

**Comment by AStupidBear** [comment]
@pfitzseb Can you tag a new release for this fix?
