### ISSUE TITLE
"Media not defined"

### ISSUE THREAD

**Issue by mkborregaard** [JunoLab/atom-julia-client#323]
If I run (Cmd-shift-enter) the StatPlots.jl or PlotRecipes.jl module in Juno, it fails with the message "Media not defined". I can usually get it to work with `using Media` and rerunning the module in StatPlots, but PlotRecipes (that imports and reexports StatPlots) continue in an unstable state and so I cannot use Juno to edit either of these packages. Everything works great from the REPL. 
Probably related to / identical to https://github.com/JuliaPlots/PlotRecipes.jl/issues/16

**Comment by mkborregaard** [comment]
This seems to have been reported several times in the past for Plots
https://github.com/JuliaPlots/Plots.jl/issues/543
https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/105

**Comment by pfitzseb** [comment]
I think this is because of Plots.jl's somewhat unorthodox Juno.jl integration -- I've been meaning to create a PR that is more in line with out API, but haven't gotten around to it yet.

**Comment by ChrisRackauckas** [comment]
It's Plots.jl's `@eval` and precompilation usage, not a Juno issue.

**Comment by ChrisRackauckas** [comment]
Yeah.
