### ISSUE TITLE
Cannot go to definitions of macros

### ISSUE THREAD

**Issue by AStupidBear** [JunoLab/atom-julia-client#324]
The ```Go to Definition``` functionality works fine for functions, but not for macros.

**Comment by pfitzseb** [comment]
We currently look for `methods(functionname)` to get the definition location, which obviously doesn't work for macros. Not sure if we can actually get this information through julia introspection or not...

**Comment by AStupidBear** [comment]
Thanks

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/Atom.jl/commit/6ae269a60ed6b842917e9081865327e94afabdbd.
