### ISSUE TITLE
No highlighting for breakpoints

### ISSUE THREAD

**Issue by AStupidBear** [JunoLab/atom-julia-client#327]
There should be a red dot on ```  x / rand(10)```
![2017-04-07_232933](https://cloud.githubusercontent.com/assets/16422976/24807345/6ac07bd8-1bea-11e7-8974-eb85079effdd.jpg)

My juno packages are up to date. ```Atom.jl``` and ```Juno.jl``` are on masters.

**Comment by pfitzseb** [comment]
Can't reproduce this on latest master.
