### ISSUE TITLE
latex rendering

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/atom-julia-client#329]
using https://github.com/nteract/mathjax-electron.

**Comment by MikeInnes** [comment]
Worth checking out [Katex](https://khan.github.io/KaTeX/). MathJax's architecture is pretty insane so that may be a better way forward.

**Comment by pfitzseb** [comment]
```
var mathjaxHelper = require('mathjax-electron')

var container = document.createElement('div')
container.innerHTML = '$$\\sum\\limits_{i=0}^{\\infty} \\frac{1}{n^2}$$'

mathjaxHelper.loadAndTypeset(document, container)
```
seemed pretty easy to me, but I didn't look into it apart from the fact that Hydrogen uses mathjax.

**Comment by pfitzseb** [comment]
KaTeX is supported in the `sp/docpane` branches of ink and julia-client now. Was surprisingly easy to implement.
