### ISSUE TITLE
cannot find the "end" when run the definition of the "Struct"

### ISSUE THREAD

**Issue by zhangliye** [JunoLab/atom-julia-client#333]
![image](https://cloud.githubusercontent.com/assets/8065051/25521787/8467f800-2c33-11e7-97fb-d6c56bbff401.png)

when click 'Enter' while put the cursor within the "Struct"

**Comment by pfitzseb** [comment]
That's been fixed by https://github.com/JunoLab/atom-julia-client/commit/2b76e7a09e52e348fbc556c802ab015356564077. Until a new version is released you can just select the definition and eval that.
