### ISSUE TITLE
julia-client cannot find julia binary

### ISSUE THREAD

**Issue by Ward9250** [JunoLab/atom-julia-client#335]
I use a julia install on OSX obtained from downloading the latest release source branch and compiling.

Recently julia-client has been giving me the following message:

>We tried to launch Julia from:
>~/github/julia/usr/bin/julia
>This path can be changed in the settings.
>Details:
> /bin/sh: ~/github/julia/usr/bin/julia: No such file or directory

As you can see, rather than let it find julia, in my preferences I've spelt out the exact location of the binary, as in the past finding julia would often not work for me: even though the julia binary folder is on my PATH:
```sh
bward$ echo $PATH
/Users/bward/anaconda/bin:/Users/bward/.nvm/versions/node/v6.9.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/munki:/Library/TeX/texbin:/Users/bward/.rvm/bin:/Users/bward/github/julia/usr/bin
```

**Comment by Ward9250** [comment]
Update:

Using the path: /Users/bward/github/julia/usr/bin/julia works. So the tidle as denoting $HOME is what messes things up it seems. Could support be added for expanding '~'?

**Comment by pfitzseb** [comment]
Done.
