### ISSUE TITLE
better console cell-break heuristics

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-julia-client#341]
I sometimes find the console to be a little over-aggressive in splitting output into cells, resulting in output that looks like this:
![image](https://cloud.githubusercontent.com/assets/734386/25857065/eb5c2b7e-34a5-11e7-8ea5-b537ee2e8036.png)
I understand that splitting the text stream into conceptually-related blocks is a tricky problem and it's never going to be perfect, but I think there's room to improve the heuristics.

Where in the code is this splitting handled?

**Comment by MikeInnes** [comment]
I think this sometimes happens on the first warning, just because Julia is compiling at the same time as printing, but then it calms down. The timeout for a new block is 0.1s which should be high enough generally.

Anyway, the code is [here](https://github.com/JunoLab/atom-ink/blob/bc2c6adfb5d1fa22bbfbad7fa1dcb3f6593255f7/lib/console/console.js#L258-L267) if you want to take a look.

**Comment by pfitzseb** [comment]
This also feels *much* worse on Windows, imho.

**Comment by MikeInnes** [comment]
Ok, yeah, I just saw an old thread where we'd discussed exactly that.

We could try just bumping it to 1s or something.

**Comment by pfitzseb** [comment]
1s buffer time:
![screenshot_20170509_174041](https://cloud.githubusercontent.com/assets/6735977/25859403/b94f19fa-34de-11e7-8071-c674279549e7.png)
0.1s buffer time:
![screenshot_20170509_173949](https://cloud.githubusercontent.com/assets/6735977/25859425/c5947a16-34de-11e7-9929-9e1d11e43695.png)

We could try starting a new cell whenever we encounter a blank line in the output (plus a long buffer time, like a second or so). Would at least work pretty well for that example.

**Comment by ssfrr** [comment]
> This also feels much worse on Windows, imho.

Yeah, I've been on windows lately, so maybe that's why I'm noticing it more.

I'd be a fan of bumping up the timeout, it seems like false positives (splitting that which shouldn't be split) are worse than false negatives. I'm not sure if there are any situations that I'd be annoyed that it didn't split something, particularly because it already forces a split when the `type` of the output changes.

One option (if you wanted more granularity) would be to add something that split whenever a line started with `INFO:`, `WARNING:`, or `ERROR:`.

**Comment by ssfrr** [comment]
another data point:
![image](https://cloud.githubusercontent.com/assets/734386/25965066/d7ee314e-3654-11e7-8454-8525847d3a02.png)

the timeout logic ends up randomly grouping the output. What if it never used the timeout and _only_ split on `type` transitions or `INFO:`, `WARNING:` and `ERROR:`s?

**Comment by pfitzseb** [comment]
Old console is deprecated.
