### ISSUE TITLE
Changes required due to TextBuffer.save becoming async in Atom 1.19

### ISSUE THREAD

**Issue by maxbrunsfeld** [JunoLab/atom-julia-client#353]
Hi! Thanks for maintaining the julia-client package!

In Atom v1.19, we will release a [major change](https://github.com/atom/atom/pull/14435) to Atom's core text buffer data structure. As part of this change, we have made `TextBuffer.save` asynchronous; rather than blocking until the save is complete, it now immediately returns a `Promise` that *resolves* when the save is complete. Because of this, a few other Atom APIs that *use* `save` have similarly become async:

* `Pane.close`
* `TextBuffer.save`
* `TextEditor.save`
* `Pane.saveItem`
* `Pane.saveItemAs`
* `Pane.saveActiveItem`
* `Pane.saveActiveItemAs`
* `Pane.saveItems`
* `Workspace.saveActivePaneItem`
* `Workspace.saveActivePaneItemAs`

#### Effects on this package

We think this package could be impacted by this upgrade because it calls the changed methods in the following places:

We think this package could be impacted by this upgrade because it calls the changed methods in the following places:

* `Pane.close`
  * [here](https://github.com/JunoLab/atom-julia-client/tree/master/lib/runtime/profiler.js#L25)
  * [here](https://github.com/JunoLab/atom-julia-client/tree/master/lib/runtime/profiler.js#L34)
  * [here](https://github.com/JunoLab/atom-julia-client/tree/master/lib/ui/layout.js#L49)

We found these calls using a regex search, so this list might be incomplete, and it might contain some false positives.

#### What to do about the change

It should be pretty easy to adjust your package code and/or tests to work with the new async behavior, and to simultaneously keep it working with older versions of Atom. Here are some examples of pull requests we opened on our bundled packages to cope with the change:

* https://github.com/atom/autocomplete-plus/pull/852
* https://github.com/atom/whitespace/pull/155
* https://github.com/atom/symbols-view/pull/222
* https://github.com/atom/status-bar/pull/193
* https://github.com/atom/tabs/pull/448

Let me know if you have any questions. I'd be happy to help!

**Comment by MikeInnes** [comment]
I think the first to examples are fine, we will probably need to handle the third: https://github.com/JunoLab/atom-julia-client/blob/efdfb7ff669b45fe365b3cbd04b6702b62dff83d/lib/ui/layout.js#L49

**Comment by pfitzseb** [comment]
We can just wrap that in a `Promise.all(...).then`, I think.
