### ISSUE TITLE
Make key cobination for line break consistent with the REPL

### ISSUE THREAD

**Issue by IlyaOrson** [JunoLab/atom-julia-client#357]
In the Juno console you have to use `Alt`+`Enter` to insert a new line of code without evaluating the expression, while in the REPL one uses `Ctrl`+`Enter`. I think it would be better to have the same key combination for this. 

PS Thanks for the amazing Juno! :smile:

**Comment by pfitzseb** [comment]
Makes sense to me -- I've added it as an additional keybinding, so either <kbd>Ctrl</kbd> or <kbd>Alt</kbd> work.
