### ISSUE TITLE
Can't dismiss multiple outputs simultaneously

### ISSUE THREAD

**Issue by marius311** [JunoLab/atom-julia-client#359]
Not sure exactly when, but I seem to have lost the ability to dismiss multiple outputs by selecting more than one line and hitting Esc, I now have to do them one-by-one. This is on Julia 0.6, Atom 1.18.0, and atom-julia-client 0.6.0.

**Comment by pfitzseb** [comment]
Is `atom-ink` up-to-date? I can't reproduce this (on Juno master at least).

**Comment by marius311** [comment]
I think so, I have atom-ink 0.7.4, (just checked with Juno 0.3.0 and master, problem still there). I wanted to use the keybinding resolver to check Esc is triggering the right call in that case at least, but actually Esc just closes the keybinding resolver itself, ha. Any other ideas?

**Comment by pfitzseb** [comment]
You could put something like
```
'atom-text-editor:not([mini])':
  'f6': 'inline:clear-current'
```
into your `keymap.cson`. Also try calling `Inline: Clear Current` directly from the command pane.

**Comment by marius311** [comment]
Thanks, OK, using that to trigger the command, I confirm its not working for me in the multi-line case.

**Comment by pfitzseb** [comment]
Huh, okay. Can you try opening the Atom console <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>I</kbd> and look out for any errors?
Also, do you have any wrapped lines in the editor this is happening in (or is it happening in a new one with e.g. only `1+1 \n 2+2` in it?)?

**Comment by marius311** [comment]
This is happening in an empty editor with just `1` on one line and `2` on the other. No console errors, this is all I see on there in fact, 

```
requiring if needed: snippet-manager
/home/marius/.atom/packages/latextools/lib/snippet-manager.coffee:15 Created SnippetManager
/home/marius/.atom/packages/latextools/lib/snippet-manager.coffee:19 Set snippet service
/home/marius/.atom/packages/latextools/lib/snippet-manager.coffee:20 Object
/home/marius/.atom/packages/minimap/node_modules/element-resize-detector/src/detection-strategy/scroll.js:49 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
misc.coffee [sm]:28 Julia Boot: 4.87s
```

**Comment by pfitzseb** [comment]
Okay, I think I figured this out -- you can dismiss the results if you select text from the bottom to the top, but not the other way around. Fix incoming.

**Comment by marius311** [comment]
Yep, that did it. Thanks alot!
