### ISSUE TITLE
Progress indicator on remote desktop

### ISSUE THREAD

**Issue by alyst** [JunoLab/atom-julia-client#370]
I'm using Atom remotely using xpra. I've noticed that both network and (client) CPU usage are quite high when Julia is doing computations. My guess is that it's because of the progress animation -- when the computations are over the responsiveness of remote apps and CPU usage go back to normal. I don't think it's the server issue: it's 32-core node without other active users and only 1 Julia worker is used.

Is it possible to implement another progress indicator, e.g. RStudio-like semaphor? I don't have that kind of remote desktop responsiveness drops with RStudio.
It could also be that xpra is too eager in identifying the region to be updated, so maybe the alternative solution would be to keep the animation, but change the implementation to reduce the invalidated region.

**Comment by pfitzseb** [comment]
Can you try pasting
```
progress.ink:indeterminate {
  animation-iteration-count: 0;
}
```
into your `styles.less` (search for `Open Your Stylesheet` in the command pane) and then evaling something like `sleep(10)`? If it is indeed that animation at fault then CPU usage should be normal with that change.

**Comment by alyst** [comment]
Hmm, with the frozen progress indicator I don't see CPU going back to the background levels. But there's still the pulsation of the console prompt. Is it possible to disable it through the stylesheet as well?

**Comment by pfitzseb** [comment]
Sure:
```
ink-console .divider.loading {
  animation-iteration-count: 0;
}
```

**Comment by alyst** [comment]
ah, and there's also the spinning cogwheel for the running code block

**Comment by pfitzseb** [comment]
```
.ink.result.julia.inline.loading .icon::before {
  animation-iteration-count: 0;
}
```

**Comment by alyst** [comment]
I've experimented with `sleep(10)` a bit. Enabling either console pulsing or progress indicator leads to some CPU (15% of each 4 cores) and bandwidth usage (~1Mb/s on FullHD fullscreen Atom, zlib compression).
The cog animation doesn't eat up that much of a bandwidth, but CPU is still used.

**Comment by pfitzseb** [comment]
So if you disable the animations you see saner CPU/network usage? Workaround for now would be to keep the custom css, but I'll look into optimizing the animations when I find the time.
