### ISSUE TITLE
break button?

### ISSUE THREAD

**Issue by nickeubank** [JunoLab/atom-julia-client#375]
In the REPL, if one accidentally starts a loop that runs forever, once can break execution with `cmd-.` (on a mac) without having to terminate the session. I can't find an analogous feature in Juno -- I can `Stop Julia`, but then I lose my session and everything loaded up (I work with big files, so load time is non-trivial).

**Comment by pfitzseb** [comment]
<kbd>Ctrl</kbd><kbd>C</kbd> should work. The command you're looking for is called `Interrupt Julia`.
I guess that would be more easily discoverable with a button in the console toolbar or something?

**Comment by nickeubank** [comment]
I think that'd be nice. Most interactive editors I know have a break button in top right:

spyder:

![screen shot 2017-08-10 at 10 28 14 am](https://user-images.githubusercontent.com/9683693/29178290-b6f23efa-7db6-11e7-867d-7076fa6d6dc1.png)


RStudio:

![screen shot 2017-08-10 at 10 26 07 am](https://user-images.githubusercontent.com/9683693/29178298-beb22ab0-7db6-11e7-9e99-c6baaecf6270.png)


Stata:

![screen shot 2017-08-10 at 10 26 28 am](https://user-images.githubusercontent.com/9683693/29178305-c40f38f4-7db6-11e7-9397-60cd9ad32e3f.png)

**Comment by pfitzseb** [comment]
Implemented in https://github.com/JunoLab/atom-julia-client/commit/34f6cb0b3c7bf34e1c97bb07082fbb6204169170.

**Comment by nickeubank** [comment]
@pfitzseb That was fast! Thanks!! 👍
