### ISSUE TITLE
Wierd output selection bug

### ISSUE THREAD

**Issue by marius311** [JunoLab/atom-julia-client#378]
Is anyone else seeing this? Its as if parts of the output are being "selected". Here I'm just left-clicking on the expand buttons with no keys pressed.

![demo](https://user-images.githubusercontent.com/1510968/29998995-e732ebca-9038-11e7-81bd-2de63ba85724.gif)

```
Atom.jl           0.6.1
CodeTools.jl      0.4.6
atom-julia-client 0.6.0
atom-ink          0.7.4
```

**Comment by pfitzseb** [comment]
I've had that bug too, but I'm reasonably sure it got fixed by a new Atom release. On what version are you (works fine for me on 1.19 and 1.20)?

**Comment by marius311** [comment]
Ah forgot to mention, I'm on Atom 0.19.3, so its not just that I guess.

**Comment by marius311** [comment]
Just tried 0.19.5 and 0.20.0 neither of which seem to fix it.

**Comment by pfitzseb** [comment]
Seems like I fixed that bug somewhere then, so it should be fine in the next release :)

**Comment by marius311** [comment]
Could you let me know which package I need to update to master to get the fix?

**Comment by pfitzseb** [comment]
Not right now, no (I can check on the evening though). It might not even be fixed on master, but I do know it's fixed on the `sp/docpane` branches.

**Comment by pfitzseb** [comment]
Okay, found the fix: https://github.com/JunoLab/atom-ink/commit/6188351a0fa220c170405b16bfec42374fe6915e.
Getting on ink master should solve the bug therefore.
