### ISSUE TITLE
Documentation browser issue

### ISSUE THREAD

**Issue by jorkku** [JunoLab/atom-julia-client#381]
After opening the documentation browser and searching for anything I get the following error
`UndefVarError: searchdocs not defined`.

I'm using Julia 0.6 and Atom 1.20.1 with the latest packages (uber-juno).

**Comment by pfitzseb** [comment]
Try `Pkg.update()` -- it seems like Atom.jl is outdated.

**Comment by jorkku** [comment]
I did `Pkg.update()` and after it the Atom.jl version I got was `"Atom" → v"0.6.1"`. However I'm still getting the same error. 

I looked at https://pkg.julialang.org/ to check that the newest version is 0.6.2. I wonder if there is some another package blocking me from upgrading to it?

**Comment by pfitzseb** [comment]
Hm, probably. You could try backing up your `~/.julia/v0.6` and installing the relevant packages again (easiest way is to keep `~/.julia/v0.6/REQUIRE` and run `Pkg.update()).

**Comment by jorkku** [comment]
Yes, that solved the issue. Thank you.
