### ISSUE TITLE
Include language server integration

### ISSUE THREAD

**Issue by aterenin** [JunoLab/atom-julia-client#382]
http://langserver.org

In the most recent version, Atom now has language server support using the `atom-ide` package.
https://nuclide.io/blog/2017/09/12/Introducing-Atom-IDE-UI/

There's a Julia package that implements the protocol.
https://github.com/JuliaEditorSupport/LanguageServer.jl

I suggest adding support for this to Juno.

**Comment by pfitzseb** [comment]
Have a look at https://github.com/pfitzseb/atom-julia-lsp-client for some (very) experimental first steps.
Proper integration of the language server into Juno is on our roadmap, but not a priority right now.

**Comment by aterenin** [comment]
Thanks, that package works _fantastically_ well. You should publish it to the Atom package repository!

The only problem is latest version of Juno breaks it. Latest version appears to register a hyperclick provider among other things, which seems to prevent it from loading. I had to downgrade to 0.5.14 to make it work.

Is there any workaround with later versions?
