### ISSUE TITLE
[Feature Request] String path auto-completion 

### ISSUE THREAD

**Issue by kescobo** [JunoLab/atom-julia-client#383]
Currently, path auto-completion works for certain functions (eg `open()` and `include()` but not for other functions that take paths (eg `readtable()` in the `DataFrames` package.

It would be great to have generic completion for path-like strings. See for example [this atom package](https://github.com/atom-community/autocomplete-paths). 

As a bonus, if possible it would be great if this worked with string interpolation as well. Eg:

```julia
rootpath = expanduser("~/Desktop")
readtable("$rootpath/<completion here>
```

see also [gitter discussion](https://gitter.im/JunoLab/Juno?at=59de29eb01110b7231a24936)

**Comment by ssfrr** [comment]
hah, I've noticed many times that I don't get the same path completion in Atom as the REPL, but I didn't know that it does exist for `open` and friends (I'm often passing paths to other functions). I think it would be great to emulate the REPL's behavior here.

Maybe one way to limit how much disk access it needs to do (If that's a concern) is to only autocomplete paths that start with `/` or any of the file/directory names in `pwd()`, so you can still complete relative paths.
