### ISSUE TITLE
specific keymaps to julia-runtime console

### ISSUE THREAD

**Issue by yelled1** [JunoLab/atom-julia-client#387]
Hi:

I am trying to mimic my usual gvim/nya vim usage. What I am trying to do is jump with ‘ctrl-`’ key to go back & forth between the editor & repl(console?) panes. So, I attempted:
```
'.editor':
    'ctrl-`': 'window:focus-pane-below'

#'.ink-console':
#'juno.runtime.console':
#'juno.runtime':
'console':
    'ctrl-`': 'window:focus-pane-above'
2 problems:
```
I cannot get back to editor from repl
I really do not want to focus-pane-above or below, but rather focus on the repl or julia editor, as Plots pane is open often.
can someone tell me what : ‘console’ above should be replaced with?
I read threads on this but seems like a oneway trip to console.
Also, is there a way to put conditionals into keymaps? (Sorry new to Atom)
If julia-console is open then just move down/up, else open a new session.
If plot pane is open then close with Ctrl-j Ctrl-p
This is like "ctrl-\\" which closes/opens tree view with tree-view:toggle
currently "ctrl-j ctrl-p" does julia-client:open-plot-pane. but  julia-client:toggle-plot-pane would be better

Thanks much,!

**Comment by yelled1** [comment]
Actually this works!
`'atom-text-editor[data-grammar="source julia"]':
    'ctrl-\`': 'window:focus-pane-below'
'.julia-console.julia atom-text-editor':
    'ctrl-`': 'window:focus-pane-above'
`

**Comment by ajkeith** [comment]
Is there an alternate way to do this for atom 1.32 and julia-client 0.7? As far as I can tell, I should replace 'atom-text-editor' with '.editor'. That works for the focus changing outside of the repl, but I still get my focus stuck in the repl with either syntax. I also tried single and double backticks but no luck. (I have a left-right editor-repl setup). 

```
'.julia-console.julia .editor':
  'ctrl-``': 'window:focus-pane-on-left'
```

**Comment by pfitzseb** [comment]
You need to add those keybindings to `julia-client`s whitelisted keybindings (with some limitations, see e.g. https://github.com/JunoLab/Juno.jl/issues/258).

**Comment by ajkeith** [comment]
Great, thanks! That worked perfectly.
