### ISSUE TITLE
Better handling of very wide line bubbles

### ISSUE THREAD

**Issue by jebej** [JunoLab/atom-julia-client#391]
Exemplified here with the stepper:

Bubbles are usually aligned next to the related code:
![image](https://user-images.githubusercontent.com/11141558/32752520-7b366ec8-c897-11e7-91e8-dcc87a43292a.png)

but when the bubble is too wide, only the center portion is kept visible:
![image](https://user-images.githubusercontent.com/11141558/32752489-5aed1108-c897-11e7-9364-aa374ee91588.png)

It would be more useful to have the bubble be left aligned so that the left edge would always be visible (that shows the name of the function with the stepper).

**Comment by jebej** [comment]
I realized that this might be better in the atom-ink repo, tell me if that's the case.

**Comment by pfitzseb** [comment]
New behaviour:
![grafik](https://user-images.githubusercontent.com/6735977/32782928-507a709a-c94a-11e7-9d42-b5b9f7ecf925.png)

Still a bit ugly, but much better than before.
