### ISSUE TITLE
Debug slider doesn't move in Juno after clicking on next line button

### ISSUE THREAD

**Issue by bmharsha** [JunoLab/atom-julia-client#392]
This issue occurs on all platforms: Linux, Mac and Windows, 

As shown in below screenshots, the debug slider doesn't move after clicking on "Next Line" button, even though the "Step into" function is happening in background, you can observe the values of variables are changing in the work-space but the slider is fixed on the beginning of the function. 

![image](https://user-images.githubusercontent.com/5441491/32889681-dfbb9b64-caf1-11e7-896e-0917b404e2a8.png)

Following screenshot has executed the first line of code in `function asd` , variable values in the workspace have changed 
![image](https://user-images.githubusercontent.com/5441491/32889805-47a11ed4-caf2-11e7-8c1a-ccadeb7c476c.png)

Following screenshot has executed the second line of code in `function asd`
![image](https://user-images.githubusercontent.com/5441491/32889721-1523baca-caf2-11e7-9b9a-4cb86c2caf58.png)

### Configuration
Julia version 0.6.1, Julia side package versions are shown below
```
ASTInterpreter 0.0.4
ASTInterpreter2 0.1.0 
Atom 0.6.5
Juno 0.3.2
```
Atom version = 1.22.1
Atom package versions are shown below
```
tool-bar@1.1.0
default-language@0.3.0
latex-completions@0.3.3
language-julia@0.13.0
ink@0.7.9
julia-client@0.6.6
autoupdate-packages@1.3.1
project-manager@3.3.5
teletype@0.1.2
```

**Comment by pfitzseb** [comment]
Yeah there's still some problems with untitled editors -- try saving it somewhere for now. :)
