### ISSUE TITLE
Syntax highlighting problems macOS

### ISSUE THREAD

**Issue by wgreenr** [JunoLab/atom-julia-client#396]
With Juno/Julia 0.6/macOS latest, I experience the following:
<img width="315" alt="screen shot 2017-11-24 at 8 21 08 pm" src="https://user-images.githubusercontent.com/3976771/33228518-2b0f65d4-d1c6-11e7-8beb-cf876fa576c0.png">
<img width="127" alt="screen shot 2017-11-24 at 8 23 18 pm" src="https://user-images.githubusercontent.com/3976771/33228519-2e1c41de-d1c6-11e7-8c98-8cc5ffdf1472.png">
As one can see, in the first case, more than 3 levels of `{}` nesting leads to disappearance of highlighting, and in the second, the `in` keyword is not highlighted.
This is a copy of https://discourse.julialang.org/t/syntax-highlighting-problems-in-juno/7295

**Comment by pfitzseb** [comment]
Yeah, the type nesting case is an actual issue (see the one referenced above in `language-julia`); `in` highlighting has been changed a while ago to `operator` instead of `keyword` highlighting, which seems more correct to me. Your syntax theme doesn't have any special highlighting for `operator`s though.

**Comment by wgreenr** [comment]
@pfitzseb which syntax theme supports `operator` or how can I adjust this manually, could you please point me?
Really have no experience with this, I've tried several themes to no avail.

**Comment by pfitzseb** [comment]
You can put something like
```
@import "syntax-variables";
.syntax--julia .syntax--operator {
  color: @syntax-color-tag;
}
```
into your `styles.less` (just open the command pane and search for `Open Your Stylesheet`). It's currently not possible to *only* color `in` though.

`∈` is currently not correctly tokenized correctly though, but that's a seperate issue.

**Comment by wgreenr** [comment]
@pfitzseb thank you very much, it worked! Where can I check other available syntax classes `.syntax--*`, except for `.syntax--operator`?
I've tried `.syntax--julia .syntax--struct` or `.syntax--julia .syntax--class` to color differently `struct` name definitions, but without any luck.

**Comment by pfitzseb** [comment]
You can open the dev tools (`Cmd-Shift-I`, I think?) and inspect the css classes for whatever you're interested in. For `struct` you'll get `class="syntax--keyword syntax--other syntax--julia"`, but usually those aren't super specific to the different keywords.
