### ISSUE TITLE
macOS High Sierra 10.13.1 and atom-julia-client

### ISSUE THREAD

**Issue by luisjavierhernandez** [JunoLab/atom-julia-client#397]
Hi!
My  laptop atom is not able to 
connect to Julia.

In  Setting of julia-client I have writen 
/Applications/Julia-0.7.app/Contents/Resources/Julia/bin
but Julia does not start.
I will thank some help with this problem.
Best wishes
Luis Javier

Notes: 

The terminal gives the following answer: 

UndefVarError: find_in_path not defined
Stacktrace:
 [1] 
top-level scope at /Users/luhernan/.atom/packages/julia-client/script/boot.jl:3
 [2] include_relative(::Module, ::String) at ./loading.jl:509
 [3] include(::Module, ::String) at ./sysimg.jl:15
 [4] process_options(::Base.JLOptions) at ./client.jl:340
 [5] _start() at ./client.jl:406
in expression starting at /Users/luhernan/.atom/packages/julia-client/script/boot.jl:3

Atom gives the following message

We tried to launch Julia from:
/Applications/Julia-0.7.app/Contents/Resources/julia/bin
This path can be changed in the settings.
Details:
  /bin/sh: /Applications/Julia-0.7.app/Contents/Resources/julia/bin: is a directory

I have checked the PATH and I have

sh-3.2$ echo $PATH
/Applications/Julia-0.7.app/Contents/Resources/julia/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin

**Comment by pfitzseb** [comment]
Julia 0.7 isn't supported yet.

**Comment by luisjavierhernandez** [comment]
Thank you very much to pfitzseb.
I am going to install Julia 0.6.
Best wishes
Luis Javier
