### ISSUE TITLE
julia start-up is horribly slow in Atom

### ISSUE THREAD

**Issue by stakaz** [JunoLab/atom-julia-client#399]
Hello, since about one month or so I the start-up of julia REPL in Atom became very slow and CPU extensive.
I.e., this program:
```
println("test")
```
runs in less than a second with `julia -O3 -- test.jl` but takes about 20 seconds in atom to print the result to console.
It is even worse for every program with some using statements.
This also happens to older code which started much faster in the past.

Can you give me a hint where to search for the core of the problem? I have the most recent versions:
```
atom: 1.22.1 (64 bit, every package updated)
julia: 0.6.1 (2017-10-24 22:15 UTC)
```

**Comment by stakaz** [comment]
I have just tested. only press "Start Julia" gives me

```
Julia Boot: 42.23s          .atom/packages/julia-client/lib/misc.coffee:44
```

This is incredibly long and definitely was not the case about one month ago.

**Comment by pfitzseb** [comment]
That seems excessive, and I haven't seen boot times that long yet. I will definitely look into improving boot times though.

**Comment by stakaz** [comment]
Thanks, meanwhile, have you an idea of what I can test in order to get closer to the core of the problem?

**Comment by stakaz** [comment]
I have just tested with a new .atom directory and the only thing I have added to initial atom is the uber-juno package which installed me everything needed for julia.

The result is sadly the same: 40 seconds to start julia...

**Comment by pfitzseb** [comment]
Yes, all/most of the reported time is spend loading and connecting to Julia.
Just for reference, I usually get something like `Julia Boot: 8.02s`, which doesn't seem that bad if you consider
```
julia> @time using Atom
  5.140905 seconds (4.15 M allocations: 235.254 MiB, 4.34% gc time)
```

**Comment by stakaz** [comment]
No, this is just starting the REPL. With the new version however, it get much better.

**Comment by stakaz** [comment]
The start-up time is now again around 30 seconds vs. 1 second in terminal.

**Comment by stakaz** [comment]
Here is what happens when I start julia in terminal:

```julia
gluon:~ $ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> @time using Atom
 35.649488 seconds (6.30 M allocations: 360.687 MiB, 2.17% gc time)
```

**Comment by pfitzseb** [comment]
Hm, I've seen a bit of a regression here to, but nothing as massive. Will take a look soon.
