### ISSUE TITLE
Atom v1.0.15 keeps freezing/crashing on Windows 10 

### ISSUE THREAD

**Issue by SergeUK** [JunoLab/atom-julia-client#40]
Hi,

I am new to Atom and I just started to use it with Julia (packages language-julia, julia-client, ink). I have the version 1.0.15 installed on Windows 10. It runs fine a while but it keeps crashing when I run my Julia code always at the same place. I don't know if it is an issue with the packages or with Atom. How can I find out what causes the crash / freeze?

Thanks
Serge

**Comment by ssfrr** [comment]
Can you give a little more detail about what causes the crash and what symptom's you're seeing? It sounds reproducible which is a promising start.

Are you seeing any error messages? One thing that can be helpful is to have the Julia console open while you're evaluating code to see if there's any information there.

**Comment by nilshg** [comment]
Have you tried running the code in the REPL? That should always be the first thing to try if you're unsure whether Julia or the editor is crashing. 
On 21 Sep 2015 5:20 am, Spencer Russell <notifications@github.com> wrote:Can you give a little more detail about what causes the crash and what symptom's you're seeing? It sounds reproducible which is a promising start.

Are you seeing any error messages? One thing that can be helpful is to have the Julia console open while you're evaluating code to see if there's any information there.

**Comment by SergeUK** [comment]
The code runs perfectly fine in Juno, so that does not seem to be the issue. Thanks

**Comment by Varanas** [comment]
Is there some kind of large vector output or somerthing like that where you are experiencing the crash? Can you share (part of) the code?

Also, if you're feeling a bit adventurous, you can try following the [developer install instructions](https://github.com/JunoLab/atom-julia-client/blob/master/docs/README.md) -- there is at least a chance that the bug you're experiencing might already be fixed on master but not on the latest tagged release.

**Comment by SergeUK** [comment]
I can share the julia code, but it does not seem to be the issue here as it is running perfectly well on Juno/REP. 

 

The problem arises when I run a function of mine. It generates an warning message (WARNING: [a] concatenation is deprecated; use collect(a)). I just spotted that that console is filling rapidly with messages (probably one for each iteration of the loops within the function). First I get a message from windows saying: “Editor not responding. The editor is not responding. Would you like to force close it or just keep waiting?”.   Then, while my CPU is quite busy and churning, the console freezes at some stage. Eventually I get an message saying: “ The editor has crashed. Please report the issue to https://github/atom/atom” and it asks me to either close the window, reload or keep it open. 

 

It always happen when I run this particular function of mine, which runs perfectly fine in Juno.

**Comment by Varanas** [comment]
The code isn't the issue, true, but the output is.
Something like 
```julia
while true
    println(2)
end
```
reproduces your problem (after some time). 
This obviously is an issue with the console -- deleting old output after a certain number of lines has been rendered seems sensible to me.

**Comment by SergeUK** [comment]
Agreed. In my example, I cannot control the amount of output if I am running loops and there are warnings for each iteration.

Another potential issue is that the output on the console probably slows down Atom. 

Shall I notify somebody about that or are you the person to talk to in that instance?

**Comment by Varanas** [comment]
I'll have a look, but I don't have all that much time until this evening, so cc @one-more-minute.

**Comment by SergeUK** [comment]
I don’t really know how this works. I’d prefer if you do it. There is no urgency. Thanks

**Comment by ssfrr** [comment]
So aside from limiting the history size of the console (which I agree seems reasonable), the other issue here is that your code (or some code your code is calling) is using deprecated syntax. It's a good idea to fix the issue that's causing the warnings to be printed.

One trigger for this warning is if you have code like `[1:3]`, which should be turned into `collect(1:3)` instead. Interesting you're not seeing it in Juno. Are you using an older Julia version with that?

**Comment by SergeUK** [comment]
I am using v0.3.11 on Juno simply because it is the stable version. Deprecation is not an issue there. 

 

I will modify the code to turn [a:b] into collect(a,b). Thanks for that.

**Comment by one-more-minute** [comment]
The console should be able to take a bit more pushing now, although there's still some low-hanging fruit for optimising it.
