### ISSUE TITLE
Interaction between run-file and run-block has been broken

### ISSUE THREAD

**Issue by jamii** [JunoLab/atom-julia-client#400]
To replicate, open:

``` julia
module Example

@show fullname(current_module())

end
```

And run this sequence of commands:

```
run-file
run-block
run-file
run-block
```

Produces:

```
fullname(current_module()) = (:Example,)
fullname(current_module()) = (:Example,)
WARNING: replacing module Example
fullname(current_module()) = (:Example, :Example)
fullname(current_module()) = (:Example,)
```

Now run-file evaluate Example.Example and run-block evaluates in Example, so they can't be used together in the same workflow.

```
julia-client 0.6.6
language-julia 0.13.0

Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)

 - Atom                          0.6.5
 - CodeTools                     0.4.7
 - Juno                          0.3.2
```

**Comment by pfitzseb** [comment]
Dup of #398.

Basically, `run-file` is sensitive to the cursor position as well, which means that you can get the correct behaviour by placing the cursor on the last line when executing `run-file`.

**Comment by pfitzseb** [comment]
Alright, fixed. Turns out I broke this while refactoring a while back :)

**Comment by jamii** [comment]
Wow, I was still halfway through writing a workaround command to jump to the end of the file and back :D
