### ISSUE TITLE
Swap copy/interrupt keybindings on windows/linux

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/atom-julia-client#403]
Intercept Ctrl-C & Ctrl-Shift-C via the custom keyhandler on the xterm.js level and switch them around. Then:

| keybinding   | editor    | Juno REPL | standalone REPL |
|--------------|-----------|-----------|-----------------|
| Ctrl-C       | copy      | copy      | interrupt       |
| Ctrl-Shift-C | interrupt | interrupt | copy (windows)  |
| Ctrl-V       | paste     | paste     | paste (windows) |

**Comment by MikeInnes** [comment]
On Mac at least, this shouldn't matter (Cmd-C is copy so Ctrl-C is free for interrupt everywhere).

I'm a little ambivalent about this for Winux, but it's probably more important to be internally consistent than to match the normal terminal's behaviour.
