### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by JBAhire** [JunoLab/atom-julia-client#408]
Argument to `path.dirname` must be a string
```
Object.dirname (C:\Users\Asus\AppData\Local\JuliaPro-0.6.2.1\app-1.22.1\resources\app.asar\src\electron-shims.js:9:10)
Object.cdHere (C:\Users\Asus\AppData\Local\JuliaPro-0.6.2.1\.atom\packages\julia-client\lib\runtime\evaluation.coffee:235:22)
<unknown> (C:\Users\Asus\AppData\Local\JuliaPro-0.6.2.1\.atom\packages\julia-client\lib\package\commands.coffee:276:44)
Object.require (C:\Users\Asus\AppData\Local\JuliaPro-0.6.2.1\.atom\packages\julia-client\lib\connection\client.coffee:220:43)
requireClient (C:\Users\Asus\AppData\Local\JuliaPro-0.6.2.1\.atom\packages\julia-client\lib\package\commands.coffee:14:39)
HTMLElement.julia-client:work-in-file-folder (C:\Users\Asus\AppData\Local\JuliaPro-0.6.2.1\.atom\packages\julia-client\lib\package\commands.coffee:275:18)
```

**Comment by jzazo** [comment]
Same message appeared today.
```
Argument to path.dirname must be a string

Object.dirname - /usr/share/atom/resources/app.asar/src/electron-shims.js:9:10
Object.cdHere - /home/javier/.atom/packages/julia-client/lib/runtime/evaluation.coffee:221:28
<unknown> - /home/javier/.atom/packages/julia-client/lib/package/commands.coffee:297:44
Object.require - /home/javier/.atom/packages/julia-client/lib/connection/client.coffee:279:43
requireClient - /home/javier/.atom/packages/julia-client/lib/package/commands.coffee:14:39
HTMLElement.julia-client:work-in-file-folder - /home/javier/.atom/packages/julia-client/lib/package/commands.coffee:296:18
```

**Comment by HelgavonLichtenstein** [comment]
Hello, the same depreciation message appeared today. I have the latest Atom and am using Julia 1.4.2.
```
Argument to path.dirname must be a string

Object.dirname - C:\Users\Helga\AppData\Local\atom\app-1.47.0\resources\app.asar\src\electron-shims.js:9:10
Goto.getJumpFilePath - C:\Users\Helga\.atom\packages\julia-client\lib\runtime\goto.js:85:39
Object.<anonymous> - C:\Users\Helga\.atom\packages\julia-client\lib\runtime\goto.js:198:36
Generator.next - null:null:null
step - C:\Users\Helga\.atom\packages\julia-client\lib\runtime\goto.js:9:273
<unknown> - C:\Users\Helga\.atom\packages\julia-client\lib\runtime\goto.js:9:443
```

**Comment by wizebt** [comment]
Hi, Same issue appeard today Atom 1.53.0 x64 Julia 
`julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4940MX CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_EDITOR = atom  -a`
`Object.dirname - /usr/share/atom/resources/app.asar/src/electron-shims.js:9:10
formatEditorTextInRange - /home/manu/.atom/packages/julia-client/lib/runtime/formatter.js:47:31
formatEditorWithSelection - /home/manu/.atom/packages/julia-client/lib/runtime/formatter.js:43:10
<unknown> - /home/manu/.atom/packages/julia-client/lib/runtime/formatter.js:31:7
Array.forEach - null:null:null
Object.formatCode - /home/manu/.atom/packages/julia-client/lib/runtime/formatter.js:30:16`

**Comment by DBNJ** [comment]
Same issue appeared today. Atom 1.50 and Julia 1.6.

Argument to path.dirname must be a string

Object.dirname - /Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10
Goto.getJumpFilePath - /Users/dbhatia/.atom/packages/julia-client/lib/runtime/goto.js:85:39
Object.<anonymous> - /Users/dbhatia/.atom/packages/julia-client/lib/runtime/goto.js:198:36
Generator.next - null:null:null
step - /Users/dbhatia/.atom/packages/julia-client/lib/runtime/goto.js:9:273
<unknown> - /Users/dbhatia/.atom/packages/julia-client/lib/runtime/goto.js:9:443
