### ISSUE TITLE
[Feature request] Auto-completion of `end`

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JunoLab/atom-julia-client#411]
I would greatly appreciate, if Juno would automatically insert an indented line and the `end` keyword and places the cursor at the indent, whenever you hit `enter` at the end of line that began with the use of  `function`, `if`, etc.

**Comment by pfitzseb** [comment]
This should be handled with snippets, so closing in favour of https://github.com/JuliaEditorSupport/atom-language-julia/issues/138.
