### ISSUE TITLE
Uncaught Error: Pane items must be objects. Attempted to add item undefined.

### ISSUE THREAD

**Issue by hearnsj** [JunoLab/atom-julia-client#414]
[Enter steps to reproduce:]

1. Install Atom Beta 1.24.0-beta3  
2. Windows 10 Home OS
3. Julia 0.6.2 is already installed

At install time there is an error window 

**Atom**: 1.24.0-beta3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.6.7

### Stack Trace

Uncaught Error: Pane items must be objects. Attempted to add item undefined.

```
At C:\Users\hearn\AppData\Local\atom\app-1.24.0-beta3\resources\app\src\pane.js:604

Error: Pane items must be objects. Attempted to add item undefined.
    at Pane.addItem (~/AppData/Local/atom/app-1.24.0-beta3/resources/app/src/pane.js:604:19)
    at createDockLayout (/packages/julia-client/lib/ui/layout.js:21:20)
    at standard (/packages/julia-client/lib/ui/layout.js:62:3)
    at NotificationElement.onDidClick (/packages/julia-client/lib/ui/layout.js:6:7)
    at HTMLAnchorElement.<anonymous> (~/AppData/Local/atom/app-1.24.0-beta3/resources/app/node_modules/notifications/lib/notification-element.js:139:48)
```

### Commands

```
     -2:05.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
antialiased 0.1.0 
atom-ide-ui 0.7.0 
atom-julia-run 1.0.5 
ide-python 0.3.0 
indent-detective 0.1.1 
ink 0.7.11 
julia-client 0.6.7 
language-julia 0.14.0 
latex-completions 0.3.3 
tool-bar 1.1.0 
uber-juno 0.1.2 
```

**Comment by hearnsj** [comment]
![capture](https://user-images.githubusercontent.com/19259589/35481047-03e615d8-041c-11e8-87d7-0ce487a91a68.PNG)

Screen capture file

**Comment by pfitzseb** [comment]
Pretty sure that happens because you're running Atom 1.24; will take a loock asap.

**Comment by pfitzseb** [comment]
Ah, nvm. You're still on an old `ink` release -- please update to 0.8.1!

**Comment by hearnsj** [comment]
@pfitzseb Thankyou. I upgraded ink and the issu eis fixed
