### ISSUE TITLE
Include "end" as keyword

### ISSUE THREAD

**Issue by davidavdav** [JunoLab/atom-julia-client#416]
Hello, 

every time I type "end", quite a common keyword in Julia, and I type \<tab> to un-indent in Atom, it turns into "encode" because autocomplete doesn't know about "end". 

Could you please add "end" as a list of keywords for autocompletion?

**Comment by pfitzseb** [comment]
Can't reproduce that:
![endcompletion](https://user-images.githubusercontent.com/6735977/35561513-d3830aa4-05b0-11e8-9e9a-bfc7618be4c4.png)

**Comment by davidavdav** [comment]
I can't get rid of it, though.  Is there anything I can do to reload/reset/whatever the settings/tables/whatever is involved?

Thanks

---david

<img width="690" alt="screen shot 2018-01-31 at 09 32 12" src="https://user-images.githubusercontent.com/5497303/35612639-bf406bc2-0669-11e8-93e8-2ab3c9b6510a.png">

**Comment by pfitzseb** [comment]
Hm, I'd expect the completiopns you get there only when Julia _isn't_ running. Is that the case?

**Comment by davidavdav** [comment]
That is correct, I never run Julia inside atom.  

(The first things that IDEs invariably do, is hijack the up/down arrows.  These are the most useful keys in a REPL, IMHO.)

But yes, I now see that if I start Julia inside Atom, completions include "end".  

Is there a way that Julia will automatically start in the background whenever I edit a .jl file?

**Comment by pfitzseb** [comment]
If you switch the Boot Mode to "Cycler" Julia will silently start in the background -- you'll still have to manually connect by trying to evaluate anything (either in the REPL or in an editor or in the docpace or anywhere else).
