### ISSUE TITLE
running `@enter` from REPL and clicking right-most button leaves REPL in `debug>` state

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-julia-client#418]
MWE (executed from the console):

```julia
julia> foo(x) = x*2
foo (generic function with 1 method)

julia> @enter foo(3)
```

Then press the right-most button on the debugger panel. You'll see the REPL now with the `debug>` prompt

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/Atom.jl/commit/a0de71cd2a2010703d2c06f11e23254f29e9640e.
