### ISSUE TITLE
Juila Console fails to load in Atom due to LoadError

### ISSUE THREAD

**Issue by MS07112** [JunoLab/atom-julia-client#420]
I have installed Atom, Juno, uber-juno, and all of the corresponding Julia packages. But whenever I try to start the Julia Console from within Atom, I get the error message:

`ERROR: LoadError: error compiling anonymous: unsupported or misplaced expression "import" in function anonymous
while loading /home/mike/.atom/packages/julia-client/script/boot_repl.jl, in expression starting on line 1
Julia has exited. Press Enter to start a new session.`

![screenshot_2018-02-04_08-01-57](https://user-images.githubusercontent.com/13173456/35777800-1f3af702-0982-11e8-9b27-adce5105f093.png)

In the 'boot_repl.jl' file: Line 32 mentions a non-existent '.junorc.jl' file in the home directory; I'm not sure if this is the cause or what exactly. Please let me know if you have any hints. 

Thank you.

**Comment by pfitzseb** [comment]
Are you on old Julia version? Juno *only* supports Julia 0.6.

**Comment by MS07112** [comment]
I just installed the newest version of Julia from the official site. Everything works fine now. 

Before I was using the latest version available on the Debian repository (version 0.4.7).

Thanks!

**Comment by pfitzseb** [comment]
Awesome, glad you got it working now! :)
