### ISSUE TITLE
Evaluating functions stops at comment block

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JunoLab/atom-julia-client#421]
Here is a MWE:
```julia
function mwe()
    a = 0
    #= hello =#
end
```
Hitting `cmd+enter` at the line with `a = 0` yields an error about missing `end`.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-julia-client/commit/35918a6733d15ee542a936362db911140c003254.
