### ISSUE TITLE
Juno.render no longer works from the editor

### ISSUE THREAD

**Issue by jamii** [JunoLab/atom-julia-client#423]
If I type `Juno.render([1,2,3])` in an editor and eval with ctrl+enter, nothing happens. Previously it would render `[1,2,3]` nicely in the console.

Perhaps this feature died in the change to the new console, but it's still in the [docs](http://docs.junolab.org/latest/man/basic_usage.html#Enhanced-Rendering-1).

Julia 0.6.2, Juno 0.4.0, Atom 0.6.9
Atom 1.23.3, julia-client 0.6.8

**Comment by pfitzseb** [comment]
Right, that's a docs issue.

**Comment by MikeInnes** [comment]
This should still work. I'm guessing it's still hooked up to the old console? We can just remove that and let it fall back to the repl.

**Comment by pfitzseb** [comment]
Well, one argument `render` uses `Console()` as the default display IIRC. So we could either pipe those calls back to the base display system or make `Editor()` the default display (which would be pretty useless).

**Comment by MikeInnes** [comment]
We explicitly tell render to use the console as the generic fallback [here](https://github.com/JunoLab/Atom.jl/blob/888e68f3c3e230aebcc4edf1aae2c1bb0a4ec2de/src/display/display.jl#L13), so it should just be a case of removing that. Just doing `Media.unsetdisplay(Juno.Editor(), Any)` fixes this for me.

**Comment by pfitzseb** [comment]
Fixed: https://github.com/JunoLab/Atom.jl/commit/0697e594daacb15e99dfe438b1ce89278b4f1b09.
