### ISSUE TITLE
Overeager module search

### ISSUE THREAD

**Issue by jamii** [JunoLab/atom-julia-client#424]
Juno thinks that the bottom half of this code is in module `file`. 

``` julia
function show_for_analyze(method_instance::MethodInstance)
  original = string(method_instance)
  shortened = replace(original, "MethodInstance for ", "")
  mod = method_instance.def.module
  file = method_instance.def.file
  line = method_instance.def.line
  "$shortened in $module at $file:$line"
end
```

Similarly, this is in module `bar`:

``` julia
sym = :module
bar = 1
```

Maybe amend the regex so that `module` can't be preceded by a dot or colon? I can't think of any other legal syntax that would include module.

**Comment by pfitzseb** [comment]
The module detection part of this is fixed with https://github.com/JunoLab/CodeTools.jl/commit/835b10ba557b7ed045d6828ea06b12754939adb4, the syntax highlighting bug is fixed with https://github.com/JuliaEditorSupport/atom-language-julia/commit/9fafea41b210eddb434fc339deb6506b9eab0943.

**Comment by jamii** [comment]
❤️
