### ISSUE TITLE
Problem with Pkg.add("Atom")

### ISSUE THREAD

**Issue by jchen1992** [JunoLab/atom-julia-client#425]
Hello Guys, I'm trying learning Julia, and try to use Atom+Juno, but I got stucked, when I typed  Pkg.add("Atom"), it gives me this:
julia> Pkg.add("Atom")
INFO: Installing ASTInterpreter2 v0.1.1
INFO: Installing Atom v0.6.9
INFO: Installing BinDeps v0.8.6
INFO: Installing Blink v0.6.1
INFO: Installing CodeTools v0.4.7
INFO: Installing Codecs v0.4.0
INFO: Installing Compat v0.53.0
INFO: Installing DebuggerFramework v0.1.2
INFO: Installing Distances v0.5.0
INFO: Installing DocSeeker v0.1.0
INFO: Installing Hiccup v0.1.1
INFO: Installing HttpCommon v0.4.0
INFO: Installing HttpParser v0.3.1
INFO: Installing HttpServer v0.3.0
INFO: Installing IterTools v0.2.1
INFO: Installing JSON v0.16.4
INFO: Installing Juno v0.4.0
INFO: Installing LNR v0.0.2
INFO: Installing Lazy v0.12.0
INFO: Installing MacroTools v0.4.0
INFO: Installing MbedTLS v0.5.5
INFO: Installing Media v0.3.0
INFO: Installing Mustache v0.3.0
INFO: Installing Mux v0.2.3
INFO: Installing Nullables v0.0.3
INFO: Installing Reexport v0.1.0
INFO: Installing Requires v0.4.3
INFO: Installing SHA v0.5.6
INFO: Installing StringDistances v0.2.0
INFO: Installing Tokenize v0.4.2
INFO: Installing URIParser v0.3.0
INFO: Installing WebSockets v0.4.0
INFO: Building HttpParser

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ff8f09144a1 -- RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
while loading C:\Users\thech\.julia\v0.6\BinDeps\src\dependencies.jl, in expression starting on line 113
RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
realloc at C:\WINDOWS\System32\msvcrt.dll (unknown line)
_buf_realloc at /home/Administrator/buildbot/worker/package_win64/build/src/support\ios.c:202 [inlined]
_write_grow at /home/Administrator/buildbot/worker/package_win64/build/src/support\ios.c:237 [inlined]
ios_write at /home/Administrator/buildbot/worker/package_win64/build/src/support\ios.c:402
jl_compress_ast at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\dump.c:2789

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ff8f09144a1 -- RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
while loading C:\Users\thech\.julia\v0.6\BinDeps\src\dependencies.jl, in expression starting on line 113
RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
realloc at C:\WINDOWS\System32\msvcrt.dll (unknown line)
ZN4llvm15SmallVectorBase8grow_podEPvyy at D:\Julia-0.6.2\bin\LLVM.dll (unknown line)
ZN4llvm3sys4path6appendERNS_15SmallVectorImplIcEERKNS_5TwineES7_S7_S7_ at D:\Julia-0.6.2\bin\LLVM.dll (unknown line)
ZNK4llvm26DWARFDebugInfoEntryMinimal28collectChildrenAddressRangesEPKNS_9DWARFUnitERSt6vectorISt4pairIyyESaIS6_EE at D:\Julia-0.6.2\bin\LLVM.dll (unknown line)
=================================================[ ERROR: HttpParser ]==================================================

LoadError: Failed to precompile BinDeps to C:\Users\thech\.julia\lib\v0.6\BinDeps.ji.
while loading C:\Users\thech\.julia\v0.6\HttpParser\deps\build.jl, in expression starting on line 1

========================================================================================================================
INFO: Building MbedTLS
Using system libraries...

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ff8f09196aa --
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ff8f09196aa --
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ff8f09196aa -- RtlAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
while loading no file, in expression starting on line 0
RtlAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
malloc at C:\WINDOWS\System32\msvcrt.dll (unknown line)
===================================================[ ERROR: MbedTLS ]===================================================

LoadError: Failed to precompile BinDeps to C:\Users\thech\.julia\lib\v0.6\BinDeps.ji.
while loading C:\Users\thech\.julia\v0.6\MbedTLS\deps\build.jl, in expression starting on line 45

========================================================================================================================
INFO: Building Blink

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ff8f09196aa -- RtlAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
while loading C:\Users\thech\.julia\v0.6\BinDeps\src\dependencies.jl, in expression starting on line 109
RtlAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
malloc at C:\WINDOWS\System32\msvcrt.dll (unknown line)
====================================================[ ERROR: Blink ]====================================================

LoadError: LoadError: Failed to precompile BinDeps to C:\Users\thech\.julia\lib\v0.6\BinDeps.ji.
while loading C:\Users\thech\.julia\v0.6\Blink\deps\../src/AtomShell/install.jl, in expression starting on line 1
while loading C:\Users\thech\.julia\v0.6\Blink\deps\build.jl, in expression starting on line 4

========================================================================================================================

====================================================[ BUILD ERRORS ]====================================================

WARNING: HttpParser, Blink and MbedTLS had build errors.

 - packages with build errors remain installed in C:\Users\thech\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("HttpParser", "Blink", "MbedTLS")`
 - build a single package by running its `deps/build.jl` script

Anyone know how to deal with it? 
Thanks a lot.

**Comment by rapus95** [comment]
Maybe not solving the problem itself but if you want a working install go that way:
if you don't have julia and Atom installed already do it, then:
open Atom and install the package "uber-juno" (not sure if with or without '-')
wait until it's finished. Now you've got a working atom-julia interface 👍

you can also read it there:
https://github.com/JunoLab/uber-juno/blob/master/setup.md

**Comment by gwerbin** [comment]
I have the same error. @rapus95 it appears regardless of how you install Juno, since it will try to `Pkg.add("HttpParser")` on first run anyway.

I just posted an issue to https://github.com/JuliaWeb/HttpParser.jl/issues/83
