### ISSUE TITLE
Error: EPERM

### ISSUE THREAD

**Issue by xanfus** [JunoLab/atom-julia-client#426]
```
apm install julia-client

Error: EPERM: operation not permitted, open 'C:\Users\<user>\.atom\packages\julia-client\script\spawnInterruptible.ps1' at Error (native)
```
spawnInterruptible.ps1 is abscent. Is permission to write it abscent?
I can't remove read-only state from script folder.

**Comment by pfitzseb** [comment]
This might be related to an overzealous virus scanner deleting the file or something like that.
Might also be a permission problem -- make sure you install Atom and Juno with the same User.
