### ISSUE TITLE
Error while loading juno on atom for the first time

### ISSUE THREAD

**Issue by inarighas** [JunoLab/atom-julia-client#427]
I installed atom and juno (my julia version is 0.6.2 & my os is ubuntu 17.04) following these instructions http://docs.junolab.org/latest/man/installation.html

and when the IDE starts the REPL, i get a precompiling error of julia concerning the "HttpParser" package: 

> juno-msg-precompilingINFO: Precompiling module Atom.
ERROR: LoadError: HttpParser not properly installed. Please run
Pkg.build("HttpParser")
Stacktrace:
 [1] error(::String, ::String, ::Vararg{String,N} where N) at ./error.jl:30
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] anonymous at ./<missing>:2
while loading /home/osboxes/.julia/v0.6/HttpParser/src/HttpParser.jl, in expression starting on line 9
ERROR: LoadError: LoadError: Failed to precompile HttpParser to /home/osboxes/.julia/lib/v0.6/HttpParser.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] include_from_node1(::String) at ./loading.jl:576
 [7] include(::String) at ./sysimg.jl:14
 [8] anonymous at ./<missing>:2
while loading /home/osboxes/.julia/v0.6/HttpServer/src/RequestParser.jl, in expression starting on line 16
while loading /home/osboxes/.julia/v0.6/HttpServer/src/HttpServer.jl, in expression starting on line 12
ERROR: LoadError: LoadError: Failed to precompile HttpServer to /home/osboxes/.julia/lib/v0.6/HttpServer.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] include_from_node1(::String) at ./loading.jl:576
 [7] include(::String) at ./sysimg.jl:14
 [8] anonymous at ./<missing>:2
while loading /home/osboxes/.julia/v0.6/Mux/src/server.jl, in expression starting on line 1
while loading /home/osboxes/.julia/v0.6/Mux/src/Mux.jl, in expression starting on line 24
ERROR: LoadError: LoadError: Failed to precompile Mux to /home/osboxes/.julia/lib/v0.6/Mux.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] include_from_node1(::String) at ./loading.jl:576
 [7] include(::String) at ./sysimg.jl:14
 [8] anonymous at ./<missing>:2
while loading /home/osboxes/.julia/v0.6/Blink/src/content/content.jl, in expression starting on line 1
while loading /home/osboxes/.julia/v0.6/Blink/src/Blink.jl, in expression starting on line 9
ERROR: LoadError: Failed to precompile Blink to /home/osboxes/.julia/lib/v0.6/Blink.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /home/osboxes/.julia/v0.6/Atom/src/Atom.jl, in expression starting on line 5
juno-msg-loadERROR: LoadError: Failed to precompile Atom to /home/osboxes/.julia/lib/v0.6/Atom.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] process_options(::Base.JLOptions) at ./client.jl:305
 [7] _start() at ./client.jl:371
while loading /home/osboxes/.atom/packages/julia-client/script/boot_repl.jl, in expression starting on line 35
Julia has exited. Press Enter to start a new session.

**Comment by pfitzseb** [comment]
As the error indicates, please try running `Pkg.build("HttpParser")` in a REPL outside of Atom.

**Comment by inarighas** [comment]
here is the output : 

> julia> Pkg.build("HttpParser")
INFO: Building HttpParser
INFO: Attempting to create directory /home/osboxes/.julia/v0.6/HttpParser/deps/downloads
INFO: Directory /home/osboxes/.julia/v0.6/HttpParser/deps/downloads already exists
INFO: Attempting to create directory /home/osboxes/.julia/v0.6/HttpParser/deps/downloads
INFO: Directory /home/osboxes/.julia/v0.6/HttpParser/deps/downloads already exists
INFO: Downloading file https://github.com/nodejs/http-parser/archive/v2.7.1.zip
INFO: Done downloading file https://github.com/nodejs/http-parser/archive/v2.7.1.zip
INFO: Attempting to create directory /home/osboxes/.julia/v0.6/HttpParser/deps
INFO: Directory /home/osboxes/.julia/v0.6/HttpParser/deps already exists
INFO: Path /home/osboxes/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1 already exists
INFO: Attempting to create directory /home/osboxes/.julia/v0.6/HttpParser/deps/usr/lib
INFO: Directory /home/osboxes/.julia/v0.6/HttpParser/deps/usr/lib already exists
INFO: Changing directory to /home/osboxes/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1
INFO: Changing directory to /home/osboxes/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1
INFO: Changing directory to /home/osboxes/.julia/v0.6/HttpParser/deps/src
INFO: Attempting to create directory /home/osboxes/.julia/v0.6/HttpParser/deps/usr/lib
INFO: Directory /home/osboxes/.julia/v0.6/HttpParser/deps/usr/lib already exists
INFO: Changing directory to /home/osboxes/.julia/v0.6/HttpParser/deps/src
make: Entering directory '/home/osboxes/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1'
cc  -I. -DHTTP_PARSER_STRICT=0  -Wall -Wextra -Werror -O3  -fPIC -c http_parser.c -o libhttp_parser.o
http_parser.c: In function ‘http_parser_execute’:
http_parser.c:1817:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
               parser->upgrade = 1;
               ~~~~~~~~~~~~~~~~^~~
http_parser.c:1819:13: note: here
             case 1:
             ^~~~
http_parser.c: In function ‘http_parser_parse_url’:
http_parser.c:2376:18: error: this statement may fall through [-Werror=implicit-fallthrough=]
         found_at = 1;
         ~~~~~~~~~^~~
http_parser.c:2379:7: note: here
       case s_req_server:
       ^~~~
cc1: all warnings being treated as errors
Makefile:102: recipe for target 'libhttp_parser.o' failed
make: *** [libhttp_parser.o] Error 1
make: Leaving directory '/home/osboxes/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1'
==========================================[ ERROR: HttpParser ]==========================================

LoadError: failed process: Process(setenv(`make -j8 -C http-parser-2.7.1 library`,String["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", "TEXTDOMAIN=im-config", "STATATERM=emacs", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "XDG_SESSION_DESKTOP=ubuntu", "XDG_SESSION_TYPE=wayland", "QT_IM_MODULE=ibus", "XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg", "USER=osboxes", "MKL_THREADING_LAYER=INTEL", "USERNAME=osboxes", "GNOME_SHELL_SESSION_MODE=ubuntu", "GDMSESSION=ubuntu", "COLUMNS=105", "XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop", "CLUTTER_IM_MODULE=xim", "SHELL=/bin/bash", "GJS_DEBUG_OUTPUT=stderr", "XDG_SEAT=seat0", "XDG_MENU_PREFIX=gnome-", "GTK_IM_MODULE=ibus", "SESSION_MANAGER=local/osboxes:@/tmp/.ICE-unix/764,unix/osboxes:/tmp/.ICE-unix/764", "XMODIFIERS=@im=ibus", "TERM=dumb", "HOME=/home/osboxes", "WAYLAND_DISPLAY=wayland-0", "IM_CONFIG_PHASE=2", "XDG_CURRENT_DESKTOP=ubuntu:GNOME", "LANG=en_US.UTF-8", "XDG_RUNTIME_DIR=/run/user/1000", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "LOGNAME=osboxes", "SHLVL=1", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "INSIDE_EMACS=25.2.2,comint", "DESKTOP_SESSION=ubuntu", "_=/usr/bin/gnome-session", "PAGER=cat", "GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/emacs25.desktop", "TERMCAP=", "PWD=/home/osboxes/braidPhon/sketchpad", "DISPLAY=:0", "GJS_DEBUG_TOPICS=JS ERROR;JS LOG", "SONAME=libhttp_parser.so", "XDG_VTNR=1", "XDG_SESSION_ID=1", "TEXTDOMAINDIR=/usr/share/locale/", "JOURNAL_STREAM=9:17386", "GIO_LAUNCHED_DESKTOP_FILE_PID=22371", "QT4_IM_MODULE=xim", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(2)) [2]
while loading /home/osboxes/.julia/v0.6/HttpParser/deps/build.jl, in expression starting on line 71

=========================================================================================================

============================================[ BUILD ERRORS ]=============================================

WARNING: HttpParser had build errors.

 - packages with build errors remain installed in /home/osboxes/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("HttpParser")`
 - build a single package by running its `deps/build.jl` script

=========================================================================================================

**Comment by inarighas** [comment]
i tried it in the beginning, and that made me think that the problem is caused by the HttpParser package... Maybe i need to transfer this question in its repository !

**Comment by pfitzseb** [comment]
Maybe try installing gcc and make beforehand: `apt-get install make gcc`. If that doesn't fix it, you can ask for help [over here](https://github.com/JuliaWeb/HttpParser.jl/issues).

**Comment by inarighas** [comment]
Installing `gcc` and` make` do not solve this problem. 
I will put the issue in the HttpParser repo.
thanks!
