### ISSUE TITLE
display not working when running block of code with ctrl+enter

### ISSUE THREAD

**Issue by szymonk211** [JunoLab/atom-julia-client#430]
I ran this code with ctrl+enter in atom and it printed nothing:

A = [12.1 13.12; 123.2 12.23]
for i in 1:10
    display(A)
end

It is annoying, because i have no idea how to do as trivial job as printing a matrix in loop. (println output is unreadable)

**Comment by marius311** [comment]
This is a possible workaround,

```julia
for i in 1:10
    show(STDOUT,"text/plain",A)
    println()
end
```

**Comment by pfitzseb** [comment]
Pretty sure this is fixed on master.
Should also have worked before (and did for me, I think).

**Comment by szymonk211** [comment]
Ok, it's probably combination of julia version and atom version. If it's fixed than ok.

**Comment by pfitzseb** [comment]
This might very well be related to https://github.com/JunoLab/Juno.jl/issues/115 or something similar. I do hope to get a new release out today, so then you can test this yourself :)
