### ISSUE TITLE
Missing Toolbar after 0.6.10 update

### ISSUE THREAD

**Issue by v-i-s-h** [JunoLab/atom-julia-client#435]
Hi,

I updated my Atom package julia-client to 0.6.10 and now the toolbar is gone!!
My atom package versions:
```
indent-detective -> 0.2.0
ink -> 0.8.3
julia-client -> 0.6.10
language-julia -> 0.15.0
latex-completion -> 0.3.3
tool-bar -> 1.1.6
uber-juno -> 0.1.2
```

Julia package versions:
```
Juno => v"0.4.0"
Atom => v"0.6.11"
```
I tried uninstalling uber-juno and all the above packages with no results! I even tried deleting my ```~/.atom``` folder, restarting atom and installing uber-juno. :/

Regards,
vish

**Comment by pfitzseb** [comment]
Just execute the `Tool Bar: Toggle` command in the command pane:
![grafik](https://user-images.githubusercontent.com/6735977/37104357-cbef54c6-222c-11e8-8156-7f787388163c.png)

**Comment by v-i-s-h** [comment]
Thanks!! :)
That worked. But when I tried this yesterday, it was not working! :/

Also I found that even if I do a package update in atom, I have to manually do the update of related Atom.jl package in julia. For a normal user, this is a bit annoying, because we just installed an update and suddenly the things are going mad with cryptic warnings. I appreciate the effort you are putting in developing the package. Is it possible to make that part also automated - like I update package in Atom and the relavant julia package will also get updated in julia's package folder?

**Comment by twadleigh** [comment]
I just upgraded Atom, deleted .atom, and reinstalled uber-juno. Still no toolbar, and toggling doesn't help. :-(

**Comment by HamletFr** [comment]
After the update I have the same problem and the Toggle command does not work. Any ideas?

**Comment by HamletFr** [comment]
Solved it: go to Settings - Julia Client - settings: Enable Menu and restart!

**Comment by pfitzseb** [comment]
Should be `Enable Toolbar`, but yes, that setting needs to be switched on.

**Comment by zekeriyasari** [comment]
For my case, having enable menu as @HamletFr said, toggling still required as @pfitzseb said. So, I combined both of the suggestions.

**Comment by aliyyousuff** [comment]
`Settings - Julia Client - settings` did that, still didn't work. 
How do I find Command Pane to execute the command to follow @pfitzseb suggestion?

**Comment by aliyyousuff** [comment]
I found it, and executed the command following @pfitzseb  suggestion, it worked. 
To find command pane: `Packages > Command Palette > Toggle `

Thanks.

**Comment by dizergin** [comment]
yes  you should recompile toolbar package in the favor of julia -client and then toggle it on. So it is not the issue it is just side effect of the atoms plugin technology

**Comment by brenhinkeller** [comment]
I'm having a similar / equivalent  issue. Toolbar was missing next time I restarted Atom, toggle doesn't work, and almost all julia-related commands are now missing from the command palette (all except the two from language-julia). Have tried several uninstall-reinstall sequences but nothing has worked yet.

**Comment by dizergin** [comment]
2brenhinkeller  just 
1 recompile toolbar (for my case it was enough)
2 recompile julia client
3. check Julia Client - settings: Enable Menu and restart
4. toggle toolbar On from menu
In the my case works sequence  : 1,3,4
Most probably it was due to precompiled tool bar libs, that was shipped with julia client (newer version
of tool bar was a bit incompatible)

**Comment by brenhinkeller** [comment]
How does one recompile toolbar, since as far as I can see these Atom add-ons like toolbar are written mostly in scripting languages and css, not really compiled languages? I assume you mean something different than just using apm to uninstall and reinstall? I searched the repo for toolbar (https://github.com/suda/tool-bar) but there is no mention of compilation and certainly no makefile. https://github.com/suda/tool-bar/lib seems to be all javascript.

**Comment by dizergin** [comment]
1. today was toolbar update - check it!
If it does not work -my way:>
a) uninstall toolbar and restart atom
b) install toolbar and got an incompatibility message from atom (with suggestion to recompile some libraries) -choose it
c)after some working .. restart atom and toggle the toolbar on

**Comment by brenhinkeller** [comment]
Thanks! Everything seems to be working again now.

**Comment by pfitzseb** [comment]
Alright, I'll close this since the issue seems to be resolved. With the new uber-juno version the most common cause of this error should be caught as well.
