### ISSUE TITLE
Boxes at end of file may become unreachable

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JunoLab/atom-julia-client#437]
When you have the display box at the end of the file, and there are many fields, the last items cannot be looked at. Here is an example:

![bildschirmfoto 2018-03-09 um 17 03 27](https://user-images.githubusercontent.com/18145188/37216832-1ca651b8-23bc-11e8-982b-d7a147ea59a3.png)

Here I cannot see, the content of `parameters`. Scrolling either inside the box or scrolling past the end of the file should be made available for that.

Another related question: Is there a way to "clear" all those boxes at once? I noticed `cmd+shift+enter` will but it also executes the whole file, which is unpleasant.

Thanks in advance!

**Comment by pfitzseb** [comment]
1. Go to Settings > Editor and enable `Scroll Past End`.
2. There's the `Inline Results: Clear All` command which is bound to `Cmd-I Cmd-C` by default I believe.

**Comment by BeastyBlacksmith** [comment]
Marvelous, thank you! I also saw the `Inline Results: Toggle` but, it didn't change anything for me. But `Inline Results: Clear All` works fine.

**Comment by pfitzseb** [comment]
`Inline Results: Toggle` moves the result under the current line and widens it to the complete editor width (same as the button in the little toolbar that pops up when you hover over a result).
