### ISSUE TITLE
atom julia-client: console options: legacy: PowerShell version < 3 encountered. Running without wrapper (interrupts won't work).

### ISSUE THREAD

**Issue by crash-crush** [JunoLab/atom-julia-client#439]
Hey,

I have tried like I don't know so many others to set up julia on atom to get an IDE like Matlab for example.
After some issues I solved myself through a lot of searching I brought it almost to work.

Till this issue: atom julia-client: console options: legacy: "PowerShell version < 3 encountered. Running without wrapper (interrupts won't work)."

I hope this style is ok, it would be kind of what I would also directly search on google.
And I hope someone can help.

Additionaly because there is nothing comparable out there, were can someone post instructions for a kind of setup because I made a step by step list, with the condensed information

Best regards,
crash-crush

**Comment by pfitzseb** [comment]
> Till this issue: atom julia-client: console options: legacy: "PowerShell version < 3 encountered. Running without wrapper (interrupts won't work)."

What version of Windows are you running? What does 
```
powershell -NoProfile $PSVersionTable.PSVersion
```
return if you type it into a terminal?

> Additionaly because there is nothing comparable out there, were can someone post instructions for a kind of setup because I made a step by step list, with the condensed information

Sounds awesome! :) You can open a PR [here](https://github.com/JunoLab/JunoDocs.jl) (or just paste your list into a gist and I can integrate it into our docs).

**Comment by crash-crush** [comment]
Windows 7

On Console Window in Atom where the error occurs:
Appears:

```
PowerShell version < 3 encountered. Running without wrapper (interrupts won't work).INFO: Precompiling module Atom.
UndefVarError: powershell not defined

```

And on the Command- line version from Julia:

```
julia> PowerShell version < 3 encountered. Running without wrapper (interrupts w
on't work).INFO: Precompiling module Atom.
ERROR: syntax: extra token "version" after end of expression

julia> UndefVarError: powershell not defined
```

And I will add the steps when all problems are solved ;).
