### ISSUE TITLE
Console improvements

### ISSUE THREAD

**Issue by musmo** [JunoLab/atom-julia-client#45]
Here are some things I would like to see for the console

* Better status indicator. Currently it blinks very slow making it hard to tell if it's actually running or not.
* Disallow users to enter other commands when the console is running
* Arrow keys for retrieving history (up key to call last command run)
* Clear console by the standard julia command `ctrl+l`
* Pretty format `@show` commands when running a script with `Ctrl+shift+enter`. It would be nice if `@show x` when `x` is a vector would output just like when you typed it directly in the console:
![image](https://cloud.githubusercontent.com/assets/4319522/10108885/91c67c86-6391-11e5-9c29-c12f547fc490.png)
* Subtle iconography in the console. I find the huge icons and massive quote marks in the console distracting:

![image](https://cloud.githubusercontent.com/assets/4319522/10109027/65cb371a-6392-11e5-862f-2101efa03119.png)

**Comment by Varanas** [comment]
Thanks for opening this and sorry for the lack of responses. :)
I think pretty much all of these points are valid, though the third and fourth point can easily be adressed by setting your own shortcuts for those commands:
```
'.ink.console':
  'down': 'console:next-in-history'
  'up': 'console:previous-in-history'
'.atom-workspace atom-text-editor':
  'ctrl+l': 'julia-client:clear-console'
```

The second point is a bit debatably imo, because that is a somewhat nice feature I kind like ;)

Still, the console defintely needs more work.

**Comment by CarloLucibello** [comment]
as suggested by @Varanas I overrided the console history's keybinding adding 
```
'.ink-console atom-text-editor:not([mini])':
  'down': 'console:next-in-history'
  'up': 'console:previous-in-history'
```
to `my keyboard.cson`.

Shouldn't these be the default bindings instead of  `alt-down` and `alt-up`?

**Comment by CarloLucibello** [comment]
another nice feature to have would be the possibility of selecting (and copying) the result of evaluations, both in the console and in the editor

**Comment by Varanas** [comment]
See also #47. Copying of inline results should work if you right click on the result.

**Comment by one-more-minute** [comment]
Most of the technical things here are fixed, the exceptions being styling issues and pretty printing `@show`. `@show` is definitely on the roadmap (I'd like to both pretty-print results as well as display a backtrace, like the chrome devtools), and I'll try things out in a few different themes to make sure that styling is ok.
