### ISSUE TITLE
Julia package not listed in Atom 

### ISSUE THREAD

**Issue by CBongiova** [JunoLab/atom-julia-client#451]
Hello 

I have a similar problem to what it was reported in https://github.com/JunoLab/atom-julia-client/blob/master/keymaps/julia-client.cson#L76

To wrap up: I have the Julia client and language-julia packages installed but Atom in not showing the Julia folder under Packages --> Julia. I tried to open the console with the commands cmd+j cmd+o/ctrl+j ctrl+o but I was not able to succeed. I also tried to uninstall/reinstall the packages with no success.
Any suggestion? 

Thanks!

**Comment by CBongiova** [comment]
It seems like I forgot to erase some of the "hidden" files from Atom. I have now cleaned it following the process in: https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084

**Comment by pfitzseb** [comment]
[This](http://docs.junolab.org/latest/man/faq.html#Juno-doesn't-work-properly-after-an-update.-What-do-I-do?-1) might have resolved your issue (can't be sure because the link in your first post isn't very helpful). Glad you got it worknig anyways! :)

**Comment by CBongiova** [comment]
I think I was being over positive...Unfortunately it isn't working yet. I am now trying to completely re-install atom and Julia. I will keep you posted! :-) Thanks for your help!

**Comment by pfitzseb** [comment]
Great! I've also just released a new version of uber-juno which should detect this situation and display a [more obvious warning](https://github.com/JunoLab/uber-juno/pull/45).
