### ISSUE TITLE
Open Terminal not working

### ISSUE THREAD

**Issue by aderzelle** [JunoLab/atom-julia-client#455]
Hello,

Basically "Open Terminal" does nothing when I click on it. I can open a Console tough. However there is no color or highlight of any sort in the Console (should I open another report for this)? 

I am on Atom 1.25 running in Manjaro Linux.

Thanks for your help

**Comment by pfitzseb** [comment]
You mean `Julia > Open Terminal`? That I supposed to open an external console window and start Julia in it, so we can only guess a good default for Linux. Go to `Settings > Packages > julia-client` and set `Terminal` to something that works for you.

**Comment by aderzelle** [comment]
yes I meant that. So far I haven't been able to find something that works for me. However, it might be an os issue rather than a Juno one. So I will investigate on that side.

**Comment by pfitzseb** [comment]
If you're using KDE then something like `konsole -e` should work for you (and something similar for other terminal emulators, but I don't know if they use `-e`).
