### ISSUE TITLE
a julia process is started when launch on startup is disabled in settings

### ISSUE THREAD

**Issue by xgdgsc** [JunoLab/atom-julia-client#460]
I disabled launch on startup in julia client settings. But everytime I start atom, a julia process taking more than 100MB memory still starts with atom and uses a lot of CPU at start. It keeps running even I don' t open any julia file.

**Comment by pfitzseb** [comment]
That option is a remnant of older Juno versions and now defunct. `Boot Mode: Cycler` automatically starts a few julia processes -- if you don't want that, switch to `Boot Mode: Basic`, which will start one instance of Julia (and only if you request it).

**Comment by xgdgsc** [comment]
Thanks. Changing to Basic works. Why not remove that option if it' s defunct.
