### ISSUE TITLE
WARNING: Atom.jl: unrecognised message validatepath and changemodule

### ISSUE THREAD

**Issue by guillempuig** [JunoLab/atom-julia-client#463]
Hello everyone!

I was using julia 0.6.2 in Atom and it worked correctly, nevertheless, for an specific project I need to work with Julia 0.5.2 version. So I have installed 0.5.2 the same way I did it for la version 0.6.2

I have updated all the packages in the new version, to have the same packages as I was using in the newer version, so I have nothing yet to update. I'm not having problem to work with Julia console, however, when using Atom and more precisely REPL I'm getting the following errors (when starting Julia)

```
WARNING: Atom.jl: unrecognised message validatepath
WARNING: Atom.jl: unrecognised message changemodule
```
I have read some other issues but I haven't found the solution.

Thanks you very much!

**Comment by pfitzseb** [comment]
You'll either live with those or revert to julia-client 0.5.x and a corresponding ink version. Look at `apm help install` for some more info on that.

**Comment by jamesonquinn** [comment]
https://github.com/JunoLab/Juno.jl/issues/141
