### ISSUE TITLE
Macro output to inline view instead of console

### ISSUE THREAD

**Issue by stakaz** [JunoLab/atom-julia-client#469]
Is it possible to have the output of say `@time` or `@show` in the inline results instead of the console? Would be great to have an option on this.

**Comment by pfitzseb** [comment]
Well, `@time` etc print their output directly to STDOUT. You can intercept that if you need to, e.g. with Suppressor.jl, but in general it's better to use an alternate function that returns the value you're interested in. In this case you might consider `@timed` or something similar.

**Comment by stakaz** [comment]
It is not only about time, this was only an example. Actually it is about nearly every macro with output. Line `@code_llvm` and so on. I would like to have kind of completely same output as in REPL from Juno. Is this possible?

**Comment by pfitzseb** [comment]
![grafik](https://user-images.githubusercontent.com/6735977/40608643-5f8fe054-626c-11e8-8610-17c59aae8f97.png)

It's definitely possible with e.g. the above macro, but I don't think we'll have that as the default in Juno. It's not really a given that whatever is printed to STDOUT is more interesting than the actual return value.

**Comment by stakaz** [comment]
Ok, I have another question, but I dont know, whether it is worse it to make a new issue for that. If the output goes to the REPL as standard option, why not print it exactly as in a Julia standard REPL e. g. 

```julia
julia> A = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4
``` 
instead of `[1 2; 3 4]` which is the case now. 

I mean, the julia team already thought about a good way for the output and I cannot understand why it should be not used in Atoms REPL by defalut or at least as an option.

Would that be possible to implement?

Nevertheless, thanks for the reply and support.

**Comment by pfitzseb** [comment]
It definitely should look like that in the Juno REPL:
![grafik](https://user-images.githubusercontent.com/6735977/40611616-4dae06d0-6277-11e8-9356-121a8694a4ef.png)

It's very weird that it looks differently for you, so two quesitons: Are you on the latest version of Juno? Also, can you post a screenshot of what that looks like for you?

**Comment by stakaz** [comment]
Yes, when I type it into the REPL directly it gives the desierd output. However, the same Array defintion in a file and Run selection (or block) gives the second output:

![image](https://user-images.githubusercontent.com/998651/40612376-80d587d8-627a-11e8-8f81-22de307d7f8e.png)
So the issue is about output from executed code in a file...

A second very annoying thing is when accidentally evaluate e. g. `rand(100000)` in the file, I get the whole array printed to the REPL instead of a representation with dots.

The JUNO version is 0.6.13

**Comment by pfitzseb** [comment]
Ah, I see. I was mistakenly using `show` instead of `display` for showing those results in the REPL. 
Should be fixed with https://github.com/JunoLab/Atom.jl/commit/bce4ac688c42ecb231c1c4d6f2ed8acf2163ff0c.

**Comment by stakaz** [comment]
Yeah, that is great. Thank you for the quick fix.
