### ISSUE TITLE
Can't copy output from console

### ISSUE THREAD

**Issue by stillyslalom** [JunoLab/atom-julia-client#47]
(On Windows 10, Atom 1.0.18, Julia 0.4.0-rc2): it's possible to copy input lines from the console by right-clicking and selecting 'copy', but output lines cannot be copied by the same method. Neither input nor output lines can be copied or pasted using keyboard shortcuts.

Using right-click on an input line:
![image](https://cloud.githubusercontent.com/assets/4324760/10120549/192e3058-6485-11e5-97fb-c67cf1ffe99f.png)

Using right-click on an output line:
![image](https://cloud.githubusercontent.com/assets/4324760/10120545/db0d518c-6484-11e5-9406-1e5062d842a0.png)

**Comment by spencerlyon2** [comment]
I'd love this, but can't quite decide how to implement it. Any tips 

cc: @Varanas

**Comment by Varanas** [comment]
You could add a context menu entry to `ink.cson` that only applies to the console and write a function that either copies the current `.cell` (you may be able to get that via `currentTarget` or something similar) or somehow try to get the selection and copy that. 

That said: I'm not sure if we shouldn't just redesign the console so this Just Works -- only problem is that it's *not* easy to do it right at all (and we'd need someone who has the time, of course)...

**Comment by one-more-minute** [comment]
This is implemented!
