### ISSUE TITLE
juno-msg-loadERROR: LoadError: ArgumentError: Module Atom not found in current path

### ISSUE THREAD

**Issue by RosalesE** [JunoLab/atom-julia-client#473]
I am trying to run Julia package on ATOM for the first time, but I'm getting this error... 

**Starting Julia...
juno-msg-loadERROR: LoadError: ArgumentError: Module Atom not found in current path.
Run `Pkg.add("Atom")` to install the Atom package.
while loading C:\Users\s1678502\.atom\packages\julia-client\script\boot_repl.jl, in expression start
ing on line 16**

When I try to `Pkg.add("Atom")` on Julia I get the following error: 

![image](https://user-images.githubusercontent.com/39735352/40662743-231f15b6-634f-11e8-8aaa-34b8c90932ce.png)

Can anyone explain how to fix this? Appreciate your help!

**Comment by pfitzseb** [comment]
Same as https://github.com/JuliaLang/julia/issues/26167.
