### ISSUE TITLE
Unicode issues in REPL on windows

### ISSUE THREAD

**Issue by mistguy** [JunoLab/atom-julia-client#475]
On windows, some of the unicode symbols seem to behave quite unexpectedly in the integrated REPL. Although the default REPL (provided by julia by default) is also buggy in the aspect, is it possible to work around this issue?

An example
![image](https://user-images.githubusercontent.com/8522036/40871544-870eb974-6678-11e8-8a76-bb508cf4bffa.png)
hitting "+"
![image](https://user-images.githubusercontent.com/8522036/40871550-990469e4-6678-11e8-8b1e-929ee99b6b71.png)
The alpha symbol becomes invisible.

**Comment by pfitzseb** [comment]
I can't reproduce that, neither in the REPL nor in Juno. Did you enter that `α` via `\alpha\tab`?

**Comment by mistguy** [comment]
Well, I never understand fonts. 

I am using Atom default Menlo, Consolas, DejaVu Sans Mono, monospace and since I do not have Menlo I think I am using Consolas.

I am not sure this is really font related since I have tried quite a number of them. The only font that does not have this issue is `symbol`, with which I press `a` and get `α`.

**Comment by pfitzseb** [comment]
Hm, very weird. The only other thing that comes to mind is that this is in some way locale dependent, but I'm not sure why that would be the case.

You could also try using another font in Atom (I quite like Source Code Pro), but I couldn't reproduce the problems you're seeing with Consolas .

**Comment by mistguy** [comment]
I tried "Source Code Pro" yesterday. I even tried to change my system language to English. I'll ask my colleagues whether they can reproduce this. After all, I spent quite a lot of time pushing them to julia :)

**Comment by wuhuagumu** [comment]
Hi, 

mistguy asked me to test if his problem is reproducible. The result is yes. And unluckily, I found some other problem. 

1. \alpha followed by any character will make it temporarily disappear. Type in another Unicode (like \beta) will make it appear. Type in numbers won't. 
2. When you do backspace on "\alpha\tab+1", \alpha will appear. It now looks like "\alpha\tab+" 
3. When you type "\alpha\tab+1", the \alpha disappears but let's ignore this one at now. Then you backspace, "1" disappears. Retype "1", here "1" will take the place of the original "+".  It now looks like "\alpha\tab1"

I think the space transformation to support Unicode may still have some problems. 

My platform:
Windows 10 1803
atom 1.27.2 x64
julia-client 0.6.2

**Comment by mistguy** [comment]
Well, I am not sure what information I can provide right now. As a last resort, I can let you remote desktop to my laptop @pfitzseb .

**Comment by mistguy** [comment]
I fixed it by Settings-Region&Language-Administrative Language Settings-Change System Local-Beta: Use Unicode UTF-8 for worldwide language support. Therefore, it is a Windows issue anyway.

**Comment by mistguy** [comment]
Well, using Beta: Use Unicode UTF-8 for worldwide language support breaks a lot of things. It's better to change system locale to English in Administrative Language Settings

**Comment by pfitzseb** [comment]
Great it's working for you now! Just to make sure: This was an error in the normal Windows terminal too, right? If not it might make sense to reopen this at xterm.js.

**Comment by mistguy** [comment]
Yes, this is reproducible at powershell terminal.

**Comment by pfitzseb** [comment]
Alright, then there's nothing we can do about this I think.
