### ISSUE TITLE
`if` in comprehensions messes up indent detection

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-julia-client#478]
MWE:

```julia
module Foo

function bar(x)
    if x != nothing
        [z for z in x if z != nothing]
    else
        x
    end
end

end # module foo
```

Pressing `CTRL+Enter` inside the function definition seems to include the final `end` in what it executes, giving the error `syntax: unexpected "end"`

**Comment by pfitzseb** [comment]
Fixed by https://github.com/JunoLab/atom-julia-client/commit/aa133bc131cbdf3a807d2896e5603f68484dab8c.
