### ISSUE TITLE
copy button in inline results and errors

### ISSUE THREAD

**Issue by Varanas** [JunoLab/atom-julia-client#48]
that copies the (lazy-loaded) plaintext output, ideally with expanded paths and stuff.
Bonus: Another button that copies the output in such a way that it can then be used as a valid input, e.g. eval `Dict(:a => 1, :b => 2)` and get exactly that back.

**Comment by one-more-minute** [comment]
Definitely! We actually already have a copy item on the right click menu for inline results, although it doesn't do much as yet.
