### ISSUE TITLE
error at REPL prompt

### ISSUE THREAD

**Issue by epogrebnyak** [JunoLab/atom-julia-client#480]
I get this error at Atom. Any directions to fix/configure?

```
Press Enter to start Julia.
ERROR: unknown option `-3`
```

**Comment by pfitzseb** [comment]
Yeah, use a more recent version of Julia :) We only support 0.6 right now.

**Comment by epogrebnyak** [comment]
@pfitzseb - thanks, it is solved by updating a version!
