### ISSUE TITLE
Run Block Doesn't Work

### ISSUE THREAD

**Issue by saiknave** [JunoLab/atom-julia-client#487]
Windows 10, Atom 1.28.2, Julia 0.6.4. The Julia REPL works fine, but when I try to run blocks of the Julia code in the editor above it just never finishes processing.

**Comment by pfitzseb** [comment]
What version of `ink` do you have installed?

**Comment by saiknave** [comment]
I just updated to the latest version. I think it was from 0.x.5 to 0.x.6. The run block button works now, but the shift+enter shortcut still does not.

**Comment by pfitzseb** [comment]
What versions of julia-client, ink, Atom.jl, Juno.jl, and CodeTools.jl do you have installed?

**Comment by glwhart** [comment]
Maybe this is obvious to everyone else...it wasn't to me...the "run block" with shift+enter *only* works if the file has the extension `jl`. That's *not* true for hitting the "lightning" button which works regardless of the file name

**Comment by pfitzseb** [comment]
True, although you can change the file type with `Ctrl-Shift-L` independently of the actual file extension.
This behaviour is unlikely to change to make sure our keybindings are as unintrusive as possible. Should maybe be added to the FAQ though.
