### ISSUE TITLE
Are icons of "Documentation" and "Workspace" right?

### ISSUE THREAD

**Issue by taohonker** [JunoLab/atom-julia-client#488]
<img width="49" alt="screen shot 2018-07-20 at 09 26 31" src="https://user-images.githubusercontent.com/1193805/42978389-2e2f09ec-8bff-11e8-9ec8-6e41d78a08b6.png">
Top to bottom: Terminal, Plots, Workspace, Documentation. Why isn't the icon of Documentation a open book?

---

<img width="569" alt="screen shot 2018-07-20 at 09 26 19" src="https://user-images.githubusercontent.com/1193805/42978385-2a1118be-8bff-11e8-9c4c-606012f90b98.png">
Why are the two icons same?

**Comment by pfitzseb** [comment]
Why? Because I never really noticed the inconsistency :)
Fixed with https://github.com/JunoLab/atom-ink/commit/371f4851adbaf9d769f532cf634a1142464499a4.
