### ISSUE TITLE
Error on start-julia or toggle-console with eval

### ISSUE THREAD

**Issue by jgoldfar** [JunoLab/atom-julia-client#49]
```
ERROR: ArgumentError: Atom not found in path
  in require at ...
  in process_options at ...
  in _start at ...

Julia has stopped: 1, null
```

Any pointer on where to start debugging this? I have one working installation of julia-client, one not working...

**Comment by spencerlyon2** [comment]
This simply means that when the atom editor spawned a `julia`, that particular `julia` doesn't have the `Atom.jl` package installed

**Comment by jgoldfar** [comment]
Ah, that was the step I missed this time around. Thanks! I might recommend a step-by-step installation list rather than in paragraphs; I'd be willing to rewrite the docs.

**Comment by spencerlyon2** [comment]
PRs are always welcome, especially for docs!

**Comment by dvdplm** [comment]
How do I install `Atom.jl`? :)
