### ISSUE TITLE
[Pretty serious] Code incorrectly executed on terminal / REPL with middle-click on Linux

### ISSUE THREAD

**Issue by marius311** [JunoLab/atom-julia-client#493]
To reproduce (Atom 1.28.2, julia-client 0.7.1, Ubuntu 18.04):

* Open an empty Atom editor tab and a Julia client terminal. 
* Write something in the editor and select it. 
* Click on terminal to focus to it. 
* Now middle-click the editor tab to close it. 

You'll see the text you had selected is now pasted into the terminal, and if it contained newlines, has been evaluated. Better hope you hadn't selected `sudo rm -rf /` !

**Comment by pfitzseb** [comment]
Yes, but I'm not sure what I can do about it/why this even happens. Will definitely try to figure something out.

**Comment by marius311** [comment]
Thanks, I'm standing by to test whatever is needed. My guess is that since on Linux you can select some text then middle-click to paste it, what is happening it that when you go to middle-click the tab to close it, the focus is somehow still on the terminal so it triggers a paste in there as well.

**Comment by pfitzseb** [comment]
Yeah, I know what is going on and can repro this :) I'm not at all sure why the focus is so wrong though. Will definitely look into it once I'm home from juliacon.

**Comment by pfitzseb** [comment]
[This](https://github.com/atom/atom/pull/15183) is relevant, but not really a solution to this problem. I see three options right now:
1. Wait for xterm.js to implement customizable mouse handling.
2. Add a transparent overlay element on top of the console, add js to detect whether that's hit by a click and pass that through.
3. Make sure that Atom focuses the clicked element *before* handling the mouse event.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-ink/commit/7e99a7a1519f15238eb94a13ed44bc95afa1a5f4.

Was easier than I though...

**Comment by marius311** [comment]
Woohoo! Thanks for taking care of this, I really had kind of stopped using the terminal out of paranoia ha.
