### ISSUE TITLE
terminal window wraps narrower than actual pane width

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-julia-client#494]
It seems like Juno is wrapping lines more narrowly than the logging system expects them to, leading to extra line breaks, and messing up the pretty borders.

![image](https://user-images.githubusercontent.com/734386/43749595-b7d47742-99c2-11e8-9c21-e0088e597749.png)

**Comment by ssfrr** [comment]
Oh, actually the same thing happens in a basic terminal window, so maybe I'll repurpose this to request that the terminal pane not be made artificially narrow

**Comment by pfitzseb** [comment]
Yeah, that's an unfortunate issue on Windows. If you try resizing the terminal pane a bunch it should work fine afterwards. And I think I have a partial fix for this on ink master, but not entirely sure it works in all cases.

**Comment by pfitzseb** [comment]
Should be fixed now.
