### ISSUE TITLE
WARNING message every time starting a Julia session in Juno

### ISSUE THREAD

**Issue by rchen14** [JunoLab/atom-julia-client#496]
Just updated to julia-client 0.7.3, Juno console shows the following message:
> Starting Julia …
> INFO: Loading HttpServer methods…
> WARNING: Julia> Atom.jl: unrecognized message connected.

Running Pkg.update() to get the latest atom.jl does not help.
the current versions are Atom editor 1.29.0 x64, Atom.jl is 0.6.16

My questions are:
1. What is the HttpServer method used for? I did not see this previously
2. How to fix the WARNING message?

Thanks!

**Comment by pfitzseb** [comment]
No clue why that HttpServer thing is printed, that's somewhere in out dependencies. The is basically my fault, I'll try to get rid of that soon.

**Comment by rchen14** [comment]
Thanks! FYI, just rolled back to julia-client 0.7.1, HttpServer method is printed, without any warning or error message. The same message is still printed in 0.7.2.

**Comment by jebej** [comment]
Yes, I am also seeing this, with the latest release of everything on julia 0.6.4

**Comment by jebej** [comment]
It actually prints out:
```
[1m[36mINFO: [39m[22m[36mLoading HttpServer methods...
[39m
[1m[33mWARNING: [39m[22m[33mAtom.jl: unrecognised message connected.[39m
```

**Comment by pfitzseb** [comment]
Should be fixed by now.

**Comment by rchen14** [comment]
Thanks!
