### ISSUE TITLE
Timeline for Julia 1.0 support?

### ISSUE THREAD

**Issue by rwatts3** [JunoLab/atom-julia-client#498]
Greetings,

I'm sure you guys are hard at work to add support for Julia 1.0. 
I figured I'd create this issue to try and see if there is an expected timeline for support.

Thank you, 

Ryan

**Comment by pfitzseb** [comment]
Juno works fine on Julia 1.0 since last Thursday or so :)
I guess we should advertise that a bit more though.

**Comment by rwatts3** [comment]
That is great news. Thank you for confirming. 
Nice work !

**Comment by pfitzseb** [comment]
Thanks for the kind words. Let me know if anything goes awry (or even if it doesn't).
