### ISSUE TITLE
UndefVarError: active_repl not defined

### ISSUE THREAD

**Issue by PhillipBC** [JunoLab/atom-julia-client#499]
I have just installed Julia 1.0 on my fresh ubuntu 18 install, and then installed Atom and then Uber-Juno, as I had done on another computer last week.
However now when I press Julia-> Start Julia, I get the error box 
"
Julia Client – Internal Error
UndefVarError: active_repl not defined
"

**Comment by pfitzseb** [comment]
Are you sure you're on the latest versions of all your Julia packages? What version of julia-client and ink are you running?

**Comment by pfitzseb** [comment]
Nevermind, I think I know what's going wrong here.

Please just use the REPL-based console instead of the legacy console for now.

**Comment by PhillipBC** [comment]
Julia Client 0.7.3
Ink 0.9.4

It was still working actually, just that error for some reason, and it wouldn't let me use the 'find' function.

**Comment by SemperFiDev** [comment]
I'm having the same issue. I tried using the legacy version and it allows me to actually input something but it just crashes. I tried uninstalling and reinstalling the packages but it hasn't fixed anything. Anyone have a solution?

**Comment by pfitzseb** [comment]
What version of the Atom packages `julia-client` and `ink` as well as the Julia packages `Atom.jl` and `Juno.jl` do you have installed?

**Comment by SemperFiDev** [comment]
So removed the version of them being pinned and updated them. Now running julia-client (0.7.6), ink (0.9.6), uber-juno (0.2.0), julia-language (0.17.0) but nothing has changed. Still stuck on the green text "Press Enter to start Julia" within the REPL. It works SOMEwhat in legacy but I want to get REPL working.
