### ISSUE TITLE
Plots not showing up

### ISSUE THREAD

**Issue by CarloLucibello** [JunoLab/atom-julia-client#50]
Evaluating in atom the lines
```
using Gadfly
plot(sin, 0, 1)
```
results in the last line returning a Plot object, but nothing is displayed in the browser. The same happens with PyPlot.  

Is this a bug or a feature not implemented yet? In the latter case sorry for the noise.

Bye,
Carlo

**Comment by spencerlyon2** [comment]
Just not implemented yet

**Comment by one-more-minute** [comment]
This will work for Gadfly now, I'm working on getting a plotting pane + other libraries working.

**Comment by hafez-ahmad** [comment]
it  does work in atom. any solution?
using Gadfly 
xvalues = rand(1000);
yvalues = rand(1000);
Gadfly.plot(x=xvalues,y=xvalues,Geom.point,Geom.line)

Gadfly.plot(x=1:10, y=2.^rand(10),Scale.y_sqrt, Geom.point, Geom.smooth,
Guide.xlabel("Stimulus"), Guide.ylabel("Response"), Guide.title("Dog Training"))

**Comment by aviatesk** [comment]
see https://github.com/JunoLab/Juno.jl/issues/583
