### ISSUE TITLE
Argument / Parameter Intellisense

### ISSUE THREAD

**Issue by rwatts3** [JunoLab/atom-julia-client#500]
Greetings, 

I am currently not able to see intellisense for a functions arguments or parameters. 
Is this currently not supported or is there an additional configuration I must set in order to get intellisense on function arguments?

**Comment by pfitzseb** [comment]
Yeah, we just don't have that yet. See [here](https://github.com/JunoLab/Atom.jl/pull/125) for some progress.

**Comment by rwatts3** [comment]
Just checking does this close mean that it is now available ?

I see a prompt for a new Julia client update in atom   

And I see the property has been merged.

**Comment by pfitzseb** [comment]
Yeah, this feature is in the latest Juno release (in a somewhat limited but still very useful form).
