### ISSUE TITLE
Julia Client - Internal Error: Base.InvalidCharError{Char}('\xb0')

### ISSUE THREAD

**Issue by kylebeggs** [JunoLab/atom-julia-client#502]
Upgraded from Julia v0.6.4 to v0.7 in Atom using Juno and I am getting this error ``Julia Client - Internal Error: Base.InvalidCharError{Char}('\xb0')`` It pops up randomly, I do not have to press anything to invoke it. I cannot run any code. When I simply chnage the path back to v0.6.4, eveyrthing works as normal. v0.7 works perfect when opening the REPL outside of Atom so I presume it is installed correctly. Thanks.

Edit - I am on Windows 10.

**Comment by pfitzseb** [comment]
What versions of julia-client, ink, Atom.jl, Juno.jl and CodeTools.jl do you have installed on Julia 0.7?

**Comment by kylebeggs** [comment]
julia-client: v0.7.3
ink: v0.9.4
Atom.jl: v0.7.3
Juno.jl: v0.5.2
CodeTools.jl: v0.6.1

**Comment by pfitzseb** [comment]
Can you show the code your working on? This is an error with parsing your code, which seems to contain an invalid character.

**Comment by pfitzseb** [comment]
> What I have been trying to do is run a file that I mapped to on another drive.

Can you tell me a bit more about you're doing that? And did you try to run the `print("hello")` example the same way?

**Comment by kylebeggs** [comment]
I am trying to do analysis on large data sets that are on my lab's high performance cluster. All of my work is on that server, so it is nice to be able to save my code there and juts run it from there as well. Just so I can organize all of files better. For now, I have it saved locally and am giving the filepath to the data so I am able to continue my work. Yes, I tried running just the ``print("hello")`` this way and same error. It works if I open the REPL on the server and run it like that as well, just not through Atom through the server.

**Comment by kylebeggs** [comment]
Perhaps I should reopen the issue. I also switched my current working directory when I updated to Julia-client v0.7.5 and I am thinking it has something to do with that. I switched back and I got the error again, but it is not doing it as frequently as before. Weird. I will do some more digging when I get time.

**Comment by pfitzseb** [comment]
Hm, the most likely thing is that you have a `*.jl` file somewhere "around" the file you're working in (i.e. in the same dir, or dir above the current one) that has an invalid UTF8 character.
Is the code you're working on public? If so I could take a look and try to reproduce that.

**Comment by kylebeggs** [comment]
It is definitely something to do with that. I made a new dir and copied all the contents of the old dir into it. I switched my working dir to the new dir and no error. Unfortunately, at this point I can't upload the code, but probably soon. It is not an issue now for me. Since I think it is obvious there is no problem with the client and it is user error, I will close the issue. Thanks for your help.

**Comment by pfitzseb** [comment]
Where is your file relative to the NFS dir? If it's directly in the NFS dir, can you try moving it to a subdir, or even nest in one level further and report whether you can repro the bug?

**Comment by Benoit9** [comment]
Aha! I get the error in /nfs/hello.jl and in /nfs/tmp/hello.jl but not in /nfs/tmp/tmp2/hello.jl (so two dir level deep)

**Comment by pfitzseb** [comment]
Ok, that totally makes sense.

Can you try the following for me?
```
pkg> dev CodeTools
```
and then apply
```diff
diff --git a/src/module.jl b/src/module.jl
index 5695aeb..de84596 100644
--- a/src/module.jl
+++ b/src/module.jl
@@ -159,7 +159,12 @@ file is included or nothing.
 """
 function find_include(path::AbstractString)
   for file in @> path dirname dirsnearby jl_files
-    line = includeline(file, path)
+    line = -1
+    try
+      line = includeline(file, path)
+    catch err
+      return nothing
+    end
     line > 0 && (return file, line)
   end
 end
```
in `~/.julia/dev/CodeTools`? That should "fix" the bug, I think.

**Comment by Benoit9** [comment]
Indeed it fixes the bug! Thank you so much!

**Comment by pfitzseb** [comment]
Alright, thanks for testing! Once https://github.com/JuliaLang/METADATA.jl/pull/18018 is merged you can revert back to the release version of CodeTools.
