### ISSUE TITLE
Missing "end" causes Internal Error

### ISSUE THREAD

**Issue by jakobnissen** [JunoLab/atom-julia-client#506]
After updating the Julia client, whenever I run a script that lacks an "end" using Shift+Enter, it raises an internal error.

__How to reproduce:__

1) Open a new Julia file with the content:
```
function f()
1
```

2) Select the two lines and press Shift+Enter to run it

3) It will now show the following error:

```
Julia Client – Internal Error
MethodError: no method matching -(::Nothing, ::Int64)
Closest candidates are:
  -(!Matched::Complex{Bool}, ::Real) at complex.jl:298
  -(!Matched::Missing, ::Number) at missing.jl:93
  -(!Matched::Base.CoreLogging.LogLevel, ::Integer) at logging.jl:107
  ...
fetch at task.jl:202 [inlined]
macro expansion at dynamic.jl:67 [inlined]
(::getfield(Atom, Symbol("##107#112")))(::Dict{String,Any}) at eval.jl:82
handlemsg(::Dict{String,Any}, ::Dict{String,Any}) at comm.jl:168
(::getfield(Atom, Symbol("##14#17")){Array{Any,1}})() at task.jl:259
```

It works fine (i.e. raises the proper error) if I run the script by using Shift+Control+Enter.

__Environment__

I'm using julia-client 0.7.3, Julia version 1.0.0, and Atom version 1.29.0 on a Linux x64 machine.

**Comment by pfitzseb** [comment]
Basically the same as https://discourse.julialang.org/t/error-handling-in-juno/13757. The internal error is fixed on Atom.jl master (I'll tag a new release in a bit).

There's also a problem with the Julia version distributed by AUR, which I assume you're using.
