### ISSUE TITLE
Can't run julia 1.0.0 through Atom 1.29.0

### ISSUE THREAD

**Issue by maxMel1** [JunoLab/atom-julia-client#507]
Hello,
I installed Atom 1.29 on my windows 10 64 workstation and installed the packages ink, julia-client and uber-juno from JunoLab. I also am able to run julia without issues in the terminal. In the julia-client package settings, I put the correct julia binary in the "Julia Path" field. However, in the console in Atom I get the following message:
UndefVarError ative_repl not defined

Changing from legacy to repl_based won't start anything.

**Comment by GZhang** [comment]
the same issues in ATom 1.30 with the Julia 1.0.0

**Comment by pfitzseb** [comment]
What happens if you open a Julia in a terminal and type in `using Atom`? If that works then the `REPL-based` console in Juno should as well.

**Comment by maxMel1** [comment]
You need to open Julia 1.0.0 terminal, type:
1.1.) using Pkg
1.2.) Pkg.add("Atom")
1.3.) using Atom

2,) start Atom 1.30
3.) update all packages
4.) in julia-client 0.7.5 (Junolab) set the right julia path to the 1.0.0 folder exe
5.) set console option REPL-based
6.)  i cant use the console for julia.....??

**Comment by pfitzseb** [comment]
> 6.) i cant use the console for julia.....??

Why, what errors do you get?

**Comment by maxMel1** [comment]
In atom, none.
It doesn’t start julia in atom or just the console doesn’t work for julia 1.0.0
Gesendet von meinem Windows 10-Gerät.

________________________________
Von: Sebastian Pfitzner <notifications@github.com>
Gesendet: Wednesday, September 5, 2018 12:04:40 PM
An: JunoLab/atom-julia-client
Cc: maxMel1; Author
Betreff: Re: [JunoLab/atom-julia-client] Can't run julia 1.0.0 through Atom 1.29.0 (#507)


6.) i cant use the console for julia.....??

Why, what errors do you get?

**Comment by pfitzseb** [comment]
Can you open Atom's internal Console with `Ctrl-Shift-I` and report any errors you might see there?

**Comment by maxMel1** [comment]
events.js:183 Uncaught Error: connect ENOENT \\.\pipe\winpty-conin-11292-1-1d44532179dac89-20051abd88cc6843f949741027609a3f
    at Object._errnoException (util.js:1024)
    at _exceptionWithHostPort (util.js:1046)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1182)

**Comment by maxMel1** [comment]
events.js:183 Uncaught Error: connect ENOENT \\.\pipe\winpty-conout-11724-2-1d4453300f2210f-0d6d9e009f419b8cc86fe48d77a639ea
    at Object._errnoException (util.js:1024)
    at _exceptionWithHostPort (util.js:1046)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1182)
_errnoException @ util.js:1024
_exceptionWithHostPort @ util.js:1046
afterConnect @ net.js:1182

**Comment by dlshcbmuipmam** [comment]
I encounter exactly the same issue. I follow the suggestion in https://discourse.julialang.org/t/atom-not-found-in-project-manifest-or-registry/13380 to solve the problem.

Basically, I open the Julia console, type  rm(joinpath(homedir(), ".julia", "registries"); recursive=true). Then Pkg.add("Atom") works, and everything else works.

**Comment by maxMel1** [comment]
REPL still doens't respond..which is described in discussion #468  and #443 


events.js:183 Uncaught Error: connect ENOENT \\.\pipe\winpty-conout-9396-2-1d4480e9ef507bf-485311be196693c2623b813ab8a02fca
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

**Comment by maxMel1** [comment]
REPL still doens't respond..which is described in discussion #468 #499  and #443
but no suggestion helped for me.

events.js:183 Uncaught Error: connect ENOENT \.\pipe\winpty-conout-9396-2-1d4480e9ef507bf-485311be196693c2623b813ab8a02fca
at Object._errnoException (util.js:1024:11)
at _exceptionWithHostPort (util.js:1046:20)
at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

**Comment by SemperFiDev** [comment]
Same here, error I get:

C:\Users\default\.atom\packages\julia-client\node_modules\node-pty-prebuilt\lib\windowsPtyAgent.js:25 Uncaught (in promise) Error: Error launching WinPTY agent: ConnectNamedPipe failed: Windows error 232
    at new WindowsPtyAgent (C:\Users\default\.atom\packages\julia-client\node_modules\node-pty-prebuilt\lib\windowsPtyAgent.js:25)
    at new WindowsTerminal (C:\Users\default\.atom\packages\julia-client\node_modules\node-pty-prebuilt\lib\windowsTerminal.js:45)
    at Object.spawn (C:\Users\default\.atom\packages\julia-client\node_modules\node-pty-prebuilt\lib\index.js:27)
    at basic2.js:84
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188)

**Comment by pfitzseb** [comment]
Probably dup of https://github.com/JunoLab/atom-julia-client/issues/443, closing.

**Comment by maxMel1** [comment]
No  the method of switching between repl and legacy is not the solution

Gesendet von meinem Windows 10-Gerät.

________________________________
Von: Sebastian Pfitzner <notifications@github.com>
Gesendet: Friday, September 28, 2018 12:05:26 PM
An: JunoLab/atom-julia-client
Cc: maxMel1; Author
Betreff: Re: [JunoLab/atom-julia-client] Can't run julia 1.0.0 through Atom 1.29.0 (#507)


Probably dup of #443<https://github.com/JunoLab/atom-julia-client/issues/443>, closing.
