### ISSUE TITLE
Missing underscores in REPL

### ISSUE THREAD

**Issue by andrewmarx** [JunoLab/atom-julia-client#509]
It appears the REPL is obscuring the underscores for some of us (see also #485). As you can see in the attached image, underscores appear correctly in the editor, but are 1 pixel  below the letters (default fonts on Ubuntu based OS). This appears to cause an issue in the REPL where the lines are spaced closer together and the underscore does not appear. Hopefully just tweaking the line spacing for the REPL fixes it, but I don't know enough about Atom to actually identify the exact cause and possible solutions.
![underscore](https://user-images.githubusercontent.com/13956617/44915900-4856fb80-ad02-11e8-8ded-32152e783f0e.png)

**Comment by pfitzseb** [comment]
That's an upstream bug (see https://github.com/xtermjs/xterm.js/issues/1138). You can work around it by just using a different font for now.
