### ISSUE TITLE
Question: workflow: "Now open a different buffer..."

### ISSUE THREAD

**Issue by EricForgy** [JunoLab/atom-julia-client#51]
How do we open a different buffer?

**Comment by MichaelHatherly** [comment]
`ctrl-n` opens a new file. Perhaps "buffer" should be changed to "file" in the workflow docs since that's the term Atom tends to use it seems.

**Comment by EricForgy** [comment]
Yeah. Got it. Thanks.

This is beautiful! Just managed to get it to work. I'll see if I can revise the docs based on my newbie experience.
