### ISSUE TITLE
Save user-specified working directory

### ISSUE THREAD

**Issue by ebalaban** [JunoLab/atom-julia-client#511]
Currently if a user selects the working directory through the Julia Client package menu (`Packages -> Julia -> Working Directory -> Select...`), it gets "forgotten" if Julia or Atom/Juno are restarted. It would be very helpful if the choice of the working directory persisted. Perhaps that can be done through an option in the package settings.

Setting the working directory to that of the currently active file (as suggested in #490) would be an improvement over the current state of affairs, but I often look through files for different packages, while working on a particular one. Having to remember to select a file from the desired package before, say, restarting Julia is not ideal with this workflow. In addition to what is proposed in #490, it would also be great to have the option to set the working directory once and only change it when needed.

Thanks in advance!

**Comment by pfitzseb** [comment]
Implemented with https://github.com/JunoLab/atom-julia-client/commit/adf16b96893cf921b32e48f51075f26e443e2167.

**Comment by ebalaban** [comment]
Excellent, many thanks, @pfitzseb! This is a very helpful feature.
