### ISSUE TITLE
IOError: stat: unknown error (UNKNOWN) after asking for environment varible: ENV

### ISSUE THREAD

**Issue by cwb0** [JunoLab/atom-julia-client#515]
> julia> versioninfo()
Julia Version 0.7.0
Commit a4cb80f3ed (2018-08-08 06:46 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = "C:\Users\Carsten\AppData\Local\atom\app-1.30.0\atom.exe" -a
  JULIA_NUM_THREADS = 2

After a fresh start of Atom and typing:

> ENV

I've got the entries of the enviroment dictionary and subsequently I've got the following error message:

> Julia Client – Internal Error
IOError: stat: unknown error (UNKNOWN)

Then this message occurs repeatedly as soon as a new input in the REPL window is undertaken

**Comment by pfitzseb** [comment]
Are you working in a OneDrive directory, by any chance?

**Comment by cwb0** [comment]
If you mean by OneDrive the Mircosoft file hosting system then the answer is no.

**Comment by hhaensel** [comment]
I am experiencing the same thing after installing JuliaPro 1.0.1.1 to a shared drive (C:\JuliaPro-1.0.1.1)
No solution yet :-(

**Comment by pfitzseb** [comment]
That bug might be fixed with https://github.com/JunoLab/Atom.jl/commit/696b7539f8e5227adde8cd76cb271c725353697e.
