### ISSUE TITLE
inline result not clipped correctly

### ISSUE THREAD

**Issue by marius311** [JunoLab/atom-julia-client#517]
I'm on Atom 1.30.0, atom-julia-client 0.7.6, ink 0.9.7, and I see the following:

![out](https://user-images.githubusercontent.com/1510968/45591823-a79d4880-b95d-11e8-96d4-fd306e1d0d79.gif)

I bisected the problem to upgrading from ink 0.9.2 to 0.9.3, although potentially there's some dependence there on Atom/julia-client versions too, which I haven't checked.

**Comment by pfitzseb** [comment]
Yeah, that's basically working as intended.

While it's slightly ugly this change also came with a couple of QoL improvements, mostly for big inline results that overflow to the right (or down) of the editor, but also for autocompletions etc. Doing this right is surprisingly hard without patches to Atom base, afaict, but maybe I'm also just overlooking something obvious.

**Comment by marius311** [comment]
I see, thanks. Is there any way to clip them the exact moment they exit the editor area, rather than sticking around for a bit as they do now? It just really feels like its a bug this way rather than an intended behavior. 

Alternatively, is there any chance we could get this as an option, if say we wanted to keep the old behavior if we didn't care about the right/down overflow being clipped? I would definitely use it.

**Comment by pfitzseb** [comment]
Mh... I'll look into it again :)

**Comment by pfitzseb** [comment]
Can you try https://github.com/JunoLab/atom-ink/pull/176 for me?
Install instructions are in the [docs](http://docs.junolab.org/latest/devdocs/dev_install.html#Atom-Packages-1), with the additional step of checking out the right branch.

**Comment by marius311** [comment]
Closed by https://github.com/JunoLab/atom-ink/pull/176
