### ISSUE TITLE
`ARGS` config not actually used?

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-julia-client#523]
It seems that the `ARGS` configuration is not actually used. Here's a screenshot of my config:

![image](https://user-images.githubusercontent.com/734386/46484386-afffdb00-c7c7-11e8-92d2-5e5a08de95bb.png)

The options don't seem to take effect, and also `ARGS` is an empty list.

**Comment by pfitzseb** [comment]
You want this setting instead:
![image](https://user-images.githubusercontent.com/6735977/46485702-80b79100-c7fc-11e8-915e-3dd636ab2dd8.png)

**Comment by ssfrr** [comment]
ah, whoops, I didn't scroll down to see that option. Given that it's closely-related to the "Julia Path" option do you think it would make sense to put it right below? It seems like a more commonly-used option and ends up below "number of threads" and "optimization level".

Also maybe I should just learn to check the options more carefully. :)
