### ISSUE TITLE
Set the Pkg environment

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-julia-client#524]
Despite the heroic efforts both in Juno and Revise.jl, I still find myself restarting the Julia process from time to time, at which point I have to remember to re-activate whatever environment I'm working in.

It would be great if there were some widget where I could set a directory, which would both activate that directory (`Pkg.activate(dir)`) and also add `--project=<dir>` to the startup flags so when I restarted I'd still be in the configured project.

**Comment by pfitzseb** [comment]
I'll close this in favour of https://github.com/JunoLab/Juno.jl/issues/175.
