### ISSUE TITLE
DataFrame rendering on Atom 1.32.0-beta3 is bugged

### ISSUE THREAD

**Issue by laborg** [JunoLab/atom-julia-client#526]
Julia 1.0.1 + Ubuntu 18.10 Beta + Atom 1.32.0-beta results in bugged rendering of DataFrames:

![atombeta_error](https://user-images.githubusercontent.com/9527104/46598148-565b2180-cae3-11e8-8464-50965d08da1c.png)

Using the Console/Repl in the same Atom Instance works however (which i guess isn't a big surprise):
```julia
julia> using DataFrames

julia> DataFrame(a=[1])
1×1 DataFrame
│ Row │ a     │
│     │ Int64 │
├─────┼───────┤
│ 1   │ 1     │
```

**Comment by pfitzseb** [comment]
Ok, new ink version with this fix is out.

**Comment by laborg** [comment]
Thx - works!
