### ISSUE TITLE
Save Icon vanished (due to font-awesome update)

### ISSUE THREAD

**Issue by Deduction42** [JunoLab/atom-julia-client#529]
Recently, the Atom Tool Bar package had an update in terms of their font-awesome icons

v1.1.11 - 2018-11-04
Update font-awesome icons to 5.4.2

This causes the tool bar for julia-client to be missing its save icon. I suspect that this is a problem with 

.atom/packages/julia-client/lib/package/toolbar.coffee

I was able to enable a makeshift icon by going to this file and making the following change. Finding the save button under

@bar.addButton
      icon: 'floppy-o'
      callback: 'core:save'
      tooltip: 'Save'
      iconset: 'fa'

and replacing 'floppy-o' to 'save'

@bar.addButton
      icon: 'save'
      callback: 'core:save'
      tooltip: 'Save'
      iconset: 'fa'

It might be a good idea to revisit the font awesome names for this update.

**Comment by asbisen** [comment]
I have a pull request already open with the aforementioned changes. https://github.com/JunoLab/atom-julia-client/pull/528
