### ISSUE TITLE
uncluttered stacktraces

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/atom-julia-client#53]
so `atom-julia-client`s internal functions aren't mentioned. IIRC we did have this in Juno/LT.

**Comment by one-more-minute** [comment]
It's not too tricky to implement this, but since backtraces vary a bit across platforms it's just a bit of a pain to test.

**Comment by one-more-minute** [comment]
In general our backtrace-handling code is horrible. We can look into Stacktraces.jl (which was recently incorporated into Base) in order to improve the situation here.

**Comment by pfitzseb** [comment]
Mostly done.
