### ISSUE TITLE
REPL suddenly stuck : LoadError: ArgumentError: Package Pkg not found in current path:

### ISSUE THREAD

**Issue by massimilianocomin** [JunoLab/atom-julia-client#534]
Hello,

Juno was working fine with Julia 1.0.1 (2018-09-29), but suddenly when I start Julia from the REPL I get the following error :

```
Hold on tight while we're installing some packages for you.
This should only take a few seconds...

ERROR: LoadError: ArgumentError: Package Pkg not found in current path:
- Run `import Pkg; Pkg.add("Pkg")` to install the Pkg package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:820
 [2] top-level scope at /Users/mcomin/.atom/packages/julia-client/script/boot_repl.jl:18
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1041
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] exec_options(::Base.JLOptions) at ./client.jl:229
 [7] _start() at ./client.jl:421
in expression starting at /Users/mcomin/.atom/packages/julia-client/script/boot_repl.jl:1

Julia has exited. Press Enter to start a new session.
```

I tried to reinstall Atom / Juno or switching to legacy mode without success. Any help would be very appreciated !

**Comment by massimilianocomin** [comment]
Ok, I found the issue. It has nothing to do with Juno - sorry  for that.

It seems that setting the environment variable JULIA_LOAD_PATH in my .bash_profile broke Julia !

Removing this line (export JULIA_LOAD_PATH="/path/to/something") from .bash_profile did the job.

I hope it might help someone.

**Comment by pfitzseb** [comment]
Yup. If you use something like 
```
export JULIA_LOAD_PATH="@:@v#.#:@stdlib:/path/to/something"
```
it *should* work, I think. If you're missing `@stdlib` Julia can't find any stdlib package (`Pkg` in your case).
