### ISSUE TITLE
rospy: Is Atom changing path lookup behaviour?

### ISSUE THREAD

**Issue by togo59** [JunoLab/atom-julia-client#538]
I am using Atom 1.33, Ubuntu 16.04, Python2.7, ROS Kinetic and I have both Julia 0.6.4 and Julia 1.0.2. I have only installed the `uber-juno`, v0.2.0, package in Atom. `julia-client` is at version 0.7.11

I have (just now) re-run all the updates on all the above. I have run `] build PyCall`. I can see `rospy` is installed properly in the file system.

I start Julia 1.0.2 from an Atom console. I see that my start-up script has run. It contains `ENV["PYTHON"]="/usr/bin/python"`. I type `using RobotOS` and I get the error:
`ERROR: LoadError: InitError: rospy not found!
Has an environment setup script been run?` This message is generated from RobotOS when it can't find the requisite libraries. I have opened an issue on RobotOS.jl about this.

I do this outside of Atom and everything is fine, the same start-up script is run. The above error is only emitted from the Atom Julia console. I recall having no difficulty when I was using Julia 0.6.4 either using Atom or not. Atom starts the correct version of Julia (I know how to change this.) All other Julia behaviour is fine within Atom.

So the question is: Has Atom actually got anything to do with this behaviour, if so what?

**Comment by pfitzseb** [comment]
Hm, IIRC Atom does something with your environment, but I'm not entirely sure what anymore.

How are you starting Atom -- via the `.desktop` file or in a terminal? If the former, try starting it in a terminal where `using RobotOS` works as well.

**Comment by togo59** [comment]
You're right. If I start atom anywhere (I've only checked my Julia project tree, from ~ downwards) using the CLI it's OK. Normally, I open Atom by right-clicking on a folder and selecting (open with) Atom. This works for all packages except `using RobotOS`. E.g. there's no problem (anywhere) with `using PyCall`. So PyCall finds python but RobotOS doesn't. Thank you for your help, this problem was driving me mad. It's still a bit inconvenient but at least I have a simple workaround.
