### ISSUE TITLE
ARGS

### ISSUE THREAD

**Issue by ir1979** [JunoLab/atom-julia-client#539]
When I set ARGS, the program can see it only after restarting Juno.
I added it through Julia -> Settings -> Arguments

**Comment by pfitzseb** [comment]
This is actually working as intended. You need to restart the Julia process (not Atom) to change `ARGS` (because otherwise it'd be to easy to mess up your program state and it'd also be inconsistent with using Julia in a terminal). I've added a note to the setting that says as much.
