### ISSUE TITLE
atom GUI hangs when showing large inline result

### ISSUE THREAD

**Issue by dangjc** [JunoLab/atom-julia-client#54]
Great work so far on Atom Juno! I've been trying to switch over to it from LightTable, but there is one issue that's been stopping me. When a large dictionary/vector is returned as an inline result, the GUI takes a very long time to load it. Perhaps there needs to be some sort of truncation.

```
d = Dict()
for i = 1:10000   # 100000 will really stall
  d[i] = i
end
d      # looping the dict is fast, but getting the inline result is much slower

# also hangs with a vector
v = Array(Int, 0)
for i = 1:20000
  push!(v, i)
end
v    # this line will take about 12 seconds to run
```

**Comment by Varanas** [comment]
Yeah, this partly is #40, and should therefore be resolved for vectors if you are on `atom-julia-client` master.

Still, smarter printing of large types should really be adressed.

**Comment by Varanas** [comment]
The problems mentioned here have been fixed, but the overall not-so-nice handling of large inline results is still a problem. I'm gonna close this in favour of #12 though.
