### ISSUE TITLE
Failed to precompile Atom

### ISSUE THREAD

**Issue by GathererA** [JunoLab/atom-julia-client#545]
Hello! I am getting the following error when I try to boot Julia in Atom: 

WARNING: Method definition displayable(Atom.JunoDisplay, Base.MIME{Symbol("application/prs.juno.jlpane")}) in module Atom at /Users/agatherer/.julia/packages/Atom/v2iqN/src/display/showdisplay.jl:92 overwritten at /Users/agatherer/.julia/packages/Atom/v2iqN/src/display/showdisplay.jl:94.
ERROR: LoadError: LoadError: UndefVarError: IMMUTABLE not defined
.....
ERROR: LoadError: LoadError: Failed to precompile CodeTools [53a63b46-67e4-5edd-8c66-0af0544a99b9] to /Users/agatherer/.julia/compiled/v1.0/CodeTools/8fUnH.ji.
....
ERROR: LoadError: Failed to precompile Atom [c52e3926-4ff0-5f6e-af25-54175e0327b1] to /Users/agatherer/.julia/compiled/v1.0/Atom/w9XOh.ji.

Has anyone else seen this error?

**Comment by pfitzseb** [comment]
See https://discourse.julialang.org/t/cannot-use-juno-with-atom-atom-package-precompilation-failed/19208/3 and https://github.com/JunoLab/Juno.jl/issues/215.
