### ISSUE TITLE
REPL display cuts the bottom of some letters (p, g, y, etc.) on Mac

### ISSUE THREAD

**Issue by mrkite92** [JunoLab/atom-julia-client#548]
Hi Julia gurus,

Here is a screenshot of the REPL window in Atom on my Mac. All letters like p, g, y, etc. are cut at the bottom. Looks like a too narrow space between lines.
Thanks for your expertise,
Cheers,
JB
![image](https://user-images.githubusercontent.com/875257/52706146-fe4a9500-2f84-11e9-9403-2ce5f41a6ccf.png)

**Comment by pfitzseb** [comment]
Dup of https://github.com/JunoLab/atom-julia-client/issues/485 and https://github.com/xtermjs/xterm.js/issues/1138.
TL;DR: Use a different font until the upstream issue is fixed.
