### ISSUE TITLE
Uncaught Error: Signals not supported on windows.

### ISSUE THREAD

**Issue by ErwanPiR** [JunoLab/atom-julia-client#549]
Hi,

I have an issue when trying to interrupt Julia in atom.

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Windows 10
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.7.13

**Uncaught Error: Signals not supported on windows.**

Does somenone have the same problem and know how can I fix it ?

Thanks !

**Comment by pfitzseb** [comment]
You probably don't use the powershell wrapper, right? Since Windows does in fact not support signals we can't support interrupts without the wrapper.

**Comment by ErwanPiR** [comment]
Good point !! I uncheck the powershell wrapper for another reason and forgot to recheck it.

Thanks a lot and sorry for the dummy question...

**Comment by pfitzseb** [comment]
No worries.
