### ISSUE TITLE
Default Path for writting .txt files when runing a script

### ISSUE THREAD

**Issue by lionpeloux** [JunoLab/atom-julia-client#55]
Hey,

I've just switched to the old juno to the atom version (a little bit of work to make it work, but not that bad). It looks pretty cool.

I've launched a script that writes .txt files. if I call : 
```julia
writedlm("myfile.txt", myarray)
```
Then my files are sent to the \Users\Lionel\Documents directory.
Don't you think it would be better to define the path relatively to the path of the script itsef, so it default to the script's directory ?

Just a thought ...
Thanks,
Lionel

**Comment by spencerlyon2** [comment]
Yeah, this comes up for me sometimes too.

The current workaround is to use the `julia-client:work-in-file-folder` command. 

In my `keymap.cson` file I have the following (NOTE I use OSX, so I have `cmd` here, `ctrl` is probably more appropriate for windows or linux.)

```
'atom-text-editor[data-grammar="source julia"]':
  'cmd-j cmd-f': 'julia-client:work-in-file-folder'
```

**Comment by lionpeloux** [comment]
Hi spencerlyon2 (are you really from Lyon, France ? cause I' am too ...)
Anyway ... your proposal looks great but I'm a complete newbie with atom  and things don't work for me.
I see the atom command is yet defined in the /julia-client/lib/utils.coffee
I've set up the keybind in my keymap.cson
I've hit hundred (just in case) of times cmd-j cmd-f but nothing happened ...

Any advice ?
Thanks,
Lionel

**Comment by spencerlyon2** [comment]
Nope, not from Lyon -- that's just my last name.

After you run the command one time will you just open up the REPL

```
`ctrl-`
```

and try the command `pwd()`. Let's see if it updated

**Comment by lionpeloux** [comment]
Great ! It's working ! 
Thanks.

**Comment by one-more-minute** [comment]
It doesn't really work for us to automatically `cd` to the script's folder because it would lead to confusing behaviour. However, it occurs to me that it might be nice to boot julia in the current directory when you start Atom from the command line.
