### ISSUE TITLE
Error in Debugger

### ISSUE THREAD

**Issue by sth4nth** [JunoLab/atom-julia-client#555]
Just upgraded to 0.8. Everytime I set a break point, the error showed up:
Error in Debugger
no signature found at
...
Restarting and "using Revise" may fix

I installed Revise and run 'using Revise'. The problem is still there.

**Comment by pfitzseb** [comment]
Take a look at [the Revise docs](https://timholy.github.io/Revise.jl/stable/#What-Revise-can-track-1) to help figure out what you need to do to have Revise track your file.
