### ISSUE TITLE
unable to install julia-client@0.8.2

### ISSUE THREAD

**Issue by Krishnendu1986** [JunoLab/atom-julia-client#557]
Please check your internet connection, or report this to
    http://discuss.junolab.org
and we'll try to help.
    –––
Error: Installing “julia-client@0.8.2” failed.

**Comment by Krishnendu1986** [comment]
Juno: Error installing package julia-client
Please check your internet connection, or report this to
    http://discuss.junolab.org
and we'll try to help.
    –––
Error: Installing “julia-client@0.8.2” failed.

**Comment by Krishnendu1986** [comment]
The FOLLOWING SOLUTION PROVIDED BY @jandehaan NOT WORKING
This solved the issue for me:
In Windows open a command window, enter the following and press the Enter key.
apm config set strict-ssl false

**Comment by pfitzseb** [comment]
If you can't **un**install, then close Atom and type `apm uninstall julia-client` into a `cmd` prompt.

**Comment by mattar13** [comment]
The solution mentioned above is not working. 
My atom version seemed to update to 1.39.0 and I started getting this same issue. 
I attempted to run "apm install julia-client" from the terminal and came up with the same problem. 
I used the apm config set strict-ssl false solution but that did nothing.
I tried a clean install of Atom and kept running into the same problem. 
Next I tried disabling the antivirus, and following the solution mentioned here 
https://github.com/JunoLab/atom-julia-client/issues/520#issuecomment-425386233
but to no avail.

**Comment by ludoro** [comment]
I am having the same problem, this is my log error:

```
> node-pty-prebuilt@0.7.6 install /private/var/folders/6g/g0h58kn94s7b3cr4pdpsntyc0000gn/T/apm-install-dir-119623-1239-z4edgp.o71v/node_modules/julia-client/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js


npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=darwin)
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/private/var/folders/6g/g0h58kn94s7b3cr4pdpsntyc0000gn/T/AppTranslocation/D6D0DBFB-3989-4A18-8ABB-037CEEE961DD/d/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/private/var/folders/6g/g0h58kn94s7b3cr4pdpsntyc0000gn/T/AppTranslocation/D6D0DBFB-3989-4A18-8ABB-037CEEE961DD/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/private/var/folders/6g/g0h58kn94s7b3cr4pdpsntyc0000gn/T/AppTranslocation/D6D0DBFB-3989-4A18-8ABB-037CEEE961DD/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/private/var/folders/6g/g0h58kn94s7b3cr4pdpsntyc0000gn/T/AppTranslocation/D6D0DBFB-3989-4A18-8ABB-037CEEE961DD/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/6g/g0h58kn94s7b3cr4pdpsntyc0000gn/T/AppTranslocation/D6D0DBFB-3989-4A18-8ABB-037CEEE961DD/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd /private/var/folders/6g/g0h58kn94s7b3cr4pdpsntyc0000gn/T/apm-install-dir-119623-1239-z4edgp.o71v/node_modules/julia-client/node_modules/node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/6g/g0h58kn94s7b3cr4pdpsntyc0000gn/T/apm-install-dir-119623-1239-z4edgp.o71v/package.json'
npm WARN apm-install-dir-119623-1239-z4edgp.o71v No description
npm WARN apm-install-dir-119623-1239-z4edgp.o71v No repository field.
npm WARN apm-install-dir-119623-1239-z4edgp.o71v No README data
npm WARN apm-install-dir-119623-1239-z4edgp.o71v No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ludovicobessi/.atom/.apm/_logs/2019-07-23T17_15_21_904Z-debug.log

```

**Comment by aviatesk** [comment]
See this error:
```
gyp ERR! stack Error: Python executable "/private/var/folders/6g/g0h58kn94s7b3cr4pdpsntyc0000gn/T/AppTranslocation/D6D0DBFB-3989-4A18-8ABB-037CEEE961DD/d/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
```

`apm install julia-client` under an environment in which Python 2.7 is activated will solve the issue.

**Comment by pfitzseb** [comment]
Can you give the output of `atom -v`? For some reason one of our dependencies isn't downloaded as a binary and instead we try to build it on your machine (which should never happen).

**Comment by jacobs14** [comment]
I am having the same problem. I tried installing in the cmd prompt, and this is what I got 

`npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\jacob\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\jacob\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\jacob\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\jacob\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\jacob\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\jacob\AppData\Local\Temp\apm-install-dir-119623-19328-vksei2.wqub\node_modules\julia-client\node_modules\node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\jacob\AppData\Local\Temp\apm-install-dir-119623-19328-vksei2.wqub\package.json'
npm WARN apm-install-dir-119623-19328-vksei2.wqub No description
npm WARN apm-install-dir-119623-19328-vksei2.wqub No repository field.
npm WARN apm-install-dir-119623-19328-vksei2.wqub No README data
npm WARN apm-install-dir-119623-19328-vksei2.wqub No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: prebuild-install || node scripts/install.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by ludoro** [comment]
Atom -v gives me the following:

- Atom: 1.39.0
- Electron: 3.1.10
- Chrome 66.0.3359.181
- Node 10.2.0

**Comment by pfitzseb** [comment]
Cool, thanks. I think I have a fix ready, but still need to test on a couple of systems before releaseing.

**Comment by ludoro** [comment]
Wow, amazing! Thanks for the work, I am going to wait for the update then! Could you please comment when that's done?

**Comment by pfitzseb** [comment]
Yeah, I'll announce that here, on Discourse, and on Slack.

**Comment by andreale28** [comment]
@pfitzseb have you announced your solution yet?

**Comment by ludoro** [comment]
I do not know if you did something (probably yes) but It's working now for me!
