### ISSUE TITLE
CCALL : import path not working properly to load externall dylib / dll

### ISSUE THREAD

**Issue by lionpeloux** [JunoLab/atom-julia-client#56]
Hello,

I've been struggling with calling intel MKL with `CCALL API`. Everything is working in the console of julia v0.4 like this :
```julia
julia> function myasum(n::Integer, X::Vector{Float64}, incx::Integer)
         ccall((:cblas_dasum, :libmkl_rt),
               Float64,
               (Int64, Ptr{Float64}, Int64),
               n, X, incx)
       end
myasum (generic function with 1 method)

julia> myasum(3,[1.0,2.0,3.0],1)
6.0
```

But I could not make it in Juno, nor in Atom. My opinion is Juno and Atom doesn't get properly the path I defined in the `DYLD_LIBRARY_PATH` environment variable in my bash_profile. Indeed, if ii call `ENV` within julia v0.4 REPL I get the follwoing lines (remark the  `DYLD_LIBRARY_PATH` is present) :
```julia
julia> ENV
Base.EnvHash with 24 entries:
  "TERM_PROGRAM"           => "Apple_Terminal"
  "SHELL"                  => "/bin/bash"
  "TERM"                   => "xterm-256color"
  "TMPDIR"                 => "/var/folders/fy/jvkfn7_136570b5t7b8d6cw00000gn/T…
  "Apple_PubSub_Socket_Re… => "/private/tmp/com.apple.launchd.hMeo2BJQRj/Render"
  "TERM_PROGRAM_VERSION"   => "343.7"
  "TERM_SESSION_ID"        => "7440B6FA-C53F-4D79-AC27-A8320D0F4325"
  "USER"                   => "Lionel"
  "SSH_AUTH_SOCK"          => "/private/tmp/com.apple.launchd.QeyIfg9coQ/Listen…
  "__CF_USER_TEXT_ENCODIN… => "0x1F5:0x0:0x1"
  "PATH"                   => "/Applications/Julia-0.4.0.app/Contents/Resources…
  "PWD"                    => "/Users/Lionel"
  "LANG"                   => "fr_FR.UTF-8"
  "XPC_FLAGS"              => "0x0"
  "XPC_SERVICE_NAME"       => "0"
  "HOME"                   => "/Users/Lionel"
  "SHLVL"                  => "1"
  "DYLD_LIBRARY_PATH"      => ":/opt/intel/mkl/lib:/opt/intel/lib:/Users/Lionel…
  "LOGNAME"                => "Lionel"
  ⋮                        => ⋮
```

But it's not the case when I call the same `ENV` in Atom or Juno IDE ...
I can push my variable it to the `ENV` list (see image bellow) but the problem is still there : the library libmkl_rt can not be loaded.

![capture d ecran 2015-10-19 a 16 21 52](https://cloud.githubusercontent.com/assets/951626/10580410/b17d2f76-767d-11e5-822a-0b5859222c25.png)

One more strange thing : I've tried to load the VML (par of intel MKL) julia Package. In the REPL everything is fine :
```julia
julia> VML.vml_get_mode()
ERROR: UndefVarError: VML not defined

julia> using VML

julia> VML.vml_get_mode()
0x00001a02
```

But in Atom I get a strange behaviour : I first try to load the package (which leads to the dll not found exception). When I try to load it a second time it looks like it's ok .... but in fact, it is not

![capture d ecran 2015-10-19 a 16 36 54](https://cloud.githubusercontent.com/assets/951626/10580863/feec76ac-767f-11e5-91ad-eea29330e5b4.png)

Any advice to sort this out ?

Please, see : https://github.com/JuliaLang/VML.jl/pull/3
And eventually : http://discuss.junolab.org/t/failed-to-load-intel-mkl-specificly-on-juno-with-ccall/392/5

Many thanks,
Lionel

**Comment by Varanas** [comment]
You should get the environment variables into Atom if you start it from the command line.

About the `Image not found` error after adding `DYLD_LIBRARY_PATH` to `ENV`: You seem to have forgotten the leading `:` in front of the path (judging by you screenshot).

So hopefully either starting Atom from the terminal (and thus importing the correct enironment variable) or fixing the typo in your code should do the trick.

**Comment by lionpeloux** [comment]
I effectively get all the env variables when launching atom with the `atom` command from the terminal.

Then, this sample of code works fine :
```julia
function myasum(n::Integer, X::Vector{Float64}, incx::Integer)
  ccall((:dasum, :libmkl_rt),
        Float64,
        (Ptr{Int64}, Ptr{Float64}, Ptr{Int64}),
        &n, X, &incx)
end

myasum(3,Float64[1,2,3],1)
```

Thanks for clarifying.
Lionel

**Comment by Varanas** [comment]
I don't know, but suspect that this isn't intended behaviour (the part with actively setting `ENV` and `dlopen` still not working -- Atom not importing `PATH` when not started from the shell as a known issue).

What you could also try as a workaround is setting [`Libdl.DL_LOAD_PATH`](http://docs.julialang.org/en/latest/stdlib/libdl/#Libdl.DL_LOAD_PATH) because `dlopen` should use that for looking up libraries first...
Also: There's not much I know about the how the interaction between `ENV` and `dlopen` and the actual system environment variables actually works, only about how I would suspect them to -- therefore it's my debugging advice/help is more like wildely guessing at stuff ;) You may want to ask in the mailing list about this (and link to this issue) -- someone there surely knows more about that stuff than me.
