### ISSUE TITLE
Completions at console 

### ISSUE THREAD

**Issue by spencerlyon2** [JunoLab/atom-julia-client#57]
It would be great to have completions at the console. 

@one-more-minute,  any idea why they don't work out of the box? We have the console grammar specified as `source.julia` and everything is properly scoped and highlighted. I feel like that should be enough to make it work.

**Comment by one-more-minute** [comment]
Root issue is https://github.com/atom/autocomplete-plus/issues/383. I imagine it wouldn't be *too* hard to modify where the autocomplete triggers, but haven't dug into the code much either.

**Comment by pfitzseb** [comment]
Done.
