### ISSUE TITLE
Instill error: atom

### ISSUE THREAD

**Issue by boyuan-zhang** [JunoLab/atom-julia-client#578]
Installing “julia-client@0.8.12-alpha” failed:

> @pfitzseb/node-pty-prebuilt@0.9.0-alpha13 install /private/var/folders/8m/nw8n4_sn6ds6l82jf80ss5lc0000gn/T/apm-install-dir-119626-1586-gryeg1.xsnb7/node_modules/julia-client/node_modules/@pfitzseb/node-pty-prebuilt
> prebuild-install || node scripts/install.js

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
prebuild-install WARN install No prebuilt binaries found (target=2.0.18 runtime=electron arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp verb cli [ '/Applications/Atom copy.app/Contents/Resources/app/apm/bin/node',
gyp verb cli   '/Applications/Atom copy.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/Applications/Atom copy.app/Contents/Resources/app/apm/bin/python-interceptor.sh" in the PATH
gyp verb `which` succeeded /Applications/Atom copy.app/Contents/Resources/app/apm/bin/python-interceptor.sh /Applications/Atom copy.app/Contents/Resources/app/apm/bin/python-interceptor.sh
gyp verb check python version `/Applications/Atom copy.app/Contents/Resources/app/apm/bin/python-interceptor.sh -c "import platform; print(platform.python_version());"` returned: "3.7.3\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom copy.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom copy.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom copy.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Applications/Atom copy.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom copy.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/8m/nw8n4_sn6ds6l82jf80ss5lc0000gn/T/apm-install-dir-119626-1586-gryeg1.xsnb7/node_modules/julia-client/node_modules/@pfitzseb/node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/8m/nw8n4_sn6ds6l82jf80ss5lc0000gn/T/apm-install-dir-119626-1586-gryeg1.xsnb7/package.json'
npm WARN apm-install-dir-119626-1586-gryeg1.xsnb7 No description
npm WARN apm-install-dir-119626-1586-gryeg1.xsnb7 No repository field.
npm WARN apm-install-dir-119626-1586-gryeg1.xsnb7 No README data
npm WARN apm-install-dir-119626-1586-gryeg1.xsnb7 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pfitzseb/node-pty-prebuilt@0.9.0-alpha13 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pfitzseb/node-pty-prebuilt@0.9.0-alpha13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by pfitzseb** [comment]
Should be fixed now.
