### ISSUE TITLE
(Info Needed) How can prevent Julia Client from starting on Atom startup?

### ISSUE THREAD

**Issue by Cavenfish** [JunoLab/atom-julia-client#589]
I just installed Julia client, I enjoyed it but hate that when I open other projects in Atom (especially non-julia ones) Julia client will start up and make the REPL, workspace, documentation and plots pane pop open and shove all my previously organized work off to the side. 

I only want Julia client (and all the extra windows) to open when I open it myself, what do I need to do to achieve this result?

**Comment by pfitzseb** [comment]
Go to the julia-client settings (e.g. with `Ctrl-J Ctrl-,`) and take a look at UI Options > Layout Options > Open Default Panes on Startup.

**Comment by Cavenfish** [comment]
@pfitzseb Thank You!

**Comment by ptoche** [comment]
Are the ``julia-client`` settings hidden somewhere? 

<img width="1437" alt="julia" src="https://user-images.githubusercontent.com/6339274/114253050-41ce9d00-995d-11eb-80fb-38f66f0f3baa.png">

Thanks and sorry for hijacking this thread, but it comes up top in Google searches.
