### ISSUE TITLE
Inline results should stay on the line where they were generated

### ISSUE THREAD

**Issue by malmaud** [JunoLab/atom-julia-client#60]
If if I evaluate a an expression (with 'Cmd+Return'), get an inline result, and then push Return, the inline result goes to new line instead of sticking to the line that generated the result.

I presume this isn't intended, but please correct me if it is.

**Comment by Varanas** [comment]
This shouldn't be happening if you're on `ink`- master (and doesn't happen for me on Windows).

**Comment by malmaud** [comment]
Right again.
