### ISSUE TITLE
Julia automaticly exits immediately after starting

### ISSUE THREAD

**Issue by coldinjecition** [JunoLab/atom-julia-client#600]
Julia automaticly exits right after I press enter, without showing any error message. Even the startup files of both Juno and Julia weren't run.
Julia works fine outside Atom.
uber-juno installed all the other packages but failed to install julia-client so I installed it manually. Is it because I missed something?

**Comment by pfitzseb** [comment]
What OS are you on and which version of julia-client do you have installed?

**Comment by coldinjecition** [comment]
> What OS are you on and which version of julia-client do you have installed?

The OS is win10, and the version of julia-client is 0.9.4

**Comment by pfitzseb** [comment]
Alright, can you open the Atom developer tools with <kbd>Ctrl-Shift-I</kbd> and report any errors in the Console tab?

**Comment by coldinjecition** [comment]
Julia exited with Error: Cannot find module '..\build\Debug\conpty.node'.
Uncaught (in promise) Error: Cannot find module '..\build\Debug\conpty.node'

**Comment by coldinjecition** [comment]
I see 2 error messages:
Julia exited with Error: Cannot find module '..\build\Debug\conpty.node'.
Uncaught (in promise) Error: Cannot find module '..\build\Debug\conpty.node'

**Comment by coldinjecition** [comment]
> Alright, can you open the Atom developer tools with Ctrl-Shift-I and report any errors in the Console tab?

I see these 2 error messages:
Julia exited with Error: Cannot find module '..\build\Debug\conpty.node'.
Uncaught (in promise) Error: Cannot find module '..\build\Debug\conpty.node'
so conpty.node is missing

**Comment by coldinjecition** [comment]
I reinstalled julia-client and this problem is resolved, magically
