### ISSUE TITLE
How can I connect a External Process in other machine?

### ISSUE THREAD

**Issue by yeruoforever** [JunoLab/atom-julia-client#616]
Please open your issue at https://github.com/JunoLab/Juno.jl/issues/new unless you've been explicitly pointed here by a Juno developer.

I encountered a problem when I follow this [tutorial](http://docs.junolab.org/v0.7/man/faq.html#Connecting-to-a-Julia-session-on-a-remote-machine-1) for connecting to a Julia session on a remote machine.
After I am succesfully logged into the server and started Julia,I try to execute `using Atom; using Juno; Juno.connect(<RemotePort>)`,but a problem encountered as following `ERROR: IOError: connect: connection refused (ECONNREFUSED)`.

**Comment by pfitzseb** [comment]
Did you set up the port forwarding correctly? Also, any reason not to use the ["new way"](http://docs.junolab.org/dev/man/faq/#Connecting-to-a-Julia-session-on-a-remote-machine-1)?

**Comment by yeruoforever** [comment]
I  tried the [new way](http://docs.junolab.org/dev/man/faq/#Connecting-to-a-Julia-session-on-a-remote-machine-1) and received a warning.
![image](https://user-images.githubusercontent.com/19868036/64943578-af5c3980-d89e-11e9-9177-0fa889c9441b.png)

**Comment by yeruoforever** [comment]
Sorry for providing incomplete information,I have configed Remote Options in Juno and the options as follows.
![image](https://user-images.githubusercontent.com/19868036/64945120-7920b900-d8a2-11e9-8ba2-db843183e072.png)

After restarted Atom and followed the tutoral, I opend terminal successfully,but it is a Windows CMD.
![image](https://user-images.githubusercontent.com/19868036/64945595-7b374780-d8a3-11e9-9e8b-2ec62041d565.png)

**Comment by pfitzseb** [comment]
Oh, you're trying to use a Windows remote? I don't think we support that at all with ftp-remote-edit.
So yes, the old way is probably your best bet if you can figure out why the port forwarding doesn't work properly. Did you make sure you're using the correct `ssh` invocation and that whatever ssh server you've installed on the remote properly supports port forwarding?

**Comment by yeruoforever** [comment]
Thanks for your help.
I solved my problem successfully.
Under your suggestion,I restart my Atom,and do the following:
First, execute the `Julia Client: Connect External Process` command in Juno
![image](https://user-images.githubusercontent.com/19868036/64953834-80ea5880-d8b6-11e9-8e84-d707a0d16125.png)
"Copy"
Select that server in the "Remote" tree view and click the planet icon in the toolbar to start a Julia session on the selected remote machine.
![image](https://user-images.githubusercontent.com/19868036/64954149-49c87700-d8b7-11e9-8a4f-2992c51ca52b.png)
I got a message telling that Juno succesfully connect to an external process.
![image](https://user-images.githubusercontent.com/19868036/64954173-58af2980-d8b7-11e9-964c-6ca0db3983f3.png)
Start Julia and paste `using Atom; using Juno; Juno.connect(<RemotePort>)`
![image](https://user-images.githubusercontent.com/19868036/64954488-4e415f80-d8b8-11e9-8daa-64a7b5adf94b.png)
Despite the error,everything works properly.
![image](https://user-images.githubusercontent.com/19868036/64954853-4fbf5780-d8b9-11e9-84a5-783efe276051.png)
If possible, it’s perfect to modify the background color of the terminal font.

Thanks again to the contributions of Juno members.

**Comment by pfitzseb** [comment]
That's kinda surprising, but also very cool. Great to see you could solve this. If I get some time to look into it I'll make this more seamless on Windows (https://github.com/JunoLab/Juno.jl/issues/365).
