### ISSUE TITLE
Make error display persistent

### ISSUE THREAD

**Issue by malmaud** [JunoLab/atom-julia-client#62]
Currently, if you evaluate a whole buffer (with 'cmd+shift+return'), and an error occurs, it's displayed in the Atom non-modal dialogue which disappears after a few seconds. It would be nice if there was a way to keep the error message persistent so I can view it as a I debug the error.

**Comment by Varanas** [comment]
fixed in https://github.com/JunoLab/Atom.jl/pull/15

**Comment by malmaud** [comment]
Awesome.
