### ISSUE TITLE
Feature request: use special comment lines to divide code into notebook-like cells

### ISSUE THREAD

**Issue by cdsousa** [JunoLab/atom-julia-client#63]
I love working in Jupyter but I miss a full fledged editor too many times.
On the other hand I'm also liking working in Atom+atom-julia-client but then I miss the custom block/cell code division.

I think the approach Matlab editor uses for solving this is a good trade-off.

Do you think it would be feasible to have a special comment line (e.g., `## this splits cells` or `#== this  splits cells ==#`) and a key shortcut to evaluate the cursor current cell?

**Comment by Varanas** [comment]
:+1:
Not sure what syntax would be better, but I kinda like `##` since it's close to matlab and could be interpreted as markdown as well -- you jsut take a `h2` and structure your code with that.

**Comment by cdsousa** [comment]
Let me add that displaying the results of each cell inline, right before the next cell division, would be awesome and would make Atom work more like a notebook. I guess that is harder from a technical perspective though.

**Comment by spencerlyon2** [comment]
I like the idea of cells, good suggestion. 

But I also don't want my editor to become a notebook so I don't know that I'm on board with holding all results to the bottom of each cell. Given that we don't have a harsh of a visual break between cells I think it would be confusing to collect results at cell breaks

**Comment by Varanas** [comment]
Yeah, I think I'd prefer the results to stay inline, i.e. have the cell-evaluation work like manually evaling all lines in the cell instead of working like the `eval file` command.

**Comment by nilshg** [comment]
Maybe a compromise would be to have cell Eval when evaluating the cell division line, and line eval for all other lines?

**Comment by spencerlyon2** [comment]
I think that another keybindings for cell eval is fine to distinguish
between line and cell eval. The discussion above was about where cell eval
output should go.

// Spencer

**Comment by Varanas** [comment]
Once https://github.com/atom/atom/pull/9930 lands, we could easily implement @cdsousa's suggestion (along with a setting to switch to sequential inline evaluation of all lines in the cell).

**Comment by CarloLucibello** [comment]
atom/atom#9930 has been merged

**Comment by ChrisRackauckas** [comment]
Would this be a good time to revive this?

**Comment by cdsousa** [comment]
I've just noticed that [Hydrogen](https://atom.io/packages/hydrogen) now supports this (just search for "cell" in the page).
It uses a syntax I'm not a big fan, but maybe if this gets implemented here it would be good to be compatible.

**Comment by dgleich** [comment]
I would dearly love to have this feature. So much so that I'd been looking at what might be necessary to implement it. 

In Hydrogen, the code to select the current cell is (https://github.com/nteract/hydrogen/blob/d850f50df78e20ff7d5918884155bb67bfa02cde/lib/code-manager.coffee): 
~~~~
    getCurrentCell: ->
        buffer = @editor.getBuffer()
        start = buffer.getFirstPosition()
        end = buffer.getEndPosition()
        regexString = @getRegexString @editor

        unless regexString?
            return [start, end]

        regex = new RegExp regexString
        cursor = @editor.getCursorBufferPosition()

        while cursor.row < end.row and @isComment cursor
            cursor.row += 1
            cursor.column = 0

        if cursor.row > 0
            buffer.backwardsScanInRange regex, [start, cursor], ({range}) ->
                start = range.start

        buffer.scanInRange regex, [cursor, end], ({range}) ->
            end = range.start

        console.log 'CellManager: Cell [start, end]:', [start, end],
            'cursor:', cursor

        return [start, end]
~~~~

The Regex just checks if this is a "cell delimiter line" so I'm sure it would be easy to substitute in a regex for "##" until something else emerges.

Then in terms of atom-juno-client, it seems like you'd just need to either update the blocks.coffee code (https://github.com/JunoLab/atom-julia-client/blob/master/lib/misc/blocks.coffee) to add something about the cell...

Or maybe write a cells.coffee set of code with a 'get' function.

Finally, then you'd need to add something to evaluation.coffee (https://github.com/JunoLab/atom-julia-client/blob/master/lib/runtime/evaluation.coffee) to use the cell instead of the block.

I have _zero_ free time, and have never done anything with coffee, etc. but I might be able to defer more important work to do this :)

**Comment by JobJob** [comment]
I picked up from @dgleich's comment above, and got an initial version of this working. I don't really have time to make this better, and don't think it's quite ready for merging, but the commit is here if someone wants to run with it: https://github.com/JobJob/atom-julia-client/commit/13eb9bbc8fba127e086aef69468596e37441e902

It just adds one command: `julia-client:run-cell`. You separate cells with `#---`(delimiter is set [here](https://github.com/JobJob/atom-julia-client/blob/poor-mans-cell-eval/lib/misc/cells.coffee#L10)) and it will run the code in the cell the cursor is currently in.

**Comment by dgleich** [comment]
Just wanted to add some kudos here! This is great to have!

**Comment by ChrisRackauckas** [comment]
Should this be closed now?

**Comment by pfitzseb** [comment]
Sure, makes sense.
