### ISSUE TITLE
Switch from formatter.js to JuliaFormatter.jl

### ISSUE THREAD

**Issue by aminya** [JunoLab/atom-julia-client#634]
Shouldn't we switch to JuliaFormatter.jl for formatting the code from formatter.js?
https://github.com/domluna/JuliaFormatter.jl/
@domluna

formatter.js is slow and takes some time for execution:
https://github.com/JunoLab/atom-julia-client/blob/master/lib/runtime/formatter.js

Also, if we switch we can have an option for not breaking the lines and just use soft wrap already available in Atom.

https://github.com/domluna/JuliaFormatter.jl/issues/19

**Comment by aviatesk** [comment]
formatter.js is just a frontend code for our formatting task, as its backend DocumentFormat.jl was initially used, but then switched to JuliaFormatter.jl.

> formatter.js is slow and takes some time for execution:

It just happens on the first time execution, right ? I didn't take benchmarks of the JIT compilation between those packages, but I don't care it unless it's unbearably slow.

**Comment by aminya** [comment]
> > formatter.js is slow and takes some time for execution:
> 
> It just happens on the first time execution, right? I didn't take benchmarks of the JIT compilation between those packages, but I don't care it unless it's unbearably slow.

I have tried many times, and it is slow. I think in a session it compiles only once, but everything is changed if you open a new session.

**Comment by aviatesk** [comment]
yeah, the same goes for every other Juno runtime features.

**Comment by aminya** [comment]
Isn't it possible to compile it statically? Using PackageCombiler.jl

**Comment by pfitzseb** [comment]
> I think in a session it compiles only once, but everything is changed if you open a new session.

Don't start as many new sessions then?
