### ISSUE TITLE
Cannot be started or uninstalled

### ISSUE THREAD

**Issue by hhutyou** [JunoLab/atom-julia-client#638]
Julia-client cannot be started when I open Atom. No Julia package can be found. And julia-client can not be uninstalled, like my computer is crashed.

**Comment by hhutyou** [comment]
![Snipaste_2019-10-12_12-10-14](https://user-images.githubusercontent.com/33830655/66704368-46bf7b80-ece9-11e9-9fa0-de278488fd33.png)

The setting panel of julia-client seems to be stuck

**Comment by pfitzseb** [comment]
Try the installation intructions described [here](https://discourse.julialang.org/t/ann-juno-0-11/29644).

**Comment by hhutyou** [comment]
I uninstalled atom and julia, and install JuliaPro. It works now.
