### ISSUE TITLE
Evaluating code over Julia-Client service

### ISSUE THREAD

**Issue by aminya** [JunoLab/atom-julia-client#658]
How can I evaluate a Julia code over Julia-Client service?
I have added this to my Atom package:
```json
  "consumedServices": {
    "julia-client": {
      "versions": {
        "0.1.0": "consumeClient"
      }
    }

  },
```
Inside the code I have this:
```coffee
  consumeClient: (client) ->
    # getting client object
    @client = client
```

But when I want to evaluate a code I cannot run this for example:
```coffee
    atom.commands.add 'atom-workspace', 'julia-client:myEval': (event) ->
      @client.msg 'eval', 'a=2+2'
```
Gives:
```
TypeError: Cannot read property 'msg' of undefined
```
There is no example or documentation on how to set the connection here (http://docs.junolab.org/latest/devdocs/communication/)

**Comment by aviatesk** [comment]
nice try, you can see [language-weave](https://github.com/JunoLab/language-weave/blob/master/lib/main.js) as such an example.

**Comment by aminya** [comment]
@aviatesk how does weave function gets access to juliaClient. I don't see the consumeJuliaClient  being called
https://github.com/JunoLab/language-weave/blob/a966a5c52c0a402e038d9177e24ca8b59791006b/lib/main.js#L31
