### ISSUE TITLE
No longer works after update to 12.0

### ISSUE THREAD

**Issue by YorkerCoder** [JunoLab/atom-julia-client#688]
I upgraded my version of the Julia client to 12.0 and I have no prompt in the terminal.

**Comment by hanjo-kim** [comment]
Have you tried this? It worked for me. 
 
http://docs.junolab.org/latest/man/faq/#Juno-doesn't-work-properly-after-an-Atom-update.-What-do-I-do?-1

**Comment by YorkerCoder** [comment]
Thank you for the help, the link solved it. I had to uninstall and reinstall them.
-------- Original message --------From: hanjo-kim <notifications@github.com> Date: 2/18/20  15:37  (GMT-05:00) To: JunoLab/atom-julia-client <atom-julia-client@noreply.github.com> Cc: YorkerCoder <emirh1231@gmail.com>, Author <author@noreply.github.com> Subject: Re: [JunoLab/atom-julia-client] No longer works after update to 12.0 (#688) Have you tried this? It worked for me.
http://docs.junolab.org/latest/man/faq/#Juno-doesn't-work-properly-after-an-Atom-update.-What-do-I-do?-1

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/JunoLab/atom-julia-client/issues/688?email_source=notifications\u0026email_token=ALOGMKWU6VOMSVZJGJJLL53RDRBHPA5CNFSM4KW5ULRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMETJTI#issuecomment-587805901",
"url": "https://github.com/JunoLab/atom-julia-client/issues/688?email_source=notifications\u0026email_token=ALOGMKWU6VOMSVZJGJJLL53RDRBHPA5CNFSM4KW5ULRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMETJTI#issuecomment-587805901",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Myrddinlefou** [comment]
Thank you Hanjo-kim, I have the same problem and your solution work for me.
