### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by Varanas** [JunoLab/atom-julia-client#72]
We desperately need tests for all parts of Juno, especially the Atom side.

**Comment by nilshg** [comment]
Not sure I'll find time in the near future, but would be happy to contribute if I do. Do you have any pointers for an intro to tests in Julia? Never developed a package myself, so not sure where to start.

**Comment by Varanas** [comment]
The stuff in `Atom.jl/display` should be easily testable since it's mostly rendering stuff. If you don't get the expected output for the given method, it's an error. 

But the communication? No clue, really. We would probably have to set up a server that mimicks what Atom's doing or at least echos back every message we send to it. I guess.

The Atom side is a bit more tricky, imho, although Atom does have a complete testing framework. I just dunno how it works... Best way to learn it is probably to look at [Atom's tests](https://github.com/atom/atom/tree/master/spec).

**Comment by one-more-minute** [comment]
Massive +1. What we really need is a full integration test, e.g. open atom, `2+2`, `Cmd-Enter`, check that `4` pops up, same for plots and so on. I'm not sure how easy that is to do, but it seems much more worthwhile than testing individual parts that might go out of sync with each other anyway. Perhaps by launching commands programmatically and then checking the DOM?

Beyond that I think the best way to ensure robustness is to do some kind of fuzzing – simulate thousands of user events like input, console input, autocomplete requests etc. over a few hours and check for unexpected behaviour, memory leaks and so forth.

If we can't launch Atom on Travis, we might have to set up a custom AWS server as do CI on there – let's get some tests running locally before we worry about that, though.

**Comment by Varanas** [comment]
Atom has some [integration tests](https://github.com/atom/atom/blob/master/spec/integration/startup-spec.coffee) and I agree, we should have them too. Still, I feel like unit tests may be easier and equally important, especially since they help uncover design flaws like unsufficient separation between classes or whatnot.

**Comment by one-more-minute** [comment]
This has begun in the `spec` folder! Currently we test the comm link, with more to come.
