### ISSUE TITLE
check if focusutils.js works on remote machine

### ISSUE THREAD

**Issue by aviatesk** [JunoLab/atom-julia-client#739]
I found in julia-client we don't use [`ink.Opener.open`'s `remote` option](https://github.com/JunoLab/atom-ink/blob/master/lib/util/opener.js#L31) at all.
Fortunately we only have one single feature who consumes `ink.Opener.onDidOpen` emission:

> focusutils.js

https://github.com/JunoLab/atom-julia-client/blob/master/lib/ui/focusutils.js#L69-L71

But obviously it's better to be fixed. I _guess_ just using [`allowremote`](https://github.com/JunoLab/atom-ink/blob/master/lib/util/opener.js#L8) global instead of `remote` optional argument might be enough, but not sure.
What do you think on this @pfitzseb ?

**Comment by pfitzseb** [comment]
I'm 99% sure the `remote` option is completely unused and could be safely removed.

**Comment by aviatesk** [comment]
ah yeah I double checked just now, and it's certainly unused anymore.
