### ISSUE TITLE
printing issue in terminal REPL

### ISSUE THREAD

**Issue by Varanas** [JunoLab/atom-julia-client#74]
Occurs when starting a client that runs in the REPL (via `Ctrl-Alt-J Ctrl-Alt-R`):
![console](https://cloud.githubusercontent.com/assets/6735977/12026405/60b31b82-adb9-11e5-82af-91799806f7e4.PNG)

**Comment by one-more-minute** [comment]
Ref https://github.com/JuliaLang/julia/issues/12150, I think

**Comment by one-more-minute** [comment]
Moot, since we removed the terminal repl option anyway
