### ISSUE TITLE
Error in LinkedList displays

### ISSUE THREAD

**Issue by nilshg** [JunoLab/atom-julia-client#75]
Has anyone seen this? When trying to define a function, I get:
 
````
MethodError: `drop` has no method matching drop(::Int64, ::Lazy.LinkedList)
you may have intended to import Base.drop
 in yieldto at task.jl:71
 in wait at task.jl:371
 in wait at task.jl:286
 in wait at task.jl:108
 [inlined code] from C:\Users\ngudat\.julia\v0.4\Lazy\src\dynamic.jl:69
 in anonymous at C:\Users\ngudat\.julia\v0.4\Atom\src\eval.jl:50
 in handlemsg at C:\Users\ngudat\.julia\v0.4\Atom\src\comm.jl:63
 [inlined code] from C:\Users\ngudat\.julia\v0.4\Atom\src\comm.jl:18
 in anonymous at task.jl:63
````

For some reason, I can define a function without arguments, and the linked list including the one method is shown correctly. Once I give the functoin an actual argument, the error occurs (even if it is a new function, i.e. there's no overloading so the REPL output would still be `x (generic function with 1 method)`

I should be on all relevant master branches, and have just removed and cloned Lazy.jl again to be sure.

**Comment by one-more-minute** [comment]
Is this working now? v0.4 introduced some naming conflicts with Lazy.jl but those should be fixed.

**Comment by nilshg** [comment]
Sorry for late reply, yes, this is fixed now.
