### ISSUE TITLE
Notification support on Windows

### ISSUE THREAD

**Issue by MikeInnes** [JunoLab/atom-julia-client#78]
[API reference](https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md#windows). Notifications don't show up for me at all, and it sounds like they aren't easy to support on Windows versions below 10, so maybe we can switch to using the tray API.

**Comment by Varanas** [comment]
[Ref to the tray API](https://github.com/atom/electron/blob/master/docs/api/tray.md). Doesn't look like too much trouble to implement a balloon notification.

**Comment by Varanas** [comment]
Notifications actually work on Atom master with the current implementation, btw.

**Comment by MikeInnes** [comment]
Ah ok that's great. I think the tray icon will work on windows below 10, which still seems to be pretty popular.

**Comment by ChrisRackauckas** [comment]
In previous versions they never showed up for me, but they are showing up for me now. Looks great, gives me a "bing!" when the computation is done. Nice work.

**Comment by MikeInnes** [comment]
Great – is that on windows 10 as well?

**Comment by ChrisRackauckas** [comment]
Yes, this is Windows 10. Now after using it for awhile... is there a way to control it better? Let, set an option that if an evaluation takes less than 10 seconds don't give a notification? The bing sound is great for longer computations, but it started to become a lot.

FYI, the bing works perfectly. It gets the standard Windows 10 notification sound so if someone modified the theme it uses that. So other than more control, this is solid.

**Comment by MikeInnes** [comment]
Does the notification come up even if you stay inside Juno? They shouldn't appear if the Juno window is still focused. In my experience that means they only come occasionally and when they're useful, but your usage could well be different.

I like the idea of having a timeout in theory, but worry that the inconsistency could cause confusion. For example, if you start a computation and tab away expecting it to take 10 mins, and it unexpectedly ends after 5s, you'd probably want to be told about that.

**Comment by ChrisRackauckas** [comment]
No, it doesn't come up if I'm still in Juno. But if I scroll something on another window during the 5 second compute it gives the notification, which makes it a little much for multiple monitor setups! It also messes me up because sometimes I run a computation that's supposed to be about 30 minutes, and I leave to go make food, but I never get the bing to come back because I didn't switch from Juno's window. So I think it would be best to have an option in the setup for switching to timing based notifications, with the default being "focus" based (or just have "focus" being a different checkbox so people could mix and match?)

**Comment by MikeInnes** [comment]
Let's try to combine the approaches in a reasonable way, it at all possible.

What we could try is notifying based on activity, i.e. notify regardless of focus if the current window is inactive (no input) for ~10s. That solves the dinner problem.

For the multi-window problem, maybe we should use your timeout idea but try to take account of "unexpected" finishes? i.e. errors. Then if you go away and the computation errors out after 5s you still get notified.

**Comment by ChrisRackauckas** [comment]
That sounds reasonable.

**Comment by MikeInnes** [comment]
Great, well I probably won't get a chance to work on this soon, but if you get a chance to poke around with the code then a patch from you or anyone else would be very welcome. And I'll help out however I can.

**Comment by ChrisRackauckas** [comment]
Notifications seem to have been working well for me on Windows. At least, I can't recall any odd instances in the last few months.

**Comment by MikeInnes** [comment]
Great, will close this for now then.
