### ISSUE TITLE
node-pty-prebuilt needs a bump to 0.10

### ISSUE THREAD

**Issue by jebej** [JunoLab/atom-julia-client#780]
Atom v1.56 includes electron 9 and is incompatible with current node-pty-prebuilt.

```
local.coffee:86 Julia exited with Error: The module '\\?\C:\Users\Jeremy\.atom\packages\julia-client\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

**Comment by pfitzseb** [comment]
Just follow the instructions [here](http://docs.junolab.org/latest/man/update/#.-Update-Atom-Packages) to re-build the native binaries.

**Comment by jebej** [comment]
thanks, I didn't realize that could affect the native binaries without updating the package here.

**Comment by pfitzseb** [comment]
Yeah it's a bit of a mess. In theory Atom detects mismatched native binaries, but that didn't work for this update.
