### ISSUE TITLE
Connect over SSH

### ISSUE THREAD

**Issue by MikeInnes** [JunoLab/atom-julia-client#8]
It would be useful to be able to log in to remote servers and work with Julia processes there. This can be implemented fairly straightforwardly using remote port forwarding.

**Comment by Keno** [comment]
Also have a look at nuclide's remote project thing. It would be lovely to integrate.

**Comment by maximsch2** [comment]
Is there a significant set of features that julia-client needs that are not exposed through IPython notebook/kernel interface? Being able to connect to remote kernels and execute commands there would be really interesting.

**Comment by pixiez** [comment]
is it really not important? or people have better alternatives (e.g. a different IDE)? I find it a crucial feature to be able to run/debug on a remote server (which is generally much more powerful)

**Comment by MikeInnes** [comment]
This actually works pretty well already; see [here](http://docs.junolab.org/latest/man/faq.html#Connecting-to-an-external-julia-session-on-a-remote-machine-1) for docs.

**Comment by FRedBeret** [comment]
@MikeInnes The documentary link that you put (a couple of years ago) seems broken. Could you please post an updated one? Cheers in advance.

**Comment by MikeInnes** [comment]
http://docs.junolab.org/latest/man/faq/#Connecting-to-a-Julia-session-on-a-remote-machine-1
