### ISSUE TITLE
`workspace()` in console leaves you in `LastMain`

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-julia-client#80]
After you run `workspace()` it seems the console ends up in `LastMain`, so the next time you run it you get an error because you're not in `Main`.

I'm guessing this issue will be resolved with @spencerlyon2's work on #34 and JunoLab/Atom.jl#8? (looking forward to that!)

**Comment by one-more-minute** [comment]
That should sort you out!

**Comment by ssfrr** [comment]
rockin, just confirmed it's working. Thanks!
