### ISSUE TITLE
No STDERR on windows 7

### ISSUE THREAD

**Issue by Andy-P** [JunoLab/atom-julia-client#86]
I have been trying out Atom + Julia
Correct Julia code renders inline and println renders both inline and in the console, but there is no feedback when the code generates an error. 

It seems Atom is not displaying STDERR msgs

Atom 1.3.3
atom-julia-client 0.2.0
Julia 0.4.2

**Comment by Varanas** [comment]
Are you on latest master? This came up in the gitter chat once or twice and was fixed by doing [this](https://github.com/JunoLab/atom-julia-client/tree/master/docs#developer-install).

If you don't want to go through that we should be able to get a new version tagged somewhat soonish.

**Comment by one-more-minute** [comment]
Good to see you over these parts @Andy-P! Is this issue fixed for you with the latest update?

**Comment by Varanas** [comment]
Closing this since it most likely isn't an issue on a current version of `julia-client` anymore.
