### ISSUE TITLE
Implement block finding in Atom

### ISSUE THREAD

**Issue by one-more-minute** [JunoLab/atom-julia-client#9]
Currently julia-client calls out to Julia to do things like block finding – that is, determining the section of code to be evaluated when you try to evaluate, for example. However, this is pretty inefficient, involving sending the entire buffer to be parsed by Julia. Instead it would be good to use the existing information provided by Atom's syntax highlighting to scan over the current buffer and pull out blocks from CoffeeScript.

**Comment by spencerlyon2** [comment]
This seems totally doable.

Maybe someone who knows the julia language grammar could pitch in :wink:

**Comment by davidanthoff** [comment]
Maybe jakebolewski/JuliaParser.jl#22 would be an alternative design? Certainly not in the short term, but I'd be interested to get your take on it.

**Comment by spencerlyon2** [comment]
If we've done it right, the grammar definition should give us all the info we need. 

I guess it is possible that it would be more efficient to do this in Julia, but I'm a bit skeptical about this idea given that we would be making an IOish round-trip out and into atom.

**Comment by one-more-minute** [comment]
@spencerlyon2 If you happen to know anyone available with such expertise, their help would be most welcome ;)

I'm more than happy to help out where I can explaining how the current block-finding works and such. It's simple enough, but the Julia code currently doing it is a little abstruse.
