### ISSUE TITLE
Remove firewall dialog on Windows

### ISSUE THREAD

**Issue by davidanthoff** [JunoLab/atom-julia-client#90]
The first time one evaluates a julia expression on windows, the standard windows firewall dialog pops and asks one to enable an exception for atom.exe. It would be nice if that wouldn't show up, ever, given that all communication is local in any case.

My (vague) understanding is that maybe right now the various pieces are listening on all IP addresses, instead of listening only on the loopback address? I think that triggers the firewall dialog on Windows.

For example, [here](https://github.com/JunoLab/atom-julia-client/blob/master/lib/connection/spawnInterruptibleJulia.ps1#L32) it looks to me like ``[IPAddress]::Loopback`` would be more appropriate. But there are probably other places in the code base as well where one should adjust things so that the code only listens on the loopback adapater.

**Comment by Varanas** [comment]
You're right, thanks!
That only gets rid of the `powershell` firewall popup -- not sure where the requests for Atom and Julia are coming from though.

Will have a look at the latter two tomorrow.

**Comment by davidanthoff** [comment]
Yes, and I'm actually not getting a firewall dialog for powershell, it probably already has an exception somewhere on my system. But I am getting a request for Atom.exe, so wherever the atom.exe process is opening a port, that is where it should only open it on loopback. No rush.

**Comment by one-more-minute** [comment]
[Right here](https://github.com/JunoLab/atom-julia-client/blob/c27dc1d56a0b50588b237af78d6c1042e6dcb4a7/lib/connection/tcp.coffee#L38) -- should be easy enough to sort out the node APIs for this.

**Comment by davidanthoff** [comment]
I've never touched node, or javascript, so I'm afraid I won't be able to help :)

**Comment by one-more-minute** [comment]
Meh, JS is just like Julia really, just with more braces :) Let me know if you do want to take the plunge at all and we'll be happy to help you out if you get stuck.

**Comment by davidanthoff** [comment]
I won't be able to do this, sorry.

**Comment by Varanas** [comment]
Atom side is fixed -- I'm not sure why Julia requests anything though. [This](https://github.com/JunoLab/Atom.jl/blob/44215ea00d79ebbcf2f1047d4627a87bfe5c8b7c/src/comm.jl#L22-Lundefined) should default to `localhost`.

**Comment by davidanthoff** [comment]
I don't think julia ever asked on my system, just atom.exe... Thanks!

**Comment by davidanthoff** [comment]
And I guess the powershell script should also only listen on localhost? Probably also just for security, opening a port on all network cards seems to ask for trouble ;)

**Comment by Varanas** [comment]
Yeah, Julia asks as soon as you do any `Pkg` stuff. But if you delete the firewall rule, it asks when evaling something in Atom.

The powershell listening is also fixed :) Thanks for bringing it up!
