### ISSUE TITLE
client doesn't run after last patch

### ISSUE THREAD

**Issue by korantir** [JunoLab/atom-julia-client#93]
To say precisely, julia doesn't evaluate any of strings.

cd : �� 㤠���� ����� ���� "C:\Users\korantir\Google", ⠪ ��� �� �� ����������.
C:\Users\korantir\.atom\packages\julia-client\script\spawnInterruptible.ps1:9 ����:1
+ cd $cwd
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\korantir\Google:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
WARNING: Atom.jl: unrecognised message Dict{AbstractString,Any}("callback"=>2,"type"=>"module").WARNING: Atom.jl: unrecognised message Dict{AbstractString,Any}("callback"=>1,"type"=>"eval").

**Comment by one-more-minute** [comment]
If the Atom packages are up to date, can you try running `Pkg.update()` in Julia? (You may need to go to *Packages->Julia->Open Terminal* and run it from there)

**Comment by korantir** [comment]
Well, thanks Mike. Pkg.update() raised errors with IJulia build and now I have
    
ERROR: LoadError: InitError: UndefVarError: @hook not defined
 in eval at C:\Users\korantir\.julia\v0.4\Requires\src\Requires.jl:3
 [inlined code] from C:\Users\korantir\.julia\v0.4\Requires\src\require.jl:20
 in anonymous at C:\Users\korantir\.julia\v0.4\Requires\src\init.jl:17
 in __init__ at C:\Users\korantir\.julia\v0.4\Requires\src\init.jl:24
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at loading.jl:109
 in require at loading.jl:219
 in stale_cachefile at loading.jl:439
 in recompile_stale at loading.jl:457
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at loading.jl:109
 in require at loading.jl:219
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in process_options at client.jl:308
 in _start at client.jl:411
during initialization of module Requires
while loading C:\Users\korantir\.atom\packages\julia-client\script\boot.jl, in expression starting on line 14

I think we can close this issue, because it looks like julia self problem now.

**Comment by korantir** [comment]
Hm. I deleted "requires" from .julia and reinstalled it with Pkg.update()
Now Pkg.update() raises no errors. Julia runs well from terminal and I still have error in atom.

**Comment by Varanas** [comment]
I think the first error is because there's a strange project path set (with a `:` in it), and the second error is because we depend on an untagged version of `Requires.jl`. cc @one-more-minute.

**Comment by korantir** [comment]
@Varanas Many thanks for answer. Full project path is `C:/Users/korantir/Google Drive/Julia` and it worked fine before patch for a long time. And it has no `:` in itself. I have no idea why it writes `ObjectNotFound: (C:\Users\korantir\Google:String)`. But i'll try to change it tomorrow.

Your second assumption looks absolutely correct. Because one-more-minute added hook macro in it 6 days ago. I tried to upgrade `Requires` from one-more-minute repository by hands, and it helped. God bless you :)

**Comment by Varanas** [comment]
@korantir Glad you got it working! 
The first issue is fixed with [this](https://github.com/JunoLab/atom-julia-client/commit/f4c6b1ed0f132072b8aad5acb47c1d0656a1dad9) -- I just forgot that paths with spaces in them should be quoted.

**Comment by korantir** [comment]
Oh well. You are my hero. Sadly im totally not familiar with coffee or js and couldnt check myself. I had idea about space, but thought that if it went fine, why something should change.
