### ISSUE TITLE
package installation errors from Atom bundle (Windows 8.1 64bit)

### ISSUE THREAD

**Issue by genwei007** [JunoLab/atom-julia-client#96]
![2016-01-30_201754](https://cloud.githubusercontent.com/assets/6006832/12695603/8f7e182e-c78e-11e5-8076-b59738475d8b.png)

**Comment by one-more-minute** [comment]
Thanks for reporting this. You might be able to fix it by removing the `~/.julia/lib` folder.

**Comment by pfitzseb** [comment]
I'll close this, but feel free to reopen if it's still a problem.
