### ISSUE TITLE
LoadError on Julia client startup/evaluation

### ISSUE THREAD

**Issue by eggheaded** [JunoLab/atom-julia-client#97]
Whenever I attempt to evaluate or set Julia-client to run on Atom's startup I get the following error in the console:

`ERROR: LoadError: connect: connection refused (ECONNREFUSED)
 in connect at /home/eghd/.julia/v0.4/Atom/src/comm.jl:23
while loading /home/eghd/.atom/packages/julia-client/script/boot.jl, in expression starting on line 421`

`Julia has stopped: 1, null`

I'm currently using Arch using Julia v0.4.3, both Atom.jl and CodeTools are on master, and the three Atom packages are up to date.

**Comment by Varanas** [comment]
Not quite sure what the issue is here, but could you try something like `Base.connect(4232)` in a julia shell?

**Comment by eggheaded** [comment]
On v0.4.3 Getting:
 `ERROR: connect: connection refused (ECONNREFUSED)
 in connect at socket.jl:667
`
and testing on a similar system running the 0.5 nightly getting: 
`ERROR: connect: connection refused (ECONNREFUSED)
 in yieldto at ./task.jl:74
 in wait at ./task.jl:355
 in wait at ./task.jl:274
 in stream_wait at ./stream.jl:59
 in wait_connected at ./stream.jl:330
 [inlined code] from ./stream.jl:1165
 in connect at ./socket.jl:665
 in eval at ./boot.jl:267
`
Looks like I've got a problem that isn't based on the atom-client; should I close this and look to more general Julia help?

**Comment by Varanas** [comment]
Nah, I don't think that should work if there's no one to connect to. That was just me no thinking stuff through ;)

Just to test whether this is related to your Atom installation/configuration or firewall or something, could you try opening the dev console in Atom via `Ctrl-Alt-i` and then type
```js
net = require('net')
s = net.createServer()
s.listen(12341, 'localhost')
```
and, after that,
```julia
Base.connect(12341)
```
in a Julia shell again?

This will most probably succeed though, and then I'm out of ideas on what to try... :)

**Comment by eggheaded** [comment]
Yep, that succeeded (for anyone else running into this problem and looking through, the dev console is now Ctrl+Shift+i). Still running into that same issue unfortunately. I'll try both fresh Julia and Atom builds and see if I get it running. Thanks for you time!

**Comment by eggheaded** [comment]
Works now with the fresh builds. Ran into #98 even with the appropriate path referenced, restarted Atom directly from the shell as root, (only change I noticed was JuliaParser, CodeTools, and Atom.jl recompiling in Atom's Julia console), and now everything works as intended.

**Comment by Varanas** [comment]
Glad you got it sorted!
